export const SERVICE_PACK_GOVERNANCE_FUNCTION_CODE = 'GOVERNMENT_SERVICE_PACK_INSTITUTIONAL_ACCEPTANCE';

export const SERVICE_PACK_GOVERNANCE_REASON_CODES = {
  NOT_VALIDATED: 'SERVICE_PACK_NOT_TECHNICALLY_VALIDATED',
  VALIDATION_NOT_ACCEPTANCE: 'TECHNICAL_VALIDATION_NOT_INSTITUTIONAL_ACCEPTANCE',
  REVIEW_ACCESS_NOT_ACCEPTANCE_AUTHORITY: 'REVIEW_ACCESS_NOT_ACCEPTANCE_AUTHORITY',
  BLOCKING_FINDING: 'BLOCKING_REVIEW_FINDING_PREVENTS_ACCEPTANCE',
  REVIEWS_INCOMPLETE: 'REQUIRED_REVIEWS_INCOMPLETE',
  ACCEPTANCE_FINGERPRINT_MISMATCH: 'ACCEPTANCE_FINGERPRINT_MISMATCH',
  VERSION_NOT_PENDING_ACCEPTANCE: 'SERVICE_PACK_VERSION_NOT_PENDING_ACCEPTANCE',
  REJECTED_CANNOT_DEPLOY: 'REJECTED_SERVICE_PACK_CANNOT_DEPLOY',
  WITHDRAWN_CANNOT_ACTIVATE: 'WITHDRAWN_SERVICE_PACK_CANNOT_ACTIVATE',
  PRIOR_ACCEPTANCE_INVALID: 'PRIOR_ACCEPTANCE_INVALID_FOR_VERSION',
  AUTHORITY_REVIEW_CANNOT_AUTHENTICATE_SOURCE:
    'AUTHORITY_REVIEW_CANNOT_AUTHENTICATE_GOVERNING_SOURCE',
  NON_HUMAN_CANNOT_ACCEPT: 'NON_HUMAN_IDENTITY_CANNOT_INSTITUTIONALLY_ACCEPT',
  AI_CANNOT_ACCEPT: 'AI_IDENTITY_CANNOT_INSTITUTIONALLY_ACCEPT',
  SERVICE_IDENTITY_CANNOT_ACCEPT: 'SERVICE_IDENTITY_CANNOT_INSTITUTIONALLY_ACCEPT',
  SPOOFED_ACCEPTING_IDENTITY: 'CLIENT_SUPPLIED_ACCEPTING_IDENTITY_FORBIDDEN',
  REVIEWER_COMMENT_NOT_AUTHORITY: 'REVIEWER_COMMENT_DOES_NOT_CREATE_AUTHORITY',
  VALIDATED_TO_ACTIVE_FORBIDDEN: 'VALIDATED_TO_ACTIVE_TRANSITION_FORBIDDEN',
} as const;

export const FORBIDDEN_CLIENT_GOVERNANCE_FIELDS = [
  'acceptingIdentityId',
  'acceptedByIdentityId',
  'officeholderId',
  'appointmentId',
  'authorityEvaluationRecordId',
  'identityId',
  'reviewerIdentityId',
  'reporterIdentityId',
] as const;

export const BLOCKING_FINDING_SEVERITIES = ['BLOCKING'] as const;

export const SERVICE_PACK_GOVERNANCE_MODEL_NAMES = [
  'ServicePackReview',
  'ServicePackReviewAssignment',
  'ServicePackReviewFinding',
  'ServicePackReviewComment',
  'ServicePackReviewEvidence',
  'ServicePackReviewSignoff',
  'ServicePackAcceptanceRecord',
  'ServicePackRejectionRecord',
  'ServicePackRevisionRequest',
  'ServicePackReviewChainPolicy',
  'ServicePackReviewChainStep',
  'ServicePackGovernanceAuditRecord',
] as const;
