export const ABSEZ_NON_PRODUCTION_MARKER = 'NON_PRODUCTION_ABSEZ_TEMPLATE';

export const ABSEZ_ZONE_ENTERPRISE_DEFAULT_CONFIGURATION_KEY = 'default';

export const ABSEZ_SEZ_LICENCE_SERVICE_PACK_ID = 'absez-sez-business-licence-pack';

export const ABSEZ_SEZ_SERVICE_FAMILY_CODE = 'TEMPLATE-FAMILY-ABSEZ-SEZ-LICENSING';

export const ABSEZ_SEZ_INSTITUTION_CODE = 'TEMPLATE-ABSEZ-LICENSING-INSTITUTION';

export const ABSEZ_SEZ_DEPARTMENT_CODE = 'TEMPLATE-ABSEZ-LICENSING-DEPARTMENT';

export const ABSEZ_SEZ_LICENCE_REFERENCE_PREFIX = 'SEZ-LIC';

export const ABSEZ_ZONE_ENTERPRISE_REFERENCE_PREFIX = 'ZE';

export const ABSEZ_SEZ_AUTHORITY_FUNCTION_CODES = {
  INTAKE: 'TEMPLATE-AUTH-ABSEZ-SEZ-INTAKE',
  COMPLETENESS: 'TEMPLATE-AUTH-ABSEZ-SEZ-COMPLETENESS',
  SUBSTANTIVE_REVIEW: 'TEMPLATE-AUTH-ABSEZ-SEZ-REVIEW',
  DECIDE: 'TEMPLATE-AUTH-ABSEZ-SEZ-DECIDE',
  ISSUE: 'TEMPLATE-AUTH-ABSEZ-SEZ-ISSUE',
  SUSPEND: 'TEMPLATE-AUTH-ABSEZ-SEZ-SUSPEND',
  REVOKE: 'TEMPLATE-AUTH-ABSEZ-SEZ-REVOKE',
  APPEAL: 'TEMPLATE-AUTH-ABSEZ-SEZ-APPEAL',
} as const;

export const ABSEZ_SEZ_TEMPLATE_SERVICE_CODES = {
  APPLY: 'TEMPLATE-ABSEZ-SEZ-BUSINESS-LICENCE',
  RENEW: 'TEMPLATE-ABSEZ-SEZ-LICENCE-RENEWAL',
  SUSPEND: 'TEMPLATE-ABSEZ-SEZ-LICENCE-SUSPENSION',
  REVOKE: 'TEMPLATE-ABSEZ-SEZ-LICENCE-REVOCATION',
  APPEAL: 'TEMPLATE-ABSEZ-SEZ-LICENCE-APPEAL',
} as const;

export const ABSEZ_BOUNDARY_DISCLAIMER =
  'SEZ licence application intake records a request only; payment does not approve or issue a licence.';
