-- Remediation S19: durable operational retries and security telemetry event types

ALTER TYPE "WorkflowDurableJobKind" ADD VALUE IF NOT EXISTS 'OPERATIONAL_COMMUNICATION_DELIVERY_RETRY';
ALTER TYPE "WorkflowDurableJobKind" ADD VALUE IF NOT EXISTS 'OPERATIONAL_INTEGRATION_EXCHANGE_RETRY';

ALTER TYPE "SecurityAuditEventType" ADD VALUE IF NOT EXISTS 'AUTHORITY_EVALUATION_DENIED';
ALTER TYPE "SecurityAuditEventType" ADD VALUE IF NOT EXISTS 'INTEGRATION_AUTHENTICATION_FAILURE';
ALTER TYPE "SecurityAuditEventType" ADD VALUE IF NOT EXISTS 'OPERATIONAL_PROVIDER_MISCONFIGURATION';
ALTER TYPE "SecurityAuditEventType" ADD VALUE IF NOT EXISTS 'PAYMENT_WEBHOOK_FAILURE';
ALTER TYPE "SecurityAuditEventType" ADD VALUE IF NOT EXISTS 'SUSPICIOUS_RECORD_ACCESS_ATTEMPT';
