export const HEALTHCARE_API_TAG = 'healthcare';

export const PLATFORM_ADMIN_HEALTHCARE_ROLE_MARKER = 'PLATFORM_ADMIN';

export const HEALTHCARE_BOUNDARY_DISCLAIMER =
  'Healthcare consent grants purpose-bound access only; consent is not universal permission.';

export const HEALTHCARE_RESEARCH_BOUNDARY_DISCLAIMER =
  'Researcher dataset access is minimum-necessary and does not authorize unrestricted patient browsing.';

export const HEALTHCARE_SAFETY_BOUNDARY_DISCLAIMER =
  'An adverse event report records an allegation; it does not by itself establish treatment causality.';

export const HEALTHCARE_INTEROP_BOUNDARY_DISCLAIMER =
  'Adapter declarations describe capability intent; they do not assert standards compliance or successful clinical transactions.';

export const FORBIDDEN_AI_HEALTHCARE_ACTIONS = [
  'ESTABLISH_ADVERSE_EVENT_CAUSALITY',
  'BYPASS_HEALTHCARE_ACCESS_POLICY',
  'SILENTLY_DELETE_SAFETY_RECORD',
] as const;

export const RESTRICTED_HEALTHCARE_CLASSIFICATIONS = [
  'GENETIC',
  'MENTAL_HEALTH',
  'HIV',
  'SUBSTANCE_USE',
  'REPRODUCTIVE',
  'SEALED',
] as const;

export const HEALTHCARE_REASON_CODES = {
  CONSENT_REVOKED: 'HEALTHCARE_CONSENT_REVOKED',
  PURPOSE_MISMATCH: 'HEALTHCARE_CONSENT_PURPOSE_MISMATCH',
  RESEARCH_ACCESS_EXPIRED: 'HEALTHCARE_RESEARCH_ACCESS_EXPIRED',
  ARBITRARY_PATIENT_BROWSE_DENIED: 'HEALTHCARE_ARBITRARY_PATIENT_BROWSE_DENIED',
  CLASSIFICATION_DENIED: 'HEALTHCARE_CLASSIFICATION_ACCESS_DENIED',
  PLATFORM_ADMIN_BYPASS_DENIED: 'HEALTHCARE_PLATFORM_ADMIN_BYPASS_DENIED',
  EXTERNAL_PROVIDER_SCOPE_DENIED: 'HEALTHCARE_EXTERNAL_PROVIDER_SCOPE_DENIED',
  BULK_ENUMERATION_DENIED: 'HEALTHCARE_BULK_ENUMERATION_DENIED',
  AI_CAUSALITY_DENIED: 'HEALTHCARE_AI_CAUSALITY_DENIED',
  SAFETY_SILENT_DELETE_DENIED: 'HEALTHCARE_SAFETY_SILENT_DELETE_DENIED',
  INTEGRATION_FAILURE_NOT_SUCCESS: 'HEALTHCARE_INTEGRATION_FAILURE_NOT_SUCCESS',
  DISCREPANCY_NOT_SILENT_OVERWRITE: 'HEALTHCARE_DISCREPANCY_NOT_SILENT_OVERWRITE',
} as const;
