export const HEALTHCARE_FOUNDATION_MODEL_NAMES = [
  'HealthcarePatientReference',
  'HealthcareConsentPurposeDefinition',
  'HealthcareConsentVersion',
  'HealthcareConsent',
  'HealthcareConsentScope',
  'HealthcareConsentGrant',
  'HealthcareConsentWithdrawal',
  'HealthcareDataSharingAuthorization',
  'HealthcareResearchConsent',
  'HealthcareGuardianConsentReference',
  'HealthDataSource',
  'HealthDataCustodian',
  'HealthDataRecordReference',
  'HealthDataProvenance',
  'HealthDataVersionReference',
  'HealthDataAccessRecord',
  'HealthDataDisclosureRecord',
  'HealthDataCorrectionRequest',
  'ResearchDataPurpose',
  'ResearchDataset',
  'ResearchDatasetVersion',
  'ResearchDatasetRecordLink',
  'ResearchDataUseRequest',
  'ResearchDataUseApproval',
  'ResearchDataAccessGrant',
  'ResearchDataDisclosure',
  'ResearchDataPseudonymizationRecord',
  'AdverseEventReport',
  'AdverseEvent',
  'SeriousAdverseEvent',
  'AdverseEventAssessment',
  'AdverseEventReportSubmission',
  'ProtocolDeviation',
  'ProtocolViolationReference',
  'SafetySignal',
  'SafetyReview',
  'SafetyEscalation',
  'ClinicalCorrectiveAction',
  'ClinicalPreventiveAction',
  'HealthcareRegulatedEntityReference',
  'HealthcareInspectionReference',
  'HealthcareComplianceMatterReference',
  'HealthcareLicenseIssueReference',
  'HealthcareRegulatorySubmissionReference',
  'HealthcareIntegrationAdapterDeclaration',
  'HealthcareExternalIdentifierMapping',
  'HealthcareIntegrationExchangeRecord',
  'HealthcareDataAccessAudit',
] as const;

export const HEALTHCARE_FOUNDATION_ENUM_NAMES = [
  'HealthcareConsentType',
  'HealthcareConsentRecordStatus',
  'HealthcareAccessBasisKind',
  'HealthcareDataClassification',
  'HealthcareActorPersona',
  'HealthDataRecordStatus',
  'ResearchDatasetStatus',
  'ResearchDataAccessGrantStatus',
  'ResearchPseudonymizationState',
  'AdverseEventReportStatus',
  'AdverseEventCausalityStatus',
  'ClinicalSafetyRecordStatus',
  'HealthcareRegulatedEntityKind',
  'HealthcareIntegrationStandardKind',
  'HealthcareIntegrationExchangeStatus',
] as const;

export const FORBIDDEN_HEALTHCARE_CLIENT_AUTH_FIELDS = [
  'causalityEstablished',
  'causalityAssessmentStatus',
  'assessorIsAi',
  'succeeded',
  'claimsAnonymous',
] as const;
