export const APPLICATION_PROCESSING_MODEL_NAMES = [
  'Application',
  'ApplicationSubmission',
  'Case',
  'CaseStatusHistory',
  'WorkflowDefinition',
  'WorkflowVersion',
  'WorkflowStageDefinition',
  'WorkflowStepDefinition',
  'WorkflowTransitionDefinition',
  'CaseWorkflowInstance',
  'CaseWorkflowStepInstance',
  'CompletenessReview',
  'DeficiencyNotice',
  'ApplicantInformationRequest',
  'CaseAssignment',
  'CaseReferral',
  'CaseReferralResponse',
  'CaseSlaClock',
  'CaseEscalation',
  'CaseIssue',
  'CaseEvent',
  'CaseCommunication',
  'CaseMilestone',
  'CasePublicStatusProjection',
] as const;

export const CASE_EVENT_TYPES = [
  'APPLICATION_RECEIVED',
  'ACKNOWLEDGMENT_ISSUED',
  'CASE_CREATED',
  'WORKFLOW_STARTED',
  'STEP_STARTED',
  'STEP_COMPLETED',
  'STEP_FAILED',
  'COMPLETENESS_REVIEW_STARTED',
  'COMPLETENESS_REVIEW_COMPLETED',
  'DEFICIENCY_ISSUED',
  'APPLICANT_CORRECTION_RECEIVED',
  'REFERRAL_CREATED',
  'REFERRAL_ACKNOWLEDGED',
  'REFERRAL_RESPONSE_RECEIVED',
  'ASSIGNMENT_CREATED',
  'ASSIGNMENT_SUPERSEDED',
  'SLA_CLOCK_STARTED',
  'SLA_CLOCK_PAUSED',
  'SLA_CLOCK_RESUMED',
  'SLA_BREACHED',
  'ESCALATION_CREATED',
  'ISSUE_CREATED',
  'STATUS_CHANGED',
  'SAFE_HALT',
  'SUSPENSION_APPLIED',
] as const;

export const PHASE_7_REFERENCE_FIELDS = [
  'masterAdministrativeFileReference',
  'documentRegisterReference',
  'evidencePacketReference',
  'recordsClassificationReference',
  'retentionLegalHoldReference',
] as const;

export const FORBIDDEN_APPLICATION_AUTHORITY_FIELDS = [
  'hasAuthority',
  'authorityGranted',
  'decisionOutcome',
  'approvalStatus',
  'eligibilityStatus',
  'issuedLicenseId',
  'issuedPermitId',
] as const;

export const FORBIDDEN_CASE_CLIENT_MUTATION_FIELDS = [
  'decisionOutcome',
  'approvalStatus',
  'issuedAt',
  'refusalReason',
] as const;
