export const NON_PRODUCTION_INSTRUMENT_FIXTURE_MARKER = 'NON_PRODUCTION_INSTRUMENT_TEST_ONLY';

export const PROTECTED_INSTRUMENT_STATUS_FIELDS = [
  'lifecycleStatus',
  'publicVerificationStatus',
  'currentVersionId',
  'effectiveUntil',
] as const;

export const CONSEQUENTIAL_LIFECYCLE_EVENT_TYPES = [
  'AMENDED',
  'VARIED',
  'RENEWED',
  'CORRECTED_CLERICAL',
  'REPLACED',
  'SUSPENDED',
  'PARTIALLY_SUSPENDED',
  'REVOCATION_DECIDED',
  'REVOKED',
  'REINSTATED',
  'EXPIRED',
  'SURRENDERED',
  'SUPERSEDED',
  'CLOSED',
] as const;

export const INCOMPATIBLE_CONCURRENT_OPERATIONS: Record<string, string[]> = {
  SUSPENDED: ['AMENDED', 'RENEWED', 'REPLACED'],
  REVOCATION_DECIDED: ['AMENDED', 'RENEWED', 'REPLACED', 'REINSTATED'],
  REVOKED: ['AMENDED', 'RENEWED', 'REPLACED', 'SUSPENDED', 'REINSTATED'],
  EXPIRED: ['AMENDED', 'RENEWED', 'SUSPENDED'],
  SURRENDERED: ['AMENDED', 'RENEWED', 'SUSPENDED', 'REVOKED', 'REINSTATED'],
  SUPERSEDED: ['AMENDED', 'RENEWED', 'SUSPENDED', 'REVOKED'],
  REPLACED: ['AMENDED', 'RENEWED', 'SUSPENDED'],
  CLOSED: ['AMENDED', 'RENEWED', 'SUSPENDED', 'REVOKED', 'REINSTATED'],
};

export const TECHNICAL_ADMIN_ROLE_MARKER = 'TECHNICAL_ADMIN';
