export const PHASE_8G_MODEL_NAMES = [
  'InstrumentLifecycleDecision',
  'OfficialInstrument',
  'OfficialInstrumentVersion',
  'InstrumentLifecycleEvent',
  'InstrumentLifecycleDecisionLink',
  'InstrumentAmendmentRecord',
  'InstrumentRenewalRecord',
  'InstrumentSuspensionRecord',
  'InstrumentRevocationRecord',
  'InstrumentReinstatementRecord',
  'InstrumentReplacementRecord',
  'InstrumentSurrenderRecord',
  'DecisionReviewReference',
] as const;

export const PHASE_8G_ENUM_NAMES = [
  'InstrumentLifecycleDecisionType',
  'InstrumentLifecycleDecisionStatus',
  'OfficialInstrumentType',
  'InstrumentJurisdictionScope',
  'InstrumentLifecycleStatus',
  'InstrumentLifecycleEventType',
  'ReviewStayStatus',
  'ReviewInterimEffect',
  'SurrenderType',
  'PriorVersionTreatment',
] as const;

export const INSTRUMENT_LIFECYCLE_EVENT_TYPES = [
  'ISSUED',
  'BECAME_EFFECTIVE',
  'AMENDED',
  'VARIED',
  'RENEWED',
  'CORRECTED_CLERICAL',
  'REPLACED',
  'SUSPENDED',
  'PARTIALLY_SUSPENDED',
  'REVOCATION_DECIDED',
  'REVOKED',
  'REINSTATED',
  'EXPIRED',
  'SURRENDERED',
  'SUPERSEDED',
  'CLOSED',
] as const;
