export const REVIEW_RECORD_SNAPSHOT_NUMBER_PREFIX = 'RRS';
export const RECONSIDERATION_PROCEEDING_NUMBER_PREFIX = 'RCP';
export const INTERNAL_ADMINISTRATIVE_REVIEW_NUMBER_PREFIX = 'IAR';
export const REVIEW_ASSIGNMENT_NUMBER_PREFIX = 'RAS';
export const REVIEW_SUBMISSION_NUMBER_PREFIX = 'RSB';
export const REVIEW_EVIDENCE_ADMISSION_NUMBER_PREFIX = 'REA';
export const REVIEW_RECOMMENDATION_NUMBER_PREFIX = 'RRC';

export const PHASE_10E_BOUNDARY_DISCLAIMER =
  'Phase 10E records reconsideration and internal administrative review proceedings. Opening review does not alter the original government decision. Staff recommendations and AI assistance are non-final. Technical permission never creates review authority.';

export const FORBIDDEN_CLIENT_REVIEW_FIELDS = [
  'isFinal',
  'decisionStatus',
  'outcome',
  'adminOverride',
  'independenceOverride',
  'systemAdministratorOverride',
] as const;

export const REDRESS_REASON_CODES = {
  ORIGINAL_DECISION_MAKER_BLOCKED: 'ORIGINAL_DECISION_MAKER_BLOCKED',
  MATERIAL_INVOLVEMENT_BLOCKED: 'MATERIAL_INVOLVEMENT_BLOCKED',
  SYSTEM_ROLE_CANNOT_SATISFY_INDEPENDENCE: 'SYSTEM_ROLE_CANNOT_SATISFY_INDEPENDENCE',
  EXPIRED_APPOINTMENT: 'EXPIRED_APPOINTMENT',
  REVOKED_DELEGATION: 'REVOKED_DELEGATION',
  WRONG_JURISDICTION: 'WRONG_JURISDICTION',
  MISSING_AUTHORITY: 'MISSING_AUTHORITY',
  INSUFFICIENT_REVIEWER_LEVEL: 'INSUFFICIENT_REVIEWER_LEVEL',
  INDEPENDENCE_REQUIRES_RECUSAL: 'INDEPENDENCE_REQUIRES_RECUSAL',
  INDEPENDENCE_UNRESOLVED: 'INDEPENDENCE_UNRESOLVED',
  ADMIN_OVERRIDE_FORBIDDEN: 'ADMIN_OVERRIDE_FORBIDDEN',
  TECHNICAL_PERMISSION_NOT_REVIEW_AUTHORITY: 'TECHNICAL_PERMISSION_NOT_REVIEW_AUTHORITY',
  REVIEW_STANDARD_NOT_CONFIGURED: 'REVIEW_STANDARD_NOT_CONFIGURED',
  SNAPSHOT_IMMUTABLE: 'SNAPSHOT_IMMUTABLE',
  POST_DECISION_EVIDENCE_REQUIRED_LABEL: 'POST_DECISION_EVIDENCE_REQUIRED_LABEL',
  AI_RECOMMENDATION_NON_FINAL: 'AI_RECOMMENDATION_NON_FINAL',
  RECOMMENDATION_CANNOT_BE_FINAL: 'RECOMMENDATION_CANNOT_BE_FINAL',
  OPENING_REVIEW_DOES_NOT_ALTER_DECISION: 'OPENING_REVIEW_DOES_NOT_ALTER_DECISION',
  PROCEEDING_TARGET_REQUIRED: 'PROCEEDING_TARGET_REQUIRED',
  DECISION_NOT_FOUND: 'DECISION_NOT_FOUND',
  ASSIGNMENT_DOES_NOT_CREATE_AUTHORITY: 'ASSIGNMENT_DOES_NOT_CREATE_AUTHORITY',
} as const;

export const AUTHORIZED_RECONSIDERATION_STANDARDS = [
  'ORIGINAL_RECORD_ONLY',
  'ORIGINAL_PLUS_PERMITTED_NEW_EVIDENCE',
  'ERROR_REVIEW',
  'MERITS_RECONSIDERATION',
  'OTHER_AUTHORIZED_STANDARD',
] as const;

export const REVIEWER_INDEPENDENCE_OUTCOMES = [
  'INDEPENDENT',
  'CONFLICT_IDENTIFIED',
  'PRIOR_INVOLVEMENT_IDENTIFIED',
  'REQUIRES_RECUSAL',
  'REQUIRES_AUTHORIZED_EXCEPTION',
  'UNRESOLVED',
] as const;

export const INTERNAL_REVIEW_GROUNDS = [
  'AUTHORITY_ERROR',
  'PROCEDURAL_ERROR',
  'EVIDENCE_OMISSION',
  'INCORRECT_CRITERION',
  'CONFLICT',
  'REASONING_DEFECT',
  'NOTICE_DEFECT',
  'AUTOMATION_DEFECT',
  'OTHER_PERMITTED_GROUND',
] as const;

export const FORBIDDEN_AI_REVIEW_ACTIONS = [
  'determine_reconsideration',
  'affirm',
  'reverse',
  'vary',
  'remand',
  'set_aside',
  'decide_credibility',
  'decide_appeal',
] as const;
