export const PHASE_10H_MODEL_NAMES = [
  'RedressRouteDefinition',
  'RedressRouteVersion',
  'RedressRouteEligibleMatter',
  'RedressRouteGround',
  'RedressRouteRemedyDefinition',
  'RedressMatter',
  'RedressFiling',
  'RedressFilingVersion',
  'RedressStandingAssessment',
  'RedressTimelinessAssessment',
  'DeadlineExtensionRequest',
  'RedressAcknowledgment',
  'ComplaintClassification',
  'ComplaintInvestigation',
  'ComplaintFinding',
  'ComplaintResponse',
  'ComplaintCorrectiveAction',
  'ComplaintClosure',
  'AdministrativeCorrectionMatter',
  'ClarificationRequest',
  'ClarificationResponse',
  'AutomationChallenge',
  'AutomationExplanationRecord',
  'AutomationChallengeDisposition',
  'ReviewAssignment',
  'ReviewerIndependenceAssessment',
  'ReviewAuthorityAssessment',
  'ReviewRecordSnapshot',
  'ReconsiderationProceeding',
  'InternalAdministrativeReview',
  'ReviewIssue',
  'ReviewSubmission',
  'ExternalReviewReferral',
  'ExternalReviewPackage',
  'ExternalReviewDetermination',
  'RedressDecision',
  'RedressFinding',
  'RedressReason',
  'RedressRemedy',
  'InterimReliefRequest',
  'ReviewStayRecord',
  'RedressImplementationPlan',
  'RedressImplementationAction',
  'RedressImplementationVerification',
  'RedressNotice',
] as const;

export const PHASE_10H_ENUM_NAMES = [
  'RedressRouteCategory',
  'RedressRouteVersionStatus',
  'RedressMatterStatus',
  'RedressFilingStatus',
  'RedressStandingOutcome',
  'RedressTimelinessOutcome',
  'DeadlineExtensionOutcome',
  'ComplaintClassificationType',
  'ComplaintInvestigationStatus',
  'ComplaintClosureReason',
  'RedressReviewType',
  'ReviewIndependenceOutcome',
  'ReviewAuthorityOutcome',
  'ExternalReviewReferralStatus',
  'ExternalDeterminationAuthenticity',
  'AutomationChallengeDispositionOutcome',
  'RedressDecisionOutcome',
  'RedressDecisionStatus',
  'InterimReliefOutcome',
  'RedressImplementationStatus',
  'RedressSafeHaltReason',
  'RedressNoticeType',
] as const;

export const REDRESS_MATTER_STATUSES = [
  'OPEN',
  'INTAKE',
  'STANDING_ASSESSMENT',
  'TIMELINESS_ASSESSMENT',
  'CLASSIFICATION',
  'INVESTIGATION',
  'REVIEW',
  'EXTERNAL_REFERRAL',
  'DECISION_PENDING',
  'IMPLEMENTATION',
  'CLOSED',
  'SAFE_HALTED',
] as const;

export const REDRESS_FILING_STATUSES = [
  'DRAFT',
  'SUBMITTED',
  'ACKNOWLEDGED',
  'CLASSIFIED',
  'REJECTED',
  'WITHDRAWN',
] as const;
