export const DECISIONS_MODULE_DISCLAIMER =
  'Phase 8A configures institutional decision routes. Catalog configuration does not create final government decisions, issue instruments, or substitute for Phase 4 authority evaluation.';

export const FORBIDDEN_DECISION_BOUNDARY_MODELS = [
  'GovernmentDecision',
  'IssuedInstrument',
  'IssuedLicense',
  'IssuedPermit',
  'IssuedCertificate',
] as const;

export const NON_FINAL_AUTHORITY_ACTIONS = [
  'RETRIEVE',
  'SUMMARIZE',
  'PREPARE',
  'REVIEW',
  'VERIFY',
  'CHECK',
  'RECOMMEND',
  'CONCUR',
  'CONSULT',
  'LIAISE',
] as const;

export const FINAL_DECISION_AUTHORITY_ACTIONS = ['DECIDE', 'APPROVE'] as const;

export const IMMUTABLE_DECISION_TYPE_VERSION_STATUSES = [
  'ACTIVE',
  'SUPERSEDED',
  'RETIRED',
] as const;

export const DECISIONS_EXPLANATION_CODES = {
  DECISION_TYPE_CODE_EXISTS: 'DECISION_TYPE_CODE_EXISTS',
  DECISION_TYPE_VERSION_IMMUTABLE: 'DECISION_TYPE_VERSION_IMMUTABLE',
  DECISION_TYPE_NOT_OPERATIONALLY_AVAILABLE: 'DECISION_TYPE_NOT_OPERATIONALLY_AVAILABLE',
  OUTCOME_NOT_CONFIGURED: 'OUTCOME_NOT_CONFIGURED',
  RECOMMENDATION_NOT_FINAL_DECISION: 'RECOMMENDATION_NOT_FINAL_DECISION',
  NON_DECISION_AUTHORITY_ACTION: 'NON_DECISION_AUTHORITY_ACTION',
  SERVICE_IDENTITY_CANNOT_BE_DECISION_MAKER: 'SERVICE_IDENTITY_CANNOT_BE_DECISION_MAKER',
  CLIENT_CANNOT_SET_LIFECYCLE_STATUS: 'CLIENT_CANNOT_SET_LIFECYCLE_STATUS',
  CATALOG_DOES_NOT_CREATE_DECISION: 'CATALOG_DOES_NOT_CREATE_DECISION',
  ACTIVATION_REQUIRES_ACCEPTANCE: 'ACTIVATION_REQUIRES_ACCEPTANCE',
  ACTIVATION_REQUIRES_CONTROLLED_PATHWAY: 'ACTIVATION_REQUIRES_CONTROLLED_PATHWAY',
  SUPERSESSION_REQUIRES_ACTIVE_PREDECESSOR: 'SUPERSESSION_REQUIRES_ACTIVE_PREDECESSOR',
  RECOMMENDATION_ELEMENT_NOT_FINAL_DECISION: 'RECOMMENDATION_ELEMENT_NOT_FINAL_DECISION',
} as const;
