export const NON_PRODUCTION_DECISIONS_FIXTURE_MARKER = 'NON_PRODUCTION_PHASE_8B_TEST_ONLY';

export const DECISION_NUMBER_PREFIX = 'DEC';
export const READINESS_ASSESSMENT_NUMBER_PREFIX = 'DRA';

export const PHASE_8B_BOUNDARY_DISCLAIMER =
  'Government decisions are official institutional acts by authorized human officeholders. AI assistance, recommendations, and readiness assessments do not constitute decisions.';

export const FORBIDDEN_PHASE_8C_MODELS = ['IssuedLicense', 'IssuedPermit', 'IssuedCertificate'] as const;
export const FORBIDDEN_PHASE_8C_MODELS = [
  'IssuedLicense',
  'IssuedPermit',
  'IssuedCertificate',
] as const;

export const FORBIDDEN_CLIENT_DECISION_FIELDS = [
  'draft',
  'isDraft',
  'approved',
  'refused',
  'issued',
] as const;

export const FORBIDDEN_AI_DECISION_ACTIONS = [
  'APPROVE',
  'REFUSE',
  'CONDITIONALLY_APPROVE',
  'WAIVE',
  'DECIDE_APPEAL',
  'CREATE_AUTHORITY',
  'SIGN',
  'SEAL',
  'ISSUE',
] as const;

export const DECISION_READINESS_REASON_CODES = {
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  CASE_NOT_DECISION_PENDING: 'CASE_NOT_DECISION_PENDING',
  DECISION_TYPE_VERSION_INACTIVE: 'DECISION_TYPE_VERSION_INACTIVE',
  SERVICE_VERSION_MISMATCH: 'SERVICE_VERSION_MISMATCH',
  MASTER_FILE_MISSING: 'MASTER_FILE_MISSING',
  MASTER_FILE_SAFE_HALTED: 'MASTER_FILE_SAFE_HALTED',
  MASTER_FILE_INCOMPLETE: 'MASTER_FILE_INCOMPLETE',
  EVIDENCE_PACKET_MISSING: 'EVIDENCE_PACKET_MISSING',
  EVIDENCE_PACKET_NOT_FROZEN: 'EVIDENCE_PACKET_NOT_FROZEN',
  EVIDENCE_PACKET_WRONG_PURPOSE: 'EVIDENCE_PACKET_WRONG_PURPOSE',
  EVIDENCE_PACKET_SUPERSEDED: 'EVIDENCE_PACKET_SUPERSEDED',
  EVIDENCE_NOT_CURRENT: 'EVIDENCE_NOT_CURRENT',
  PROFESSIONAL_REVIEW_MISSING: 'PROFESSIONAL_REVIEW_MISSING',
  INSPECTION_MISSING: 'INSPECTION_MISSING',
  GOVERNMENT_CONSULTATION_MISSING: 'GOVERNMENT_CONSULTATION_MISSING',
  GOVERNMENT_CONCURRENCE_MISSING: 'GOVERNMENT_CONCURRENCE_MISSING',
  GOVERNMENT_RESPONSE_INVALID: 'GOVERNMENT_RESPONSE_INVALID',
  RETAINED_NATIONAL_DETERMINATION_MISSING: 'RETAINED_NATIONAL_DETERMINATION_MISSING',
  RECOMMENDATION_PRESENT_NONBINDING: 'RECOMMENDATION_PRESENT_NONBINDING',
  DECISION_MAKER_CONFLICTED: 'DECISION_MAKER_CONFLICTED',
  DECISION_MAKER_RECUSED: 'DECISION_MAKER_RECUSED',
  SEGREGATION_OF_DUTY_FAILED: 'SEGREGATION_OF_DUTY_FAILED',
  CO_APPROVAL_REQUIRED: 'CO_APPROVAL_REQUIRED',
  AUTHORITY_DENIED: 'AUTHORITY_DENIED',
  AUTHORITY_BLOCKED: 'AUTHORITY_BLOCKED',
  AUTHORITY_REQUIRES_EXTERNAL: 'AUTHORITY_REQUIRES_EXTERNAL',
  AUTHORITY_SAFE_HALT: 'AUTHORITY_SAFE_HALT',
  APPOINTMENT_INVALID: 'APPOINTMENT_INVALID',
  DELEGATION_INVALID: 'DELEGATION_INVALID',
  OUTCOME_NOT_PERMISSIBLE: 'OUTCOME_NOT_PERMISSIBLE',
  PROCEDURAL_GATE_UNSATISFIED: 'PROCEDURAL_GATE_UNSATISFIED',
  NON_HUMAN_ACTOR: 'NON_HUMAN_ACTOR',
  CASE_MANAGER_NOT_DECISION_AUTHORITY: 'CASE_MANAGER_NOT_DECISION_AUTHORITY',
  TECHNICAL_ADMIN_NOT_DECISION_AUTHORITY: 'TECHNICAL_ADMIN_NOT_DECISION_AUTHORITY',
  DEPARTMENTAL_REVIEW_MISSING: 'DEPARTMENTAL_REVIEW_MISSING',
  EXPLICIT_INTENT_REQUIRED: 'EXPLICIT_INTENT_REQUIRED',
  STALE_AUTHORITY_EVALUATION: 'STALE_AUTHORITY_EVALUATION',
  READINESS_NOT_READY: 'READINESS_NOT_READY',
} as const;

export type DecisionReadinessReasonCode =
  (typeof DECISION_READINESS_REASON_CODES)[keyof typeof DECISION_READINESS_REASON_CODES];
