export const NON_PRODUCTION_SERVICE_FIXTURE_MARKER = 'NON_PRODUCTION_SAMPLE_TEST_ONLY';

export const SERVICE_CHECKLIST_EXPLANATION_CODES = {
  NO_APPROVED_REQUIREMENT_SET: 'NO_APPROVED_REQUIREMENT_SET',
  UNRESOLVED_CONDITIONAL_RULE: 'UNRESOLVED_CONDITIONAL_RULE',
  UNKNOWN_RULE_OPERATOR: 'UNKNOWN_RULE_OPERATOR',
  SUPERSEDED_REQUIREMENT_EXCLUDED: 'SUPERSEDED_REQUIREMENT_EXCLUDED',
  EXPIRED_REQUIREMENT_EXCLUDED: 'EXPIRED_REQUIREMENT_EXCLUDED',
  DOCUMENT_SUBMITTED_NOT_VERIFIED: 'DOCUMENT_SUBMITTED_NOT_VERIFIED',
  PROFESSIONAL_DOCUMENT_CANNOT_USE_FORM_TEXT: 'PROFESSIONAL_DOCUMENT_CANNOT_USE_FORM_TEXT',
  PUBLISHED_VERSION_IMMUTABLE: 'PUBLISHED_VERSION_IMMUTABLE',
} as const;

export type ServiceChecklistExplanationCode =
  (typeof SERVICE_CHECKLIST_EXPLANATION_CODES)[keyof typeof SERVICE_CHECKLIST_EXPLANATION_CODES];

export const REQUIREMENT_SATISFACTION_MECHANISMS = {
  FORM_FIELD: 'FORM_FIELD',
  PROFESSIONAL_DOCUMENT: 'PROFESSIONAL_DOCUMENT',
  DECLARATION: 'DECLARATION',
  EXTERNAL_DETERMINATION: 'EXTERNAL_DETERMINATION',
  INFORMATION_INTAKE: 'INFORMATION_INTAKE',
  OTHER: 'OTHER',
} as const;

export type RequirementSatisfactionMechanism =
  (typeof REQUIREMENT_SATISFACTION_MECHANISMS)[keyof typeof REQUIREMENT_SATISFACTION_MECHANISMS];
