export const NON_PRODUCTION_EVIDENCE_RECORDS_FIXTURE_MARKER =
  'NON_PRODUCTION_EVIDENCE_RECORDS_TEST_ONLY';

export const PHASE_7_BOUNDARY_DISCLAIMER =
  'Phase 7 manages master administrative files, evidence records, and retention. It does not create government decisions or issue licenses, permits, or certificates.';

export const FORBIDDEN_PHASE_7_MODELS = [
  'GovernmentDecision',
  'IssuedLicense',
  'IssuedPermit',
  'IssuedCertificate',
] as const;

export const MASTER_FILE_REFERENCE_PREFIX = 'MAF';
export const DOCUMENT_REFERENCE_PREFIX = 'DOC';
export const EVIDENCE_REFERENCE_PREFIX = 'EVD';
export const PACKET_REFERENCE_PREFIX = 'PKT';
export const CORRECTION_REFERENCE_PREFIX = 'COR';
export const LEGAL_HOLD_REFERENCE_PREFIX = 'HLD';
export const INSPECTION_REFERENCE_PREFIX = 'INS';
export const PROFESSIONAL_REVIEW_REFERENCE_PREFIX = 'PRV';
export const GOVERNMENT_COMMUNICATION_REFERENCE_PREFIX = 'GCR';

export const EVIDENCE_RECORDS_EXPLANATION_CODES = {
  CLIENT_CANNOT_SET_VERIFIED: 'CLIENT_CANNOT_SET_VERIFIED',
  CLIENT_CANNOT_SET_ACCEPTED: 'CLIENT_CANNOT_SET_ACCEPTED',
  CLIENT_CANNOT_SET_SEALED: 'CLIENT_CANNOT_SET_SEALED',
  CLIENT_CANNOT_SET_CONTENT_HASH: 'CLIENT_CANNOT_SET_CONTENT_HASH',
  CLIENT_CANNOT_SET_CLASSIFICATION: 'CLIENT_CANNOT_SET_CLASSIFICATION',
  CLIENT_CANNOT_MASS_ASSIGN_STATUS: 'CLIENT_CANNOT_MASS_ASSIGN_STATUS',
  UNAUTHORIZED_MASTER_FILE_ACCESS: 'UNAUTHORIZED_MASTER_FILE_ACCESS',
  UNAUTHORIZED_EVIDENCE_ACCESS: 'UNAUTHORIZED_EVIDENCE_ACCESS',
  UNAUTHORIZED_PACKET_ACCESS: 'UNAUTHORIZED_PACKET_ACCESS',
  UNAUTHORIZED_LEGAL_HOLD_ACCESS: 'UNAUTHORIZED_LEGAL_HOLD_ACCESS',
  APPLICANT_CANNOT_VERIFY: 'APPLICANT_CANNOT_VERIFY',
  APPLICANT_CANNOT_ACCEPT: 'APPLICANT_CANNOT_ACCEPT',
  VERIFICATION_REQUIRED_BEFORE_ACCEPTANCE: 'VERIFICATION_REQUIRED_BEFORE_ACCEPTANCE',
  DISPUTED_EVIDENCE_CANNOT_BE_ACCEPTED: 'DISPUTED_EVIDENCE_CANNOT_BE_ACCEPTED',
  WITHDRAWN_EVIDENCE_CANNOT_BE_ACCEPTED: 'WITHDRAWN_EVIDENCE_CANNOT_BE_ACCEPTED',
  SUPERSEDED_EVIDENCE_CANNOT_BE_MODIFIED: 'SUPERSEDED_EVIDENCE_CANNOT_BE_MODIFIED',
  QUARANTINED_EVIDENCE_CANNOT_ENTER_PACKET: 'QUARANTINED_EVIDENCE_CANNOT_ENTER_PACKET',
  SEALED_PACKET_CANNOT_BE_MODIFIED: 'SEALED_PACKET_CANNOT_BE_MODIFIED',
  PACKET_FREEZE_IS_IRREVERSIBLE: 'PACKET_FREEZE_IS_IRREVERSIBLE',
  LEGAL_HOLD_BLOCKS_DISPOSITION: 'LEGAL_HOLD_BLOCKS_DISPOSITION',
  CORRECTION_REQUIRES_APPROVAL: 'CORRECTION_REQUIRES_APPROVAL',
  CORRECTION_CANNOT_OVERWRITE_ORIGINAL: 'CORRECTION_CANNOT_OVERWRITE_ORIGINAL',
  INTEGRITY_EVENTS_APPEND_ONLY: 'INTEGRITY_EVENTS_APPEND_ONLY',
  ACCESS_EVENTS_APPEND_ONLY: 'ACCESS_EVENTS_APPEND_ONLY',
  DOCUMENT_VERSION_IMMUTABLE: 'DOCUMENT_VERSION_IMMUTABLE',
  EVIDENCE_RECORD_CANNOT_BE_DELETED: 'EVIDENCE_RECORD_CANNOT_BE_DELETED',
  MASTER_FILE_REQUIRES_CASE: 'MASTER_FILE_REQUIRES_CASE',
  PHASE_7_CANNOT_CREATE_DECISION: 'PHASE_7_CANNOT_CREATE_DECISION',
  PHASE_7_CANNOT_ISSUE_INSTRUMENT: 'PHASE_7_CANNOT_ISSUE_INSTRUMENT',
  AI_CANNOT_VERIFY_INDEPENDENTLY: 'AI_CANNOT_VERIFY_INDEPENDENTLY',
  SERVICE_IDENTITY_CANNOT_ACCEPT_DECISION_SUPPORT:
    'SERVICE_IDENTITY_CANNOT_ACCEPT_DECISION_SUPPORT',
  PROFESSIONAL_REVIEW_NOT_DECISION: 'PROFESSIONAL_REVIEW_NOT_DECISION',
  GOVERNMENT_COMMUNICATION_NOT_CASE_STATUS: 'GOVERNMENT_COMMUNICATION_NOT_CASE_STATUS',
  CUSTODY_CHAIN_REQUIRED: 'CUSTODY_CHAIN_REQUIRED',
  CUSTODY_EVENT_CANNOT_BE_BACKDATED: 'CUSTODY_EVENT_CANNOT_BE_BACKDATED',
  PACKET_MANIFEST_HASH_MISMATCH: 'PACKET_MANIFEST_HASH_MISMATCH',
  UNDISCLOSED_REQUIREMENT_CANNOT_SATISFY: 'UNDISCLOSED_REQUIREMENT_CANNOT_SATISFY',
  RETENTION_ASSIGNMENT_CLIENT_FORBIDDEN: 'RETENTION_ASSIGNMENT_CLIENT_FORBIDDEN',
  CASE_REFERENCE_FIELDS_CLIENT_FORBIDDEN: 'CASE_REFERENCE_FIELDS_CLIENT_FORBIDDEN',
  NON_ACCEPTED_EVIDENCE_IN_DECISION_PACKET: 'NON_ACCEPTED_EVIDENCE_IN_DECISION_PACKET',
  ARCHIVAL_TRANSFER_CANNOT_DESTROY: 'ARCHIVAL_TRANSFER_CANNOT_DESTROY',
  INTEGRITY_MISMATCH_SAFE_HALT: 'INTEGRITY_MISMATCH_SAFE_HALT',
  EVIDENCE_ACCEPTANCE_NOT_APPROVAL: 'EVIDENCE_ACCEPTANCE_NOT_APPROVAL',
} as const;
