export const NON_PRODUCTION_EVIDENCE_RECORDS_FIXTURE_MARKER =
  'NON_PRODUCTION_EVIDENCE_RECORDS_TEST_ONLY';

export const DOCUMENT_NUMBER_PREFIX = 'DOC';

export const DOCUMENT_STORAGE_PROVIDER_IN_MEMORY = 'in-memory';

export const DOCUMENT_INTEGRITY_DISCLAIMER =
  'SHA-256 integrity proves byte preservation only. It does not establish truth, authenticity, legal effect, professional correctness, or issuer authority.';

export const FORBIDDEN_PHASE_7C_MODELS = ['EvidenceVault', 'EvidenceItem'] as const;

export const FORBIDDEN_CLIENT_DOCUMENT_FIELDS = [
  'storageObjectKey',
  'storageProvider',
  'storageVersionId',
  'sha256',
  'malwareScanStatus',
  'authenticityStatus',
  'signatureStatus',
  'sealStatus',
] as const;

export const PHASE_7G_BOUNDARY_DISCLAIMER =
  'Phase 7G governs records retention, legal hold, archival transfer, and controlled disposition. Software defaults do not define institutional retention law or policy.';

export const PHASE_7H_BOUNDARY_DISCLAIMER =
  'Phase 7H evaluates master file completeness and enforces evidence/records boundary invariants. Completeness outcomes do not constitute government approval or refusal.';

export const EVIDENCE_RECORDS_EXPLANATION_CODES = {
  CLIENT_CANNOT_SET_VERIFIED: 'CLIENT_CANNOT_SET_VERIFIED',
  CLIENT_CANNOT_SET_ACCEPTED: 'CLIENT_CANNOT_SET_ACCEPTED',
  CLIENT_CANNOT_SET_SEALED: 'CLIENT_CANNOT_SET_SEALED',
  CLIENT_CANNOT_SET_CONTENT_HASH: 'CLIENT_CANNOT_SET_CONTENT_HASH',
  CLIENT_CANNOT_SET_CLASSIFICATION: 'CLIENT_CANNOT_SET_CLASSIFICATION',
  CLIENT_CANNOT_MASS_ASSIGN_STATUS: 'CLIENT_CANNOT_MASS_ASSIGN_STATUS',
  UNAUTHORIZED_MASTER_FILE_ACCESS: 'UNAUTHORIZED_MASTER_FILE_ACCESS',
  UNAUTHORIZED_EVIDENCE_ACCESS: 'UNAUTHORIZED_EVIDENCE_ACCESS',
  UNAUTHORIZED_PACKET_ACCESS: 'UNAUTHORIZED_PACKET_ACCESS',
  UNAUTHORIZED_LEGAL_HOLD_ACCESS: 'UNAUTHORIZED_LEGAL_HOLD_ACCESS',
  APPLICANT_CANNOT_VERIFY: 'APPLICANT_CANNOT_VERIFY',
  APPLICANT_CANNOT_ACCEPT: 'APPLICANT_CANNOT_ACCEPT',
  VERIFICATION_REQUIRED_BEFORE_ACCEPTANCE: 'VERIFICATION_REQUIRED_BEFORE_ACCEPTANCE',
  DISPUTED_EVIDENCE_CANNOT_BE_ACCEPTED: 'DISPUTED_EVIDENCE_CANNOT_BE_ACCEPTED',
  WITHDRAWN_EVIDENCE_CANNOT_BE_ACCEPTED: 'WITHDRAWN_EVIDENCE_CANNOT_BE_ACCEPTED',
  SUPERSEDED_EVIDENCE_CANNOT_BE_MODIFIED: 'SUPERSEDED_EVIDENCE_CANNOT_BE_MODIFIED',
  QUARANTINED_EVIDENCE_CANNOT_ENTER_PACKET: 'QUARANTINED_EVIDENCE_CANNOT_ENTER_PACKET',
  SEALED_PACKET_CANNOT_BE_MODIFIED: 'SEALED_PACKET_CANNOT_BE_MODIFIED',
  PACKET_FREEZE_IS_IRREVERSIBLE: 'PACKET_FREEZE_IS_IRREVERSIBLE',
  LEGAL_HOLD_BLOCKS_DISPOSITION: 'LEGAL_HOLD_BLOCKS_DISPOSITION',
  CORRECTION_REQUIRES_APPROVAL: 'CORRECTION_REQUIRES_APPROVAL',
  CORRECTION_CANNOT_OVERWRITE_ORIGINAL: 'CORRECTION_CANNOT_OVERWRITE_ORIGINAL',
  INTEGRITY_EVENTS_APPEND_ONLY: 'INTEGRITY_EVENTS_APPEND_ONLY',
  ACCESS_EVENTS_APPEND_ONLY: 'ACCESS_EVENTS_APPEND_ONLY',
  DOCUMENT_VERSION_IMMUTABLE: 'DOCUMENT_VERSION_IMMUTABLE',
  EVIDENCE_RECORD_CANNOT_BE_DELETED: 'EVIDENCE_RECORD_CANNOT_BE_DELETED',
  MASTER_FILE_REQUIRES_CASE: 'MASTER_FILE_REQUIRES_CASE',
  PHASE_7_CANNOT_CREATE_DECISION: 'PHASE_7_CANNOT_CREATE_DECISION',
  PHASE_7_CANNOT_ISSUE_INSTRUMENT: 'PHASE_7_CANNOT_ISSUE_INSTRUMENT',
  AI_CANNOT_VERIFY_INDEPENDENTLY: 'AI_CANNOT_VERIFY_INDEPENDENTLY',
  SERVICE_IDENTITY_CANNOT_ACCEPT_DECISION_SUPPORT:
    'SERVICE_IDENTITY_CANNOT_ACCEPT_DECISION_SUPPORT',
  PROFESSIONAL_REVIEW_NOT_DECISION: 'PROFESSIONAL_REVIEW_NOT_DECISION',
  GOVERNMENT_COMMUNICATION_NOT_CASE_STATUS: 'GOVERNMENT_COMMUNICATION_NOT_CASE_STATUS',
  CUSTODY_CHAIN_REQUIRED: 'CUSTODY_CHAIN_REQUIRED',
  CUSTODY_EVENT_CANNOT_BE_BACKDATED: 'CUSTODY_EVENT_CANNOT_BE_BACKDATED',
  PACKET_MANIFEST_HASH_MISMATCH: 'PACKET_MANIFEST_HASH_MISMATCH',
  UNDISCLOSED_REQUIREMENT_CANNOT_SATISFY: 'UNDISCLOSED_REQUIREMENT_CANNOT_SATISFY',
  RETENTION_ASSIGNMENT_CLIENT_FORBIDDEN: 'RETENTION_ASSIGNMENT_CLIENT_FORBIDDEN',
  CASE_REFERENCE_FIELDS_CLIENT_FORBIDDEN: 'CASE_REFERENCE_FIELDS_CLIENT_FORBIDDEN',
  NON_ACCEPTED_EVIDENCE_IN_DECISION_PACKET: 'NON_ACCEPTED_EVIDENCE_IN_DECISION_PACKET',
  ARCHIVAL_TRANSFER_CANNOT_DESTROY: 'ARCHIVAL_TRANSFER_CANNOT_DESTROY',
  INTEGRITY_MISMATCH_SAFE_HALT: 'INTEGRITY_MISMATCH_SAFE_HALT',
  EVIDENCE_ACCEPTANCE_NOT_APPROVAL: 'EVIDENCE_ACCEPTANCE_NOT_APPROVAL',
} as const;

export const AUTOMATED_DISPOSITION_OUTCOMES = ['ELIGIBLE_FOR_REVIEW'] as const;

export const FORBIDDEN_AUTOMATED_DISPOSITION_OUTCOMES = ['DESTROY_NOW'] as const;

export const LEGAL_HOLD_RELEASE_AUTHORITY_PERMISSION = 'records.legal_hold.release';

export const DISPOSITION_APPROVAL_PERMISSION = 'records.disposition.authorize';

export const ORDINARY_RECORDS_ADMIN_ROLE = 'records.administrator';

export const PHASE_7G_MODEL_NAMES = [
  'RecordsClassification',
  'RetentionSchedule',
  'RetentionRule',
  'RecordRetentionAssignment',
  'LegalHold',
  'LegalHoldTarget',
  'LegalHoldReleaseRecord',
  'PreservationCollection',
  'PreservationCollectionItem',
  'ExternalRecordsRepository',
  'ArchivalTransfer',
  'ArchivalTransferItem',
  'RecordDispositionRequest',
  'RecordDispositionRecord',
] as const;

export interface DispositionEligibilityEvaluation {
  eligibilityStatus: 'ELIGIBLE_FOR_REVIEW' | 'NOT_ELIGIBLE' | 'BLOCKED';
  safeHaltReasons: string[];
  notes: string[];
}
