import { EligibilityGuidanceOutcome } from '@prisma/client';

export const NON_PRODUCTION_SERVICE_CATALOG_FIXTURE_MARKER =
  'NON_PRODUCTION_SERVICE_CATALOG_TEST_ONLY';

export const IMMUTABLE_PUBLISHED_MATURITY_STATUSES = [
  'RECOGNIZED',
  'APPROVED',
  'CONFIGURED',
  'TESTED',
  'ACCEPTED',
  'ACTIVE',
  'SUSPENDED',
  'SUPERSEDED',
  'RETIRED',
] as const;
