export const NON_PRODUCTION_SERVICE_CATALOG_FIXTURE_MARKER = 'PHASE_5E_TEST_FIXTURE';

export const SERVICE_OPERATING_METADATA_INVARIANT_CODES = {
  FEE_REQUIRES_GOVERNING_SOURCE: 'FEE_REQUIRES_GOVERNING_SOURCE',
  EXPIRED_FEE_NOT_CURRENT: 'EXPIRED_FEE_NOT_CURRENT',
  WAIVER_AVAILABILITY_NOT_WAIVER: 'WAIVER_AVAILABILITY_NOT_WAIVER',
  SLA_EXPIRY_NOT_APPROVAL: 'SLA_EXPIRY_NOT_APPROVAL',
  DEPENDENCY_METADATA_NOT_AUTHORITY: 'DEPENDENCY_METADATA_NOT_AUTHORITY',
  OUTPUT_DEFINITION_NOT_ISSUANCE: 'OUTPUT_DEFINITION_NOT_ISSUANCE',
  REDRESS_ROUTE_NOT_DECISION: 'REDRESS_ROUTE_NOT_DECISION',
} as const;
