export const AUTHORITY_ENGINE_VERSION = '4.0.0';
export const AUTHORITY_RULESET_VERSION = '4.0.0-g';

export const AUTHORITY_CACHE_TTL_SECONDS = 60;

export const AUTHORITY_SECRET_FIELD_NAMES = [
  'secret',
  'secretHash',
  'password',
  'token',
  'tokenHash',
  'apiKey',
  'apiKeyHash',
  'privateKey',
  'credential',
] as const;

export enum AuthorityReasonCode {
  FUNCTION_NOT_FOUND = 'FUNCTION_NOT_FOUND',
  FUNCTION_SUSPENDED = 'FUNCTION_SUSPENDED',
  FUNCTION_NOT_ACTIVE = 'FUNCTION_NOT_ACTIVE',
  ASSIGNMENT_NOT_FOUND = 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_REQUIRES_REVALIDATION = 'ASSIGNMENT_REQUIRES_REVALIDATION',
  APPOINTMENT_MISSING = 'APPOINTMENT_MISSING',
  APPOINTMENT_EXPIRED = 'APPOINTMENT_EXPIRED',
  APPOINTMENT_REVOKED = 'APPOINTMENT_REVOKED',
  APPOINTMENT_NOT_CURRENT = 'APPOINTMENT_NOT_CURRENT',
  DELEGATION_MISSING = 'DELEGATION_MISSING',
  DELEGATION_EXPIRED = 'DELEGATION_EXPIRED',
  DELEGATION_REVOKED = 'DELEGATION_REVOKED',
  DELEGATION_EXCEEDED = 'DELEGATION_EXCEEDED',
  DELEGATION_NOT_CURRENT = 'DELEGATION_NOT_CURRENT',
  SOURCE_NOT_AUTHENTICATED = 'SOURCE_NOT_AUTHENTICATED',
  SOURCE_CONFLICT = 'SOURCE_CONFLICT',
  SOURCE_REVOKED = 'SOURCE_REVOKED',
  SOURCE_AMENDMENT_NOT_IMPLEMENTED = 'SOURCE_AMENDMENT_NOT_IMPLEMENTED',
  NATIONAL_AUTHORITY_SUBSTITUTION = 'NATIONAL_AUTHORITY_SUBSTITUTION',
  MANDATORY_DEPENDENCY_MISSING = 'MANDATORY_DEPENDENCY_MISSING',
  RECORD_PRESERVATION_FAILED = 'RECORD_PRESERVATION_FAILED',
  UNAUTHORIZED_OFFICIAL_ACT = 'UNAUTHORIZED_OFFICIAL_ACT',
  ALL_CONDITIONS_SATISFIED = 'ALL_CONDITIONS_SATISFIED',
  OFFICEHOLDER_NOT_LINKED = 'OFFICEHOLDER_NOT_LINKED',
}

export enum AuthorityExplanationKind {
  FACT = 'FACT',
  SOURCE = 'SOURCE',
  CONDITION = 'CONDITION',
  UNRESOLVED_ITEM = 'UNRESOLVED_ITEM',
  FAILURE = 'FAILURE',
  DEPENDENCY = 'DEPENDENCY',
  RESULT = 'RESULT',
}

export enum AuthorityReplayMode {
  HISTORICAL_REPLAY = 'HISTORICAL_REPLAY',
  CURRENT_REEVALUATION = 'CURRENT_REEVALUATION',
}
