export const CUSTOMS_REASON_CODES = {
  DECLARATION_NOT_RELEASE: 'CUSTOMS_DECLARATION_DOES_NOT_RELEASE_CARGO',
  PAYMENT_NOT_RELEASE: 'CUSTOMS_PAYMENT_DOES_NOT_RELEASE_CARGO',
  REPRESENTATIVE_AUTHORITY_REQUIRED: 'CUSTOMS_REPRESENTATIVE_AUTHORITY_REQUIRED',
  CLIENT_ASSESSMENT_FORBIDDEN: 'CUSTOMS_CLIENT_ASSESSMENT_FORBIDDEN',
  VALUATION_KIND_MISMATCH: 'CUSTOMS_VALUATION_KINDS_MUST_REMAIN_DISTINCT',
  RISK_NOT_VIOLATION: 'CUSTOMS_RISK_SCORE_IS_NOT_VIOLATION',
  AI_CANNOT_RELEASE: 'CUSTOMS_AI_CANNOT_AUTHORIZE_RELEASE',
  MANDATORY_PERMIT_BLOCKS: 'CUSTOMS_MANDATORY_PERMIT_BLOCKS_RELEASE',
  HOLD_GOVERNED_REMOVAL: 'CUSTOMS_HOLD_REQUIRES_GOVERNED_REMOVAL',
  TECHNICAL_ADMIN_CANNOT_RELEASE: 'CUSTOMS_TECHNICAL_ADMIN_CANNOT_RELEASE',
  CROSS_COMPANY_DENIED: 'CUSTOMS_CROSS_COMPANY_ACCESS_DENIED',
} as const;

export const FORBIDDEN_AI_CUSTOMS_ACTIONS = [
  'AUTHORIZE_RELEASE',
  'ISSUE_ASSESSMENT',
  'REMOVE_HOLD',
  'CLASSIFY_AUTHORITATIVELY',
] as const;

export const PLATFORM_ADMIN_CUSTOMS_ROLE_MARKER = 'PLATFORM_ADMIN';

export const BROKER_REPRESENTATION_KINDS = [
  'CUSTOMS_BROKER',
  'CUSTOMS_AGENT',
  'FREIGHT_FORWARDER',
  'AUTHORIZED_COMPANY_REPRESENTATIVE',
] as const;
