export const PHASE_13B_MODEL_NAMES = [
  'SecurityAsset',
  'SecurityControlDefinition',
  'SecurityControlImplementation',
  'SecurityControlAssessment',
  'SecurityFinding',
  'SecurityException',
  'VulnerabilityFinding',
  'VulnerabilityRemediation',
  'SecurityAssuranceReview',
  'CryptographicAsset',
  'CryptographicKeyReference',
  'CertificateReference',
  'TrustAnchorReference',
  'CryptographicPolicy',
  'CryptographicAgilityAssessment',
  'PostQuantumMigrationItem',
  'SoftwareComponentRecord',
  'SoftwareBillOfMaterialsRecord',
  'DependencyVulnerabilityRecord',
  'BuildProvenanceRecord',
  'ReleaseArtifactAttestation',
  'VendorSecurityAssessment',
  'PrivilegedAccessReview',
  'ServiceIdentityReview',
  'CredentialRotationRecord',
] as const;

export const PHASE_13B_SUPPORTING_MODEL_NAMES = [
  'BreakGlassAccessEvent',
  'SecurityTestExecution',
] as const;

export const PHASE_13B_ENUM_NAMES = [
  'SecurityControlDomain',
  'SecurityFindingSeverity',
  'SecurityControlImplementationStatus',
  'SecurityControlAssessmentResult',
  'SecurityExceptionStatus',
  'VulnerabilityFindingStatus',
  'VulnerabilityRemediationStatus',
  'SecurityAssuranceReviewStatus',
  'CryptographicMigrationStatus',
  'PostQuantumMigrationStatus',
  'SoftwareComponentType',
  'BuildProvenanceStatus',
  'ReleaseAttestationStatus',
  'VendorSecurityAssessmentStatus',
  'PrivilegedAccessReviewStatus',
  'ServiceIdentityReviewStatus',
  'CredentialRotationStatus',
  'BreakGlassAccessStatus',
  'SecurityEnvironment',
  'SecurityTestCategory',
  'ProductionReadinessGateStatus',
] as const;
