export const SECURITY_ASSET_CODE_PREFIX = 'SAST';
export const SECURITY_CONTROL_CODE_PREFIX = 'SCTL';
export const SECURITY_IMPLEMENTATION_CODE_PREFIX = 'SIMP';
export const SECURITY_ASSESSMENT_NUMBER_PREFIX = 'SASS';
export const SECURITY_FINDING_NUMBER_PREFIX = 'SFND';
export const SECURITY_EXCEPTION_NUMBER_PREFIX = 'SEXC';
export const VULNERABILITY_FINDING_NUMBER_PREFIX = 'VFND';
export const VULNERABILITY_REMEDIATION_NUMBER_PREFIX = 'VREM';
export const SECURITY_ASSURANCE_REVIEW_NUMBER_PREFIX = 'SARV';
export const CRYPTOGRAPHIC_ASSET_CODE_PREFIX = 'CRAS';
export const CRYPTOGRAPHIC_POLICY_CODE_PREFIX = 'CRPL';
export const CRYPTOGRAPHIC_AGILITY_ASSESSMENT_NUMBER_PREFIX = 'CRAA';
export const POST_QUANTUM_ITEM_CODE_PREFIX = 'PQMI';
export const SOFTWARE_COMPONENT_CODE_PREFIX = 'SWCM';
export const SBOM_CODE_PREFIX = 'SBOM';
export const DEPENDENCY_VULNERABILITY_NUMBER_PREFIX = 'DVUL';
export const BUILD_PROVENANCE_CODE_PREFIX = 'BPRV';
export const RELEASE_ATTESTATION_NUMBER_PREFIX = 'RATT';
export const VENDOR_ASSESSMENT_NUMBER_PREFIX = 'VSEC';
export const PRIVILEGED_ACCESS_REVIEW_NUMBER_PREFIX = 'PARV';
export const BREAK_GLASS_EVENT_NUMBER_PREFIX = 'BGEV';
export const SERVICE_IDENTITY_REVIEW_NUMBER_PREFIX = 'SIRV';
export const CREDENTIAL_ROTATION_NUMBER_PREFIX = 'CROT';
export const SECURITY_TEST_EXECUTION_NUMBER_PREFIX = 'STEX';

export const SECURITY_CONTROL_DOMAINS = [
  'IDENTITY',
  'AUTHENTICATION',
  'AUTHORIZATION',
  'PRIVILEGED_ACCESS',
  'SEGREGATION_OF_DUTIES',
  'NETWORK',
  'APPLICATION',
  'DATABASE',
  'API',
  'INTEGRATION',
  'HOST',
  'CONTAINER',
  'BUILD_PIPELINE',
  'SECRETS',
  'CRYPTOGRAPHY',
  'LOGGING',
  'MONITORING',
  'DATA_PROTECTION',
  'BACKUP',
  'RECOVERY',
  'INCIDENT_RESPONSE',
  'VULNERABILITY',
  'SUPPLY_CHAIN',
  'VENDOR',
  'AI_SECURITY',
  'PHYSICAL_DEPENDENCY_REFERENCE',
] as const;

export const SECURITY_FINDING_SEVERITIES = [
  'INFORMATIONAL',
  'LOW',
  'MODERATE',
  'HIGH',
  'CRITICAL',
] as const;

export const POST_QUANTUM_MIGRATION_STATUSES = [
  'IDENTIFIED',
  'ASSESSED',
  'NOT_YET_MIGRATED',
  'PILOT',
  'VALIDATION',
  'MIGRATED',
  'REVALIDATION_REQUIRED',
  'DEFERRED_WITH_ACCEPTED_RISK',
] as const;

export const SECURITY_TEST_CATEGORIES = [
  'AUTHORIZATION_BYPASS',
  'IDOR',
  'MASS_ASSIGNMENT',
  'PRIVILEGE_ESCALATION',
  'BROKEN_AUTHENTICATION',
  'SESSION_FIXATION',
  'TOKEN_REPLAY',
  'CSRF',
  'SSRF',
  'INJECTION',
  'XSS',
  'TEMPLATE_INJECTION',
  'PATH_TRAVERSAL',
  'UNSAFE_DESERIALIZATION',
  'FILE_UPLOAD_ABUSE',
  'RATE_LIMITING',
  'RESOURCE_EXHAUSTION',
  'SECRETS_LEAKAGE',
  'PII_LEAKAGE',
  'WEBHOOK_SPOOFING',
  'SIGNATURE_REPLAY',
  'CROSS_TENANT_LEAKAGE',
  'AGENT_TOOL_PRIVILEGE_ESCALATION',
] as const;

export const AUTHORIZED_SECURITY_TEST_ENVIRONMENTS = ['DEVELOPMENT', 'TEST', 'STAGING'] as const;

export const FORBIDDEN_SECRET_PERSISTENCE_FIELDS = [
  'secret',
  'secretValue',
  'password',
  'apiKey',
  'privateKey',
  'token',
  'credential',
] as const;

export const FORBIDDEN_CLIENT_SECURITY_EXCEPTION_FIELDS = [
  'status',
  'approvedAt',
  'approverIdentityId',
  'isPermanent',
] as const;

export const FORBIDDEN_CLIENT_RELEASE_ATTESTATION_FIELDS = [
  'status',
  'approvedAt',
  'approverIdentityId',
  'isSigned',
] as const;

export const FORBIDDEN_CLIENT_CRYPTOGRAPHIC_ASSET_FIELDS = [
  'postQuantumValidated',
  'claimsPostQuantumSecurity',
  'historicalVerificationPreserved',
  'migrationStatus',
] as const;

export const FORBIDDEN_CLIENT_BREAK_GLASS_FIELDS = [
  'status',
  'createsInstitutionalAuthority',
  'postEventReviewCompleted',
  'enhancedLoggingReference',
] as const;

export const CONFLATION_PAIRS = [
  ['AUTHENTICATION', 'INSTITUTIONAL_AUTHORITY'],
  ['TECHNICAL_ADMIN', 'PUBLIC_DECISION_MAKER'],
  ['ENCRYPTION', 'AUTHORIZATION'],
  ['SECURITY_SCAN_PASSING', 'SECURITY_ACCREDITATION'],
  ['SECURITY_ACCREDITATION', 'OPERATIONAL_ACTIVATION'],
  ['PQC_CAPABILITY', 'COMPLETED_PQ_MIGRATION'],
] as const;

export const PHASE_13B_BOUNDARY_DISCLAIMERS = {
  AUTHENTICATION_NOT_AUTHORITY:
    'Authentication confirms identity only; it does not confer institutional authority.',
  TECHNICAL_ADMIN_NOT_DECISION_MAKER:
    'Technical administration does not create substantive governmental decision authority.',
  ENCRYPTION_NOT_AUTHORIZATION:
    'Encryption protects data; it does not substitute for authorization controls.',
  SCAN_NOT_ACCREDITATION: 'Passing a security scan is not equivalent to security accreditation.',
  ACCREDITATION_NOT_ACTIVATION:
    'Security accreditation does not automatically authorize operational activation.',
  PQC_CAPABILITY_NOT_MIGRATION:
    'Post-quantum cryptographic capability does not imply completed PQ migration.',
  SEVERITY_NOT_RISK_ACCEPTANCE:
    'Finding severity documents impact; severity alone does not accept risk.',
  BREAK_GLASS_NOT_AUTHORITY:
    'Emergency technical access does not create substantive governmental authority.',
  SERVICE_IDENTITY_NOT_OFFICEHOLDER:
    'Service identity credentials cannot impersonate officeholder institutional authority.',
} as const;

export const CYBERSECURITY_REASON_CODES = {
  SECRET_IN_SOURCE_CONTROL: 'SECRET_IN_SOURCE_CONTROL',
  SECRET_IN_DATABASE: 'SECRET_IN_DATABASE',
  SECRET_IN_LOGS: 'SECRET_IN_LOGS',
  SECRET_IN_ERROR_MESSAGE: 'SECRET_IN_ERROR_MESSAGE',
  SHARED_ADMIN_ACCOUNT: 'SHARED_ADMIN_ACCOUNT',
  BREAK_GLASS_EXPIRED: 'BREAK_GLASS_EXPIRED',
  BREAK_GLASS_NOT_LOGGED: 'BREAK_GLASS_NOT_LOGGED',
  UNSIGNED_RELEASE: 'UNSIGNED_RELEASE',
  UNVERIFIABLE_PROVENANCE: 'UNVERIFIABLE_PROVENANCE',
  CRITICAL_VULNERABILITY_UNDISPOSITIONED: 'CRITICAL_VULNERABILITY_UNDISPOSITIONED',
  EXCEPTION_EXPIRED: 'EXCEPTION_EXPIRED',
  PERMANENT_EXCEPTION_FORBIDDEN: 'PERMANENT_EXCEPTION_FORBIDDEN',
  PQC_OVERSTATED: 'PQC_OVERSTATED',
  HISTORICAL_VERIFICATION_LOST: 'HISTORICAL_VERIFICATION_LOST',
  UNCONTROLLED_DEPENDENCY_CHANGE: 'UNCONTROLLED_DEPENDENCY_CHANGE',
  PRODUCTION_TEST_FORBIDDEN: 'PRODUCTION_TEST_FORBIDDEN',
  SYSADMIN_CANNOT_APPROVE_APPLICATION: 'SYSADMIN_CANNOT_APPROVE_APPLICATION',
  DB_ADMIN_CANNOT_CREATE_AUTHORITY: 'DB_ADMIN_CANNOT_CREATE_AUTHORITY',
  SERVICE_TOKEN_OFFICEHOLDER_IMPERSONATION: 'SERVICE_TOKEN_OFFICEHOLDER_IMPERSONATION',
  CREDENTIAL_EXPIRED: 'CREDENTIAL_EXPIRED',
  CREDENTIAL_REVOKED: 'CREDENTIAL_REVOKED',
  SUSPENDED_AGENT_CREDENTIAL: 'SUSPENDED_AGENT_CREDENTIAL',
  CERTIFICATE_EXPIRED: 'CERTIFICATE_EXPIRED',
  CONFLATION_FORBIDDEN: 'CONFLATION_FORBIDDEN',
} as const;

export const CRITICAL_VULNERABILITY_PRODUCTION_BLOCK_MESSAGE =
  'Known critical vulnerability prevents production readiness unless formally dispositioned';

export const NPM_AUDIT_CRITICAL_THRESHOLD = 'critical';
export const NPM_AUDIT_HIGH_THRESHOLD = 'high';
