export const PHASE_12F_BOUNDARY_DISCLAIMER =
  'Digital Twin != Real Object. Simulation != Live Operation. Modeled Condition != Observed Condition. Scenario != Prediction. Twin Output != Decision. APPROVED_LIVE_REFERENCE is not operational control authority.';

export const DIGITAL_TWIN_TYPES = [
  'INSTITUTION',
  'DEPARTMENT',
  'SERVICE',
  'APPLICATION',
  'CASE',
  'PROJECT',
  'INFRASTRUCTURE',
  'DEPENDENCY',
  'AUTHORITY',
  'WORKFLOW',
  'OTHER_APPROVED',
] as const;

export const DIGITAL_TWIN_MODES = [
  'DESIGN',
  'TRAINING',
  'SIMULATION',
  'TEST',
  'SHADOW',
  'ADVISORY',
  'CONTROLLED_PILOT',
  'APPROVED_LIVE_REFERENCE',
] as const;

export const DIGITAL_TWIN_SOURCE_STATUSES = [
  'AUTHORITATIVE',
  'SUPPORTING',
  'MODELED',
  'UNVERIFIED',
] as const;

export const CONSEQUENTIAL_USE_IMPACT_AREAS = [
  'PERSON',
  'PROJECT',
  'INSTITUTION',
  'PUBLIC_SERVICE',
  'FINANCIAL_INTEREST',
  'INFRASTRUCTURE',
  'LEGAL_POSITION',
  'GOVERNMENT_DECISION',
] as const;

export const FORBIDDEN_SIMULATION_LIVE_MUTATIONS = [
  'GovernmentDecision',
  'Case',
  'OfficialInstrument',
  'CaseEvent',
  'CaseCommunication',
  'ContinuingObligation',
  'ComplianceMatter',
  'RedressDecision',
  'RedressNotice',
] as const;

export const FORBIDDEN_SIMULATION_LIVE_ACTIONS = [
  'ISSUE_LICENSE',
  'CHANGE_PROJECT_STAGE',
  'SEND_PUBLIC_EVENT_NOTICE',
  'MUTATE_CASE_STATUS',
  'FINALIZE_GOVERNMENT_DECISION',
  'ISSUE_OFFICIAL_INSTRUMENT',
  'CREATE_REAL_WORLD_OBLIGATION',
  'CONTROL_LIVE_INFRASTRUCTURE',
] as const;

export const FORBIDDEN_AI_TWIN_FINAL_ACTIONS = [
  'FINAL_DECIDE',
  'APPROVE_CONSEQUENTIAL_USE',
  'AUTHORIZE_LIVE_TRANSITION',
  'DECLARE_AUTHORITATIVE',
] as const;

export const FORBIDDEN_CLIENT_TWIN_FIELDS = [
  'isAuthoritativeRecord',
  'isStale',
  'isIncomplete',
  'isInconsistent',
  'isCompromised',
  'outsideApprovedUse',
  'liveActivationAuthorized',
  'isOperationalControl',
  'presentedAsPrediction',
  'isPrediction',
] as const;

export const AI_ACTOR_ROLE_MARKER = 'AI_ASSISTANCE';

export const INTELLIGENCE_REASON_CODES = {
  TWIN_NOT_AUTHORITATIVE: 'TWIN_NOT_AUTHORITATIVE_RECORD',
  SIMULATION_CANNOT_MUTATE_LIVE: 'SIMULATION_CANNOT_MUTATE_LIVE_RECORD',
  SCENARIO_NOT_PREDICTION: 'SCENARIO_CANNOT_BE_PRESENTED_AS_PREDICTION',
  MODELED_NOT_OBSERVED: 'MODELED_DEPENDENCY_IS_NOT_OBSERVED_FACT',
  STALE_TWIN_BLOCKS_USE: 'STALE_TWIN_BLOCKS_CONSEQUENTIAL_USE',
  INCOMPLETE_TWIN_BLOCKS_USE: 'INCOMPLETE_TWIN_BLOCKS_CONSEQUENTIAL_USE',
  MISSING_SOURCE_UNDISCLOSED: 'MISSING_SOURCE_MUST_BE_DISCLOSED',
  AI_CANNOT_FINAL_DECIDE: 'AI_CANNOT_FINAL_DECIDE_CONSEQUENTIAL_USE',
  LIVE_TRANSITION_REQUIRES_ACCEPTANCE: 'LIVE_TRANSITION_REQUIRES_SEPARATE_ACCEPTANCE',
  TWIN_CANNOT_OWN_ITSELF: 'TWIN_OWNER_CANNOT_BE_TWIN_ITSELF',
  CASE_TWIN_PROFILE_EXPANSION: 'CASE_TWIN_CANNOT_BECOME_UNCONTROLLED_PERSONAL_PROFILE',
  SNAPSHOT_IMMUTABLE: 'SNAPSHOT_IS_IMMUTABLE',
  ROLLBACK_REQUIRED: 'ROLLBACK_PATH_REQUIRED_FOR_LIVE_TRANSITION',
  OPERATIONAL_CONTROL_FORBIDDEN: 'PHASE_12_DOES_NOT_DIRECTLY_CONTROL_INFRASTRUCTURE',
  CONSEQUENTIAL_REVIEW_REQUIRED: 'CONSEQUENTIAL_USE_REVIEW_REQUIRED',
  TECHNICAL_SUCCESS_NOT_ACTIVATION: 'TECHNICAL_SUCCESS_DOES_NOT_EQUAL_LIVE_ACTIVATION',
} as const;
