export const INTELLIGENCE_BOUNDARY_DISCLAIMER =
  'The intelligence layer provides analytics, dashboards, AI assistance, monitoring, and simulation. ' +
  'Technical projections, recommendations, and alerts do not constitute legal authority, official decisions, or verified violations.';

export const PHASE_12A_BOUNDARY_DISCLAIMER =
  'Phase 12A records performance frameworks, metrics, and claims. Metric observations do not constitute institutional performance verdicts or government decisions.';

export const PHASE_12B_BOUNDARY_DISCLAIMER =
  'Phase 12B records dashboards and indicator projections. Dashboard views do not create authority, delegation, or case disposition.';

export const PHASE_12C_BOUNDARY_DISCLAIMER =
  'Phase 12C records strategic project profiles and sponsor-reported milestones. Sponsor reports do not equal verified milestone completion.';

export const PHASE_12D_BOUNDARY_DISCLAIMER =
  'Phase 12D records AI models, agents, and execution. AI assistance is recommendatory only and cannot approve, refuse, waive, sign, issue, or decide.';

export const PHASE_12E_BOUNDARY_DISCLAIMER =
  'Phase 12E records analysis, monitoring, and risk assessments. Alerts are not violations; correlation is not causation; risk levels are not sanctions.';

export const PHASE_12F_BOUNDARY_DISCLAIMER =
  'Phase 12F records digital twins and simulations. Twins are not real objects; simulation outputs cannot update live case state.';

export const PHASE_12G_BOUNDARY_DISCLAIMER =
  'Phase 12G records reports and decision traceability. Report claims require review; historical replay does not substitute live decisions.';

export const FORBIDDEN_AI_ACTIONS = [
  'APPROVE',
  'REFUSE',
  'WAIVE',
  'SIGN',
  'ISSUE',
  'DECIDE',
  'FINALIZE_DECISION',
  'EXECUTE_ENFORCEMENT',
  'APPOINT_OFFICEHOLDER',
  'SUSPEND_AUTHORITY',
  'REVOKE_INSTRUMENT',
  'GRANT_DELEGATION',
  'DECLARE_VIOLATION',
  'DECLARE_COMPLIANCE',
] as const;

export const FORBIDDEN_ANALYTICS_PATCH_TARGETS = [
  'GovernmentDecision',
  'OfficialInstrument',
  'governmentDecision',
  'officialInstrument',
  'decisionStatus',
  'instrumentStatus',
  'approved',
  'refused',
  'issued',
  'signed',
] as const;

export const FORBIDDEN_CLIENT_DASHBOARD_FIELDS = [
  'authorityGranted',
  'delegationId',
  'governmentDecisionId',
  'approved',
  'refused',
  'issued',
] as const;

export const FORBIDDEN_CLIENT_METRIC_FIELDS = [
  'observedValue',
  'computedValue',
  'status',
  'verifiedAt',
] as const;

export const FORBIDDEN_CLIENT_PERFORMANCE_CLAIM_FIELDS = [
  'status',
  'verifiedAt',
  'claimedAt',
] as const;

export const FORBIDDEN_CLIENT_AI_EXECUTION_FIELDS = [
  'status',
  'isRecommendatoryOnly',
  'approved',
  'refused',
  'decided',
  'issued',
  'signed',
] as const;

export const PROMPT_INJECTION_PATTERNS: readonly RegExp[] = [
  /ignore\s+(all\s+)?(previous|prior)\s+instructions/i,
  /system\s*:\s*/i,
  /you\s+are\s+now/i,
  /<\s*script\b/i,
  /javascript:/i,
  /\{\{\{/,
  /\}\}\}/,
];

export const STALE_TWIN_MAX_AGE_MS = 24 * 60 * 60 * 1000;

export const METRIC_CALCULATION_REFERENCE_PREFIX = 'MCR';
export const PERFORMANCE_CLAIM_REFERENCE_PREFIX = 'PCL';
export const AI_EXECUTION_REFERENCE_PREFIX = 'AIE';
export const ANALYSIS_REQUEST_REFERENCE_PREFIX = 'ARQ';
export const ANALYSIS_RUN_REFERENCE_PREFIX = 'ARN';
export const MONITORING_ALERT_REFERENCE_PREFIX = 'MAL';
export const RISK_ASSESSMENT_REFERENCE_PREFIX = 'RSA';
export const SIMULATION_RUN_REFERENCE_PREFIX = 'SIM';
export const REPORT_GENERATION_REFERENCE_PREFIX = 'RGR';
export const DECISION_TRACE_REFERENCE_PREFIX = 'EDT';

export const MUST_FAIL_INVARIANTS = [
  'DASHBOARD_CANNOT_CREATE_AUTHORITY',
  'DASHBOARD_CANNOT_GRANT_DELEGATION',
  'DASHBOARD_VIEW_NOT_AUTHORITY',
  'INDICATOR_NOT_DECISION',
  'EXECUTIVE_DASHBOARD_NOT_COMMAND',
  'DEPARTMENTAL_CONSOLE_NOT_DISPOSITION',
  'DASHBOARD_SNAPSHOT_NOT_OFFICIAL_RECORD',
  'DASHBOARD_WIDGET_NOT_INSTRUMENT',
  'DASHBOARD_PROJECTION_NOT_VERIFIED_OUTCOME',
  'STALE_INDICATOR_BLOCK_CONSEQUENTIAL_USE',
  'AI_CANNOT_APPROVE',
  'AI_CANNOT_REFUSE',
  'AI_CANNOT_WAIVE',
  'AI_CANNOT_SIGN',
  'AI_CANNOT_ISSUE',
  'AI_CANNOT_DECIDE',
  'AI_RECOMMENDATION_NOT_DECISION',
  'AI_EXECUTION_NOT_BINDING',
  'AI_CANNOT_FINALIZE_GOVERNMENT_ACTION',
  'AI_CANNOT_EXECUTE_ENFORCEMENT',
  'AI_CANNOT_APPOINT_OFFICEHOLDER',
  'AI_CANNOT_SUSPEND_AUTHORITY',
  'AI_CANNOT_REVOKE_INSTRUMENT',
  'AI_ASSISTANCE_NOT_OFFICIAL_ACTOR',
  'AI_OUTPUT_REQUIRES_HUMAN_DISPOSITION',
  'ALERT_NOT_VIOLATION',
  'ALERT_CANNOT_SELF_VERIFY',
  'OPEN_ALERT_NOT_CONFIRMED_BREACH',
  'MONITORING_OBSERVATION_NOT_VIOLATION',
  'ALERT_VERIFICATION_REQUIRED_FOR_VIOLATION',
  'CORRELATION_NOT_CAUSATION',
  'FORECAST_NOT_ACHIEVEMENT',
  'PROJECTION_NOT_GUARANTEE',
  'TREND_NOT_POLICY_DIRECTIVE',
  'ANALYSIS_OPTION_NOT_DECISION',
  'ANALYSIS_FINDING_NOT_FINAL_DETERMINATION',
  'RISK_ASSESSMENT_NOT_SANCTION',
  'SPONSOR_REPORT_NOT_VERIFIED_MILESTONE',
  'REPORTED_MILESTONE_NOT_COMPLETED',
  'PROJECT_STATUS_PROJECTION_NOT_VERDICT',
  'CAPITAL_EVIDENCE_NOT_AUDITED_FACT',
  'EMPLOYMENT_EVIDENCE_NOT_VERIFIED_COUNT',
  'INFRASTRUCTURE_REPORT_NOT_DELIVERY_CERTIFICATE',
  'STRATEGIC_PROJECT_NOT_AUTHORITY_PROGRAM',
  'TWIN_NOT_REAL_OBJECT',
  'SIMULATION_CANNOT_UPDATE_LIVE_CASE',
  'SIMULATION_OUTPUT_NOT_LIVE_STATE',
  'STALE_TWIN_SAFE_HALT',
  'CONSEQUENTIAL_TWIN_USE_REQUIRES_REVIEW',
  'SIMULATION_TO_LIVE_REQUIRES_APPROVED_REVIEW',
  'PROMPT_INJECTION_TREATED_AS_DATA',
  'CROSS_CASE_RETRIEVAL_BLOCKED',
  'SUSPENDED_MODEL_BLOCKED',
  'SUSPENDED_USE_CASE_BLOCKED',
  'SUSPENDED_AGENT_BLOCKED',
  'ANALYTICS_CANNOT_PATCH_GOVERNMENT_DECISION',
  'ANALYTICS_CANNOT_PATCH_OFFICIAL_INSTRUMENT',
  'METRIC_OBSERVATION_NOT_PERFORMANCE_VERDICT',
  'PERFORMANCE_CLAIM_NOT_DECISION',
  'UNVERIFIED_CLAIM_NOT_PUBLISHED_FACT',
  'DEGRADED_DATA_QUALITY_BLOCKS_CLAIM',
  'STALE_METRIC_BLOCKS_CONSEQUENTIAL_USE',
  'BASELINE_NOT_CURRENT_TARGET',
  'CALCULATION_RUN_FAILURE_SAFE_HALT',
  'DATA_QUALITY_NOT_ASSESSMENT_OF_LEGALITY',
  'REPORT_CLAIM_NOT_VERIFIED_WITHOUT_REVIEW',
  'REPORT_PUBLICATION_NOT_DECISION_NOTICE',
  'REPORT_APPROVAL_NOT_AUTHORITY_ACT',
  'HISTORICAL_REPLAY_NOT_LIVE_DECISION',
  'DECISION_TRACE_NOT_SUBSTITUTES_DECISION',
  'ACCESS_NOT_AUTHORITY',
  'VIEWING_ANALYTICS_NOT_DELEGATION',
  'RECOMMENDATION_NOT_WAIVER',
  'SCENARIO_COMPARISON_NOT_MANDATE',
  'SENSITIVITY_ANALYSIS_NOT_APPROVAL',
  'AI_TOOL_ENTITLEMENT_NOT_AUTHORITY',
  'AI_DATA_ENTITLEMENT_NOT_DISCLOSURE_RIGHT',
  'HUMAN_DISPOSITION_REQUIRED_FOR_CONSEQUENTIAL_AI',
  'AI_INCIDENT_TRIGGERS_SUSPENSION_REVIEW',
  'EVALUATION_SCORE_NOT_APPROVAL',
  'MONITORING_RULE_NOT_ENFORCEMENT_AUTHORITY',
  'RISK_LEVEL_NOT_SANCTION_LEVEL',
  'ANALYSIS_REQUEST_NOT_DECISION_REQUEST',
  'COMPLETED_ANALYSIS_NOT_FINAL_ORDER',
  'SAFE_HALT_BLOCKS_CONSEQUENTIAL_PATH',
  'UNRESOLVED_ENTITLEMENT_BLOCKS_EXECUTION',
  'CASE_SCOPED_EXECUTION_ONLY',
  'INSTITUTION_BOUNDARY_ON_RETRIEVAL',
  'DETERMINISTIC_ADAPTER_NOT_DECISION_ENGINE',
  'PROMPT_GOVERNANCE_NOT_POLICY_AUTHORITY',
  'FORECAST_STALENESS_REQUIRES_DISCLAIMER',
  'INDICATOR_STALENESS_SAFE_HALT',
  'REPORT_GENERATION_SAFE_HALT',
  'SIMULATION_RUN_SAFE_HALT',
  'ANALYSIS_RUN_SAFE_HALT',
  'PERFORMANCE_CLAIM_CLIENT_STATUS_FORBIDDEN',
  'DASHBOARD_CLIENT_AUTHORITY_FIELDS_FORBIDDEN',
  'METRIC_CLIENT_COMPUTED_VALUE_FORBIDDEN',
  'AI_EXECUTION_CLIENT_DECISION_FIELDS_FORBIDDEN',
  'INTELLIGENCE_LAYER_BOUNDARY_NON_WAIVABLE',
] as const;

export type IntelligenceInvariantCode = (typeof MUST_FAIL_INVARIANTS)[number];

export const AI_ACTION_REASON_MAP: Partial<
  Record<(typeof FORBIDDEN_AI_ACTIONS)[number], IntelligenceInvariantCode>
> = {
  APPROVE: 'AI_CANNOT_APPROVE',
  REFUSE: 'AI_CANNOT_REFUSE',
  WAIVE: 'AI_CANNOT_WAIVE',
  SIGN: 'AI_CANNOT_SIGN',
  ISSUE: 'AI_CANNOT_ISSUE',
  DECIDE: 'AI_CANNOT_DECIDE',
  FINALIZE_DECISION: 'AI_CANNOT_FINALIZE_GOVERNMENT_ACTION',
  EXECUTE_ENFORCEMENT: 'AI_CANNOT_EXECUTE_ENFORCEMENT',
  APPOINT_OFFICEHOLDER: 'AI_CANNOT_APPOINT_OFFICEHOLDER',
  SUSPEND_AUTHORITY: 'AI_CANNOT_SUSPEND_AUTHORITY',
  REVOKE_INSTRUMENT: 'AI_CANNOT_REVOKE_INSTRUMENT',
  GRANT_DELEGATION: 'DASHBOARD_CANNOT_GRANT_DELEGATION',
  DECLARE_VIOLATION: 'ALERT_NOT_VIOLATION',
  DECLARE_COMPLIANCE: 'PERFORMANCE_CLAIM_NOT_DECISION',
};

export const INTELLIGENCE_REASON_CODES = {
  DASHBOARD_CANNOT_CREATE_AUTHORITY: 'DASHBOARD_CANNOT_CREATE_AUTHORITY',
  DASHBOARD_CANNOT_GRANT_DELEGATION: 'DASHBOARD_CANNOT_GRANT_DELEGATION',
  DASHBOARD_VIEW_NOT_AUTHORITY: 'DASHBOARD_VIEW_NOT_AUTHORITY',
  INDICATOR_NOT_DECISION: 'INDICATOR_NOT_DECISION',
  EXECUTIVE_DASHBOARD_NOT_COMMAND: 'EXECUTIVE_DASHBOARD_NOT_COMMAND',
  DEPARTMENTAL_CONSOLE_NOT_DISPOSITION: 'DEPARTMENTAL_CONSOLE_NOT_DISPOSITION',
  DASHBOARD_SNAPSHOT_NOT_OFFICIAL_RECORD: 'DASHBOARD_SNAPSHOT_NOT_OFFICIAL_RECORD',
  DASHBOARD_WIDGET_NOT_INSTRUMENT: 'DASHBOARD_WIDGET_NOT_INSTRUMENT',
  DASHBOARD_PROJECTION_NOT_VERIFIED_OUTCOME: 'DASHBOARD_PROJECTION_NOT_VERIFIED_OUTCOME',
  STALE_INDICATOR_BLOCK_CONSEQUENTIAL_USE: 'STALE_INDICATOR_BLOCK_CONSEQUENTIAL_USE',
  AI_CANNOT_APPROVE: 'AI_CANNOT_APPROVE',
  AI_CANNOT_REFUSE: 'AI_CANNOT_REFUSE',
  AI_CANNOT_WAIVE: 'AI_CANNOT_WAIVE',
  AI_CANNOT_SIGN: 'AI_CANNOT_SIGN',
  AI_CANNOT_ISSUE: 'AI_CANNOT_ISSUE',
  AI_CANNOT_DECIDE: 'AI_CANNOT_DECIDE',
  AI_RECOMMENDATION_NOT_DECISION: 'AI_RECOMMENDATION_NOT_DECISION',
  AI_EXECUTION_NOT_BINDING: 'AI_EXECUTION_NOT_BINDING',
  AI_CANNOT_FINALIZE_GOVERNMENT_ACTION: 'AI_CANNOT_FINALIZE_GOVERNMENT_ACTION',
  AI_CANNOT_EXECUTE_ENFORCEMENT: 'AI_CANNOT_EXECUTE_ENFORCEMENT',
  AI_CANNOT_APPOINT_OFFICEHOLDER: 'AI_CANNOT_APPOINT_OFFICEHOLDER',
  AI_CANNOT_SUSPEND_AUTHORITY: 'AI_CANNOT_SUSPEND_AUTHORITY',
  AI_CANNOT_REVOKE_INSTRUMENT: 'AI_CANNOT_REVOKE_INSTRUMENT',
  AI_ASSISTANCE_NOT_OFFICIAL_ACTOR: 'AI_ASSISTANCE_NOT_OFFICIAL_ACTOR',
  AI_OUTPUT_REQUIRES_HUMAN_DISPOSITION: 'AI_OUTPUT_REQUIRES_HUMAN_DISPOSITION',
  ALERT_NOT_VIOLATION: 'ALERT_NOT_VIOLATION',
  ALERT_CANNOT_SELF_VERIFY: 'ALERT_CANNOT_SELF_VERIFY',
  OPEN_ALERT_NOT_CONFIRMED_BREACH: 'OPEN_ALERT_NOT_CONFIRMED_BREACH',
  MONITORING_OBSERVATION_NOT_VIOLATION: 'MONITORING_OBSERVATION_NOT_VIOLATION',
  ALERT_VERIFICATION_REQUIRED_FOR_VIOLATION: 'ALERT_VERIFICATION_REQUIRED_FOR_VIOLATION',
  CORRELATION_NOT_CAUSATION: 'CORRELATION_NOT_CAUSATION',
  FORECAST_NOT_ACHIEVEMENT: 'FORECAST_NOT_ACHIEVEMENT',
  PROJECTION_NOT_GUARANTEE: 'PROJECTION_NOT_GUARANTEE',
  TREND_NOT_POLICY_DIRECTIVE: 'TREND_NOT_POLICY_DIRECTIVE',
  ANALYSIS_OPTION_NOT_DECISION: 'ANALYSIS_OPTION_NOT_DECISION',
  ANALYSIS_FINDING_NOT_FINAL_DETERMINATION: 'ANALYSIS_FINDING_NOT_FINAL_DETERMINATION',
  RISK_ASSESSMENT_NOT_SANCTION: 'RISK_ASSESSMENT_NOT_SANCTION',
  SPONSOR_REPORT_NOT_VERIFIED_MILESTONE: 'SPONSOR_REPORT_NOT_VERIFIED_MILESTONE',
  REPORTED_MILESTONE_NOT_COMPLETED: 'REPORTED_MILESTONE_NOT_COMPLETED',
  PROJECT_STATUS_PROJECTION_NOT_VERDICT: 'PROJECT_STATUS_PROJECTION_NOT_VERDICT',
  CAPITAL_EVIDENCE_NOT_AUDITED_FACT: 'CAPITAL_EVIDENCE_NOT_AUDITED_FACT',
  EMPLOYMENT_EVIDENCE_NOT_VERIFIED_COUNT: 'EMPLOYMENT_EVIDENCE_NOT_VERIFIED_COUNT',
  INFRASTRUCTURE_REPORT_NOT_DELIVERY_CERTIFICATE: 'INFRASTRUCTURE_REPORT_NOT_DELIVERY_CERTIFICATE',
  STRATEGIC_PROJECT_NOT_AUTHORITY_PROGRAM: 'STRATEGIC_PROJECT_NOT_AUTHORITY_PROGRAM',
  TWIN_NOT_REAL_OBJECT: 'TWIN_NOT_REAL_OBJECT',
  SIMULATION_CANNOT_UPDATE_LIVE_CASE: 'SIMULATION_CANNOT_UPDATE_LIVE_CASE',
  SIMULATION_OUTPUT_NOT_LIVE_STATE: 'SIMULATION_OUTPUT_NOT_LIVE_STATE',
  STALE_TWIN_SAFE_HALT: 'STALE_TWIN_SAFE_HALT',
  CONSEQUENTIAL_TWIN_USE_REQUIRES_REVIEW: 'CONSEQUENTIAL_TWIN_USE_REQUIRES_REVIEW',
  SIMULATION_TO_LIVE_REQUIRES_APPROVED_REVIEW: 'SIMULATION_TO_LIVE_REQUIRES_APPROVED_REVIEW',
  PROMPT_INJECTION_TREATED_AS_DATA: 'PROMPT_INJECTION_TREATED_AS_DATA',
  CROSS_CASE_RETRIEVAL_BLOCKED: 'CROSS_CASE_RETRIEVAL_BLOCKED',
  SUSPENDED_MODEL_BLOCKED: 'SUSPENDED_MODEL_BLOCKED',
  SUSPENDED_USE_CASE_BLOCKED: 'SUSPENDED_USE_CASE_BLOCKED',
  SUSPENDED_AGENT_BLOCKED: 'SUSPENDED_AGENT_BLOCKED',
  ANALYTICS_CANNOT_PATCH_GOVERNMENT_DECISION: 'ANALYTICS_CANNOT_PATCH_GOVERNMENT_DECISION',
  ANALYTICS_CANNOT_PATCH_OFFICIAL_INSTRUMENT: 'ANALYTICS_CANNOT_PATCH_OFFICIAL_INSTRUMENT',
  METRIC_OBSERVATION_NOT_PERFORMANCE_VERDICT: 'METRIC_OBSERVATION_NOT_PERFORMANCE_VERDICT',
  PERFORMANCE_CLAIM_NOT_DECISION: 'PERFORMANCE_CLAIM_NOT_DECISION',
  UNVERIFIED_CLAIM_NOT_PUBLISHED_FACT: 'UNVERIFIED_CLAIM_NOT_PUBLISHED_FACT',
  DEGRADED_DATA_QUALITY_BLOCKS_CLAIM: 'DEGRADED_DATA_QUALITY_BLOCKS_CLAIM',
  STALE_METRIC_BLOCKS_CONSEQUENTIAL_USE: 'STALE_METRIC_BLOCKS_CONSEQUENTIAL_USE',
  BASELINE_NOT_CURRENT_TARGET: 'BASELINE_NOT_CURRENT_TARGET',
  CALCULATION_RUN_FAILURE_SAFE_HALT: 'CALCULATION_RUN_FAILURE_SAFE_HALT',
  DATA_QUALITY_NOT_ASSESSMENT_OF_LEGALITY: 'DATA_QUALITY_NOT_ASSESSMENT_OF_LEGALITY',
  REPORT_CLAIM_NOT_VERIFIED_WITHOUT_REVIEW: 'REPORT_CLAIM_NOT_VERIFIED_WITHOUT_REVIEW',
  REPORT_PUBLICATION_NOT_DECISION_NOTICE: 'REPORT_PUBLICATION_NOT_DECISION_NOTICE',
  REPORT_APPROVAL_NOT_AUTHORITY_ACT: 'REPORT_APPROVAL_NOT_AUTHORITY_ACT',
  HISTORICAL_REPLAY_NOT_LIVE_DECISION: 'HISTORICAL_REPLAY_NOT_LIVE_DECISION',
  DECISION_TRACE_NOT_SUBSTITUTES_DECISION: 'DECISION_TRACE_NOT_SUBSTITUTES_DECISION',
  ACCESS_NOT_AUTHORITY: 'ACCESS_NOT_AUTHORITY',
  VIEWING_ANALYTICS_NOT_DELEGATION: 'VIEWING_ANALYTICS_NOT_DELEGATION',
  RECOMMENDATION_NOT_WAIVER: 'RECOMMENDATION_NOT_WAIVER',
  SCENARIO_COMPARISON_NOT_MANDATE: 'SCENARIO_COMPARISON_NOT_MANDATE',
  SENSITIVITY_ANALYSIS_NOT_APPROVAL: 'SENSITIVITY_ANALYSIS_NOT_APPROVAL',
  AI_TOOL_ENTITLEMENT_NOT_AUTHORITY: 'AI_TOOL_ENTITLEMENT_NOT_AUTHORITY',
  AI_DATA_ENTITLEMENT_NOT_DISCLOSURE_RIGHT: 'AI_DATA_ENTITLEMENT_NOT_DISCLOSURE_RIGHT',
  HUMAN_DISPOSITION_REQUIRED_FOR_CONSEQUENTIAL_AI:
    'HUMAN_DISPOSITION_REQUIRED_FOR_CONSEQUENTIAL_AI',
  AI_INCIDENT_TRIGGERS_SUSPENSION_REVIEW: 'AI_INCIDENT_TRIGGERS_SUSPENSION_REVIEW',
  EVALUATION_SCORE_NOT_APPROVAL: 'EVALUATION_SCORE_NOT_APPROVAL',
  MONITORING_RULE_NOT_ENFORCEMENT_AUTHORITY: 'MONITORING_RULE_NOT_ENFORCEMENT_AUTHORITY',
  RISK_LEVEL_NOT_SANCTION_LEVEL: 'RISK_LEVEL_NOT_SANCTION_LEVEL',
  ANALYSIS_REQUEST_NOT_DECISION_REQUEST: 'ANALYSIS_REQUEST_NOT_DECISION_REQUEST',
  COMPLETED_ANALYSIS_NOT_FINAL_ORDER: 'COMPLETED_ANALYSIS_NOT_FINAL_ORDER',
  SAFE_HALT_BLOCKS_CONSEQUENTIAL_PATH: 'SAFE_HALT_BLOCKS_CONSEQUENTIAL_PATH',
  UNRESOLVED_ENTITLEMENT_BLOCKS_EXECUTION: 'UNRESOLVED_ENTITLEMENT_BLOCKS_EXECUTION',
  CASE_SCOPED_EXECUTION_ONLY: 'CASE_SCOPED_EXECUTION_ONLY',
  INSTITUTION_BOUNDARY_ON_RETRIEVAL: 'INSTITUTION_BOUNDARY_ON_RETRIEVAL',
  DETERMINISTIC_ADAPTER_NOT_DECISION_ENGINE: 'DETERMINISTIC_ADAPTER_NOT_DECISION_ENGINE',
  PROMPT_GOVERNANCE_NOT_POLICY_AUTHORITY: 'PROMPT_GOVERNANCE_NOT_POLICY_AUTHORITY',
  FORECAST_STALENESS_REQUIRES_DISCLAIMER: 'FORECAST_STALENESS_REQUIRES_DISCLAIMER',
  INDICATOR_STALENESS_SAFE_HALT: 'INDICATOR_STALENESS_SAFE_HALT',
  REPORT_GENERATION_SAFE_HALT: 'REPORT_GENERATION_SAFE_HALT',
  SIMULATION_RUN_SAFE_HALT: 'SIMULATION_RUN_SAFE_HALT',
  ANALYSIS_RUN_SAFE_HALT: 'ANALYSIS_RUN_SAFE_HALT',
  PERFORMANCE_CLAIM_CLIENT_STATUS_FORBIDDEN: 'PERFORMANCE_CLAIM_CLIENT_STATUS_FORBIDDEN',
  DASHBOARD_CLIENT_AUTHORITY_FIELDS_FORBIDDEN: 'DASHBOARD_CLIENT_AUTHORITY_FIELDS_FORBIDDEN',
  METRIC_CLIENT_COMPUTED_VALUE_FORBIDDEN: 'METRIC_CLIENT_COMPUTED_VALUE_FORBIDDEN',
  AI_EXECUTION_CLIENT_DECISION_FIELDS_FORBIDDEN: 'AI_EXECUTION_CLIENT_DECISION_FIELDS_FORBIDDEN',
  INTELLIGENCE_LAYER_BOUNDARY_NON_WAIVABLE: 'INTELLIGENCE_LAYER_BOUNDARY_NON_WAIVABLE',
} as const satisfies Record<IntelligenceInvariantCode, IntelligenceInvariantCode>;

export type IntelligenceReasonCode =
  (typeof INTELLIGENCE_REASON_CODES)[keyof typeof INTELLIGENCE_REASON_CODES];
