export const APPLICATIONS_MODEL_NAMES = [
  'Application',
  'ApplicationSubmission',
  'Case',
  'CaseWorkflowInstance',
  'CaseWorkflowStepInstance',
  'CompletenessReview',
  'DeficiencyNotice',
  'ApplicantInformationRequest',
] as const;

export const CASE_WORKFLOW_STAGES = [
  'SUBMITTED',
  'COMPLETENESS_REVIEW',
  'INCOMPLETE',
  'WAITING_APPLICANT',
  'RESUBMITTED',
  'ADMINISTRATIVELY_COMPLETE',
  'SUBSTANTIVE_REVIEW',
  'SAFE_HALTED',
] as const;

export const COMPLETENESS_REVIEW_STATUSES = [
  'PENDING',
  'IN_REVIEW',
  'INCOMPLETE',
  'COMPLETE',
  'UNRESOLVED',
  'SAFE_HALTED',
] as const;

export const COMPLETENESS_REVIEW_ITEM_STATUSES = [
  'PRESENT',
  'MISSING',
  'ILLEGIBLE',
  'CORRUPTED',
  'APPARENTLY_INCONSISTENT',
  'SUBSTITUTION_PENDING',
  'NOT_APPLICABLE',
  'UNRESOLVED',
] as const;

export const FORBIDDEN_COMPLETENESS_ITEM_STATUSES = ['VERIFIED'] as const;

export const CASE_WORKFLOW_INSTANCE_STATUSES = [
  'NOT_STARTED',
  'PENDING',
  'ACTIVE',
  'WAITING_APPLICANT',
  'WAITING_EXTERNAL',
  'SAFE_HALTED',
  'COMPLETED',
  'SUSPENDED',
] as const;

export const CASE_WORKFLOW_STEP_INSTANCE_STATUSES = [
  'PENDING',
  'ACTIVE',
  'COMPLETED',
  'SKIPPED',
  'FAILED',
  'WAITING_APPLICANT',
  'WAITING_EXTERNAL',
  'SAFE_HALTED',
] as const;

export const WORKFLOW_STEP_TYPES = [
  'INTAKE',
  'COMPLETENESS_REVIEW',
  'SUBSTANTIVE_REVIEW',
  'EXTERNAL_REFERRAL',
  'INTERNAL_COORDINATION',
  'PROFESSIONAL_REVIEW',
  'DECISION_GATE',
  'ISSUANCE_GATE',
  'PARALLEL_JOIN',
] as const;

export const TERMINAL_CASE_WORKFLOW_INSTANCE_STATUSES = [
  'COMPLETED',
  'CANCELLED',
  'SAFE_HALTED',
] as const;

export const TERMINAL_CASE_WORKFLOW_STEP_INSTANCE_STATUSES = [
  'COMPLETED',
  'FAILED',
  'SAFE_HALTED',
] as const;

export const NON_PRODUCTION_APPLICATIONS_FIXTURE_MARKER = 'NON_PRODUCTION_PHASE_6D';
