export const NON_PRODUCTION_APPLICATIONS_FIXTURE_MARKER =
  'NON_PRODUCTION_APPLICATIONS_TEST_ONLY';

export const APPLICATIONS_EXPLANATION_CODES = {
  UNDISCLOSED_REQUIREMENT: 'UNDISCLOSED_REQUIREMENT',
  CHECKLIST_VERSION_MISMATCH: 'CHECKLIST_VERSION_MISMATCH',
  CONFIGURATION_FINGERPRINT_MISMATCH: 'CONFIGURATION_FINGERPRINT_MISMATCH',
  INVALID_WORKFLOW_TRANSITION: 'INVALID_WORKFLOW_TRANSITION',
  UNAUTHORIZED_COMPLETENESS_FINALIZATION: 'UNAUTHORIZED_COMPLETENESS_FINALIZATION',
  AI_CANNOT_FINALIZE_CONSEQUENTIAL_REVIEW: 'AI_CANNOT_FINALIZE_CONSEQUENTIAL_REVIEW',
  REVIEW_ALREADY_FINALIZED: 'REVIEW_ALREADY_FINALIZED',
  SUBMISSION_IMMUTABLE: 'SUBMISSION_IMMUTABLE',
  DEFICIENCY_NOTICE_IS_PROCEDURAL: 'DEFICIENCY_NOTICE_IS_PROCEDURAL',
  ADMINISTRATIVE_COMPLETENESS_NOT_APPROVAL: 'ADMINISTRATIVE_COMPLETENESS_NOT_APPROVAL',
  NEWER_CHECKLIST_CANNOT_ALTER_EXISTING_CASE: 'NEWER_CHECKLIST_CANNOT_ALTER_EXISTING_CASE',
} as const;

export type ApplicationsExplanationCode =
  (typeof APPLICATIONS_EXPLANATION_CODES)[keyof typeof APPLICATIONS_EXPLANATION_CODES];

export const COMPLETENESS_REVIEW_NOTIFICATION_EVENTS = {
  DEFICIENCY_NOTICE_ISSUED: 'DEFICIENCY_NOTICE_ISSUED',
  COMPLETENESS_REVIEW_COMPLETE: 'COMPLETENESS_REVIEW_COMPLETE',
  APPLICANT_CORRECTION_RECEIVED: 'APPLICANT_CORRECTION_RECEIVED',
} as const;
