-- CreateEnum
CREATE TYPE "SessionRevocationReason" AS ENUM ('USER_LOGOUT', 'ADMIN_REVOCATION', 'ACCOUNT_REVOCATION', 'SECURITY_EVENT', 'REPLACED', 'EXPIRED');

-- AlterEnum
ALTER TYPE "SecurityAuditEventType" ADD VALUE 'SESSION_EXPIRED';
ALTER TYPE "SecurityAuditEventType" ADD VALUE 'CREDENTIAL_REJECTED';
ALTER TYPE "SecurityAuditEventType" ADD VALUE 'SUSPENDED_ACCOUNT_LOGIN_ATTEMPT';
ALTER TYPE "SecurityAuditEventType" ADD VALUE 'REVOKED_ACCOUNT_LOGIN_ATTEMPT';

-- AlterTable
ALTER TABLE "sessions" ADD COLUMN "issuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "sessions" ADD COLUMN "lastUsedAt" TIMESTAMP(3);
ALTER TABLE "sessions" ADD COLUMN "revocationReason" "SessionRevocationReason";
