export const AUTHORITY_CLASSIFICATIONS = [
  'ABSEZ_OWNED',
  'ABSEZ_DELEGATED',
  'EXPRESSLY_RETAINED_NATIONAL',
  'SHARED_OR_COORDINATED',
  'RESERVED_PROFESSIONAL',
  'ADMINISTRATIVE_SUPPORT',
  'TECHNOLOGY_ASSISTED',
  'PROHIBITED_OR_UNAUTHORIZED',
] as const;

export const AUTHORITY_LIFECYCLE_STATES = [
  'RECOGNIZED',
  'REVIEWED',
  'ENABLED',
  'TESTED',
  'ACCEPTED',
  'ACTIVE',
  'SUSPENDED',
  'SUPERSEDED',
] as const;

export const CONTROLLED_FUNCTION_CLASSES = [
  'INFORMATION_AND_GUIDANCE',
  'APPLICANT_INTAKE',
  'IDENTITY_VERIFICATION',
  'ELIGIBILITY_SCREENING',
  'COMPLETENESS_REVIEW',
  'EVIDENCE_VERIFICATION',
  'FEE_CALCULATION_AND_COLLECTION',
  'DEPARTMENTAL_ASSESSMENT',
  'GOVERNMENT_REFERRAL',
  'PROFESSIONAL_REVIEW',
  'INSPECTION',
  'RECOMMENDATION',
  'ADMINISTRATIVE_DECISION',
  'EXPRESSLY_RETAINED_NATIONAL_DECISION',
  'ISSUANCE',
  'REGISTRATION',
  'MONITORING',
  'COMPLIANCE_REVIEW',
  'RENEWAL',
  'VARIATION',
  'SUSPENSION',
  'REVOCATION',
  'COMPLAINT',
  'RECONSIDERATION',
  'APPEAL_SUPPORT',
  'REPORTING',
  'RECORDS_MANAGEMENT',
  'ENFORCEMENT_REFERRAL',
  'EMERGENCY_OR_CONTINUITY_ACTION',
  'SERVICE_RETIREMENT',
] as const;

export const FORBIDDEN_AUTHORITY_BOUNDARY_FIELDS = [
  'canApprove',
  'isAdminAuthority',
  'isGovernmentAuthority',
] as const;

export const AUTHORITY_MODEL_NAMES = ['FunctionAuthorityRecord'] as const;

export const NON_AUTHORITY_MODEL_NAMES = [
  'UserAccount',
  'Identity',
  'Credential',
  'OrganizationMembership',
  'AuthenticationMethod',
  'Session',
  'Appointment',
  'Delegation',
  'Officeholder',
] as const;
