export const INTEGRATION_MODEL_NAMES = [
  'Integration',
  'IntegrationVersion',
  'IntegrationCredential',
  'IntegrationRequest',
  'IntegrationExchange',
  'IntegrationMessage',
  'IntegrationDeliveryAttempt',
  'IntegrationResponseRecord',
  'IntegrationWebhookEvent',
  'IntegrationCorrelationRecord',
  'IntegrationDataTransformation',
  'IntegrationValidationResult',
] as const;

export const INTEGRATION_EXCHANGE_STATUSES = [
  'PREPARED',
  'SENT',
  'ACKNOWLEDGED',
  'RESPONSE_RECEIVED',
  'VALIDATED',
  'RECONCILIATION_REQUIRED',
  'FAILED',
  'TIMED_OUT',
  'RETRY_PENDING',
  'SAFE_HALTED',
  'CANCELLED',
] as const;

export const INTEGRATION_OPERATIONS = [
  'QUERY',
  'SUBMIT',
  'UPDATE',
  'SEND_EVENT',
  'RECEIVE_EVENT',
  'HEALTH_CHECK',
] as const;

export const FORBIDDEN_INTEGRATION_AUTHORITY_FIELDS = [
  'approved',
  'refused',
  'verified',
  'decisionOutcome',
  'authorityGranted',
  'officeholderId',
export const PHASE_11E_MODEL_NAMES = [
  'TechnologyDependency',
  'IntegrationDefinition',
  'IntegrationVersion',
  'IntegrationEndpoint',
  'DataExchangeContract',
  'DataExchangeField',
  'AuthoritativeSourceDesignation',
  'FieldAuthorityMapping',
  'IntegrationCredentialReference',
  'IntegrationInstitutionOwner',
  'IntegrationDependency',
  'IntegrationApproval',
  'IntegrationAcceptanceRecord',
] as const;

export const PHASE_11E_ENUM_NAMES = [
  'TechnologyDependencyCategory',
  'IntegrationDefinitionStatus',
  'IntegrationVersionStatus',
  'IntegrationDirection',
  'AuthoritativeSourceStatus',
  'IntegrationAcceptanceState',
  'IntegrationApprovalType',
  'IntegrationApprovalStatus',
  'DataExchangeFieldClassification',
  'FieldAuthorityConflictBehavior',
  'CredentialRotationStatus',
  'AuthoritativeDesignationStatus',
  'TechnologyDependencyStatus',
] as const;

export const AUTHORITATIVE_SOURCE_STATUSES = [
  'AUTHORITATIVE',
  'IMPLEMENTING',
  'SUPPORTING',
  'REFERENCE_ONLY',
  'APPLICANT_PROVIDED',
  'PROFESSIONALLY_ISSUED',
  'THIRD_PARTY_REPORTED',
  'DERIVED',
  'MODELED',
  'UNVERIFIED',
] as const;

export const INTEGRATION_ACCEPTANCE_STATES = [
  'DISCOVERED',
  'DESIGNED',
  'CONFIGURED',
  'TECHNICALLY_CONNECTED',
  'TESTED',
  'SECURITY_APPROVED',
  'PRIVACY_APPROVED',
  'INSTITUTIONALLY_ACCEPTED',
  'ACTIVE',
  'SUSPENDED',
  'RETIRED',
] as const;

export const TECHNOLOGY_DEPENDENCY_CATEGORIES = [
  'IDENTITY',
  'APPLICATION',
  'CASE_MANAGEMENT',
  'GOVERNMENT_REGISTRY',
  'PROFESSIONAL_REGISTRY',
  'PAYMENT_BANKING',
  'DOCUMENT_RECORDS',
  'GEOSPATIAL_LAND',
  'PLANNING',
  'ENVIRONMENT',
  'CUSTOMS',
  'TAX',
  'IMMIGRATION',
  'CORPORATE',
  'LABOUR',
  'HEALTH',
  'MARITIME',
  'TOURISM',
  'LICENSING',
  'SIGNATURE_SEAL_TIMESTAMP',
  'NOTIFICATION',
  'HOSTING',
  'TELECOM',
  'CYBERSECURITY',
  'DIGITAL_TWIN',
  'ANALYTICS',
  'AI_MODEL',
  'BACKUP_ARCHIVAL',
  'SOURCE_CODE_DEPLOYMENT',
  'VENDOR',
  'OTHER',
] as const;
