export const PHASE_11E_MODEL_NAMES = [
  'TechnologyDependency',
  'IntegrationDefinition',
  'IntegrationVersion',
  'IntegrationEndpoint',
  'DataExchangeContract',
  'DataExchangeField',
  'AuthoritativeSourceDesignation',
  'FieldAuthorityMapping',
  'IntegrationCredentialReference',
  'IntegrationInstitutionOwner',
  'IntegrationDependency',
  'IntegrationApproval',
  'IntegrationAcceptanceRecord',
] as const;

export const PHASE_11E_ENUM_NAMES = [
  'TechnologyDependencyCategory',
  'IntegrationDefinitionStatus',
  'IntegrationVersionStatus',
  'IntegrationDirection',
  'AuthoritativeSourceStatus',
  'IntegrationAcceptanceState',
  'IntegrationApprovalType',
  'IntegrationApprovalStatus',
  'DataExchangeFieldClassification',
  'FieldAuthorityConflictBehavior',
  'CredentialRotationStatus',
  'AuthoritativeDesignationStatus',
  'TechnologyDependencyStatus',
] as const;

export const AUTHORITATIVE_SOURCE_STATUSES = [
  'AUTHORITATIVE',
  'IMPLEMENTING',
  'SUPPORTING',
  'REFERENCE_ONLY',
  'APPLICANT_PROVIDED',
  'PROFESSIONALLY_ISSUED',
  'THIRD_PARTY_REPORTED',
  'DERIVED',
  'MODELED',
  'UNVERIFIED',
] as const;

export const INTEGRATION_ACCEPTANCE_STATES = [
  'DISCOVERED',
  'DESIGNED',
  'CONFIGURED',
  'TECHNICALLY_CONNECTED',
  'TESTED',
  'SECURITY_APPROVED',
  'PRIVACY_APPROVED',
  'INSTITUTIONALLY_ACCEPTED',
  'ACTIVE',
  'SUSPENDED',
  'RETIRED',
] as const;

export const TECHNOLOGY_DEPENDENCY_CATEGORIES = [
  'IDENTITY',
  'APPLICATION',
  'CASE_MANAGEMENT',
  'GOVERNMENT_REGISTRY',
  'PROFESSIONAL_REGISTRY',
  'PAYMENT_BANKING',
  'DOCUMENT_RECORDS',
  'GEOSPATIAL_LAND',
  'PLANNING',
  'ENVIRONMENT',
  'CUSTOMS',
  'TAX',
  'IMMIGRATION',
  'CORPORATE',
  'LABOUR',
  'HEALTH',
  'MARITIME',
  'TOURISM',
  'LICENSING',
  'SIGNATURE_SEAL_TIMESTAMP',
  'NOTIFICATION',
  'HOSTING',
  'TELECOM',
  'CYBERSECURITY',
  'DIGITAL_TWIN',
  'ANALYTICS',
  'AI_MODEL',
  'BACKUP_ARCHIVAL',
  'SOURCE_CODE_DEPLOYMENT',
  'VENDOR',
  'OTHER',
] as const;
