export const INTEGRATIONS_EXPLANATION_CODES = {
  INTEGRATION_NOT_ACTIVE: 'INTEGRATION_NOT_ACTIVE',
  INTEGRATION_SUSPENDED: 'INTEGRATION_SUSPENDED',
  CREDENTIAL_NOT_ACTIVE: 'CREDENTIAL_NOT_ACTIVE',
  OPERATION_NOT_PERMITTED: 'OPERATION_NOT_PERMITTED',
  PURPOSE_NOT_PERMITTED: 'PURPOSE_NOT_PERMITTED',
  FIELD_NOT_PERMITTED: 'FIELD_NOT_PERMITTED',
  CLASSIFICATION_NOT_PERMITTED: 'CLASSIFICATION_NOT_PERMITTED',
  IDENTITY_NOT_AUTHORIZED: 'IDENTITY_NOT_AUTHORIZED',
  SERVICE_IDENTITY_NO_AUTHORITY: 'SERVICE_IDENTITY_NO_AUTHORITY',
  IDEMPOTENCY_DUPLICATE: 'IDEMPOTENCY_DUPLICATE',
  HTTP_SUCCESS_NOT_VALIDATED: 'HTTP_SUCCESS_NOT_VALIDATED',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  REPLAY_REJECTED: 'REPLAY_REJECTED',
  DUPLICATE_EVENT: 'DUPLICATE_EVENT',
  UNEXPECTED_EVENT_TYPE: 'UNEXPECTED_EVENT_TYPE',
  INVALID_SCHEMA: 'INVALID_SCHEMA',
  EXPIRED_TIMESTAMP: 'EXPIRED_TIMESTAMP',
  FIELD_NOT_INVENTED: 'FIELD_NOT_INVENTED',
  TIMEOUT_NO_NEGATIVE_FINDING: 'TIMEOUT_NO_NEGATIVE_FINDING',
  EXTERNAL_FAILURE_NO_DECISION: 'EXTERNAL_FAILURE_NO_DECISION',
  SAFE_HALTED: 'SAFE_HALTED',
  ADAPTER_NOT_FOUND: 'ADAPTER_NOT_FOUND',
  OPERATION_NOT_SUPPORTED: 'OPERATION_NOT_SUPPORTED',
} as const;

export const SANDBOX_ADAPTER_TYPE = 'sandbox';
export const TEST_ADAPTER_TYPE = 'test';

export const DEFAULT_WEBHOOK_TIMESTAMP_TOLERANCE_MS = 5 * 60 * 1000;
export const FORBIDDEN_INTEGRATION_DEFINITION_CLIENT_FIELDS = [
  'status',
  'currentAcceptanceState',
  'acceptedAt',
  'supersededByVersionId',
] as const;

export const FORBIDDEN_INTEGRATION_VERSION_CLIENT_FIELDS = [
  'status',
  'currentAcceptanceState',
  'acceptedAt',
  'supersededByVersionId',
] as const;

export const FORBIDDEN_AUTHORITATIVE_DESIGNATION_CLIENT_FIELDS = [
  'sourceStatus',
  'designationStatus',
] as const;

export const FORBIDDEN_CREDENTIAL_RESPONSE_FIELDS = [
  'secretReference',
  'certificateReference',
] as const;

export const FORBIDDEN_TECHNICAL_CONNECTION_FIELDS = [
  'sourceStatus',
  'designationStatus',
  'currentAcceptanceState',
] as const;

export const ACTIVE_ACCEPTANCE_REQUIRED_STATES = [
  'CONFIGURED',
  'TESTED',
  'SECURITY_APPROVED',
  'PRIVACY_APPROVED',
  'INSTITUTIONALLY_ACCEPTED',
] as const;

export const INTEGRATION_ACCEPTANCE_ACTIVE_GATE_STATES = [
  'CONFIGURED',
  'TESTED',
  'SECURITY_APPROVED',
  'PRIVACY_APPROVED',
  'INSTITUTIONALLY_ACCEPTED',
] as const;

export const IMMUTABLE_ACCEPTED_VERSION_FIELDS = [
  'version',
  'sourceSystem',
  'destinationSystem',
  'direction',
  'protocol',
  'dataContractVersion',
] as const;

export const INTEGRATION_REGISTRY_DISCLAIMER =
  'Registry metadata does not constitute connectivity, acceptance, or authoritative designation.';
