export const SERVICE_READINESS_CHECK_CODES = {
  STABLE_SERVICE_EXISTS: 'STABLE_SERVICE_EXISTS',
  RESPONSIBLE_INSTITUTION_EXISTS: 'RESPONSIBLE_INSTITUTION_EXISTS',
  RESPONSIBLE_DEPARTMENT_EXISTS: 'RESPONSIBLE_DEPARTMENT_EXISTS',
  SERVICE_OWNER_CONFIGURED: 'SERVICE_OWNER_CONFIGURED',
  AUTHORITY_FUNCTION_MAPPINGS_EXIST: 'AUTHORITY_FUNCTION_MAPPINGS_EXIST',
  CONSEQUENTIAL_FUNCTIONS_VALID: 'CONSEQUENTIAL_FUNCTIONS_VALID',
  GOVERNING_SOURCE_LINKAGE: 'GOVERNING_SOURCE_LINKAGE',
  PUBLISHED_FORM_EXISTS: 'PUBLISHED_FORM_EXISTS',
  CURRENT_REQUIREMENTS_EXIST: 'CURRENT_REQUIREMENTS_EXIST',
  FEE_SCHEDULE_VALID: 'FEE_SCHEDULE_VALID',
  DEPENDENCIES_DECLARED: 'DEPENDENCIES_DECLARED',
  EXPECTED_OUTPUT_DEFINED: 'EXPECTED_OUTPUT_DEFINED',
  REDRESS_ROUTE_DEFINED: 'REDRESS_ROUTE_DEFINED',
  PUBLIC_DESCRIPTION_COMPLETE: 'PUBLIC_DESCRIPTION_COMPLETE',
  SERVICE_VERSION_EFFECTIVE: 'SERVICE_VERSION_EFFECTIVE',
  TEST_READINESS_SUFFICIENT: 'TEST_READINESS_SUFFICIENT',
  ACTIVATION_AUTHORITY_CONFIGURED: 'ACTIVATION_AUTHORITY_CONFIGURED',
} as const;

export type ServiceReadinessCheckCode =
  (typeof SERVICE_READINESS_CHECK_CODES)[keyof typeof SERVICE_READINESS_CHECK_CODES];

export const SERVICE_ACTIVATION_BASIS = {
  INSTITUTIONAL_ACCEPTANCE: 'INSTITUTIONAL_ACCEPTANCE',
  OPERATIONAL_ACTIVATION: 'OPERATIONAL_ACTIVATION',
  PILOT_ACTIVATION: 'PILOT_ACTIVATION',
  PUBLICATION: 'PUBLICATION',
  SUSPENSION: 'SUSPENSION',
  SUPERSESSION: 'SUPERSESSION',
} as const;
