export const NON_PRODUCTION_PHASE_8D_FIXTURE_MARKER = 'NON_PRODUCTION_PHASE_8D_TEST_ONLY';

export const SIGNATURE_SEAL_BOUNDARY_DISCLAIMER =
  'A cryptographic credential does not create institutional signing authority. Valid credential does not equal valid authority. Signature image does not equal secure electronic signature. Seal image does not equal valid institutional seal application.';

export const FORBIDDEN_CLIENT_SIGNATURE_FIELDS = [
  'signatureValue',
  'privateKey',
  'certificatePrivateKey',
  'signatureStatus',
  'sealStatus',
  'validationResult',
  'documentHash',
  'integrityEvidence',
] as const;

export const SIGNATURE_EXPLANATION_CODES = {
  CREDENTIAL_WITHOUT_AUTHORITY: 'CREDENTIAL_WITHOUT_AUTHORITY',
  AUTHORITY_WITHOUT_CREDENTIAL: 'AUTHORITY_WITHOUT_CREDENTIAL',
  EXPIRED_APPOINTMENT: 'EXPIRED_APPOINTMENT',
  REVOKED_DELEGATION: 'REVOKED_DELEGATION',
  REVOKED_CERTIFICATE: 'REVOKED_CERTIFICATE',
  WRONG_INSTRUMENT_TYPE: 'WRONG_INSTRUMENT_TYPE',
  HASH_MISMATCH: 'HASH_MISMATCH',
  IMAGE_ONLY_SIGNATURE: 'IMAGE_ONLY_SIGNATURE',
  IMAGE_ONLY_SEAL: 'IMAGE_ONLY_SEAL',
  SERVICE_IDENTITY_CANNOT_SIGN: 'SERVICE_IDENTITY_CANNOT_SIGN',
  AI_CANNOT_SIGN: 'AI_CANNOT_SIGN',
  ADMIN_CANNOT_SIGN: 'ADMIN_CANNOT_SIGN',
  SELF_APPROVAL_DENIED: 'SELF_APPROVAL_DENIED',
  REVOKED_SEAL: 'REVOKED_SEAL',
  CUSTODIAN_NOT_UNLIMITED: 'CUSTODIAN_NOT_UNLIMITED',
  SIGNING_EVENT_APPEND_ONLY: 'SIGNING_EVENT_APPEND_ONLY',
  PRIVATE_KEY_NEVER_PERSISTED: 'PRIVATE_KEY_NEVER_PERSISTED',
  HISTORICAL_SIGNATURE_PRESERVED: 'HISTORICAL_SIGNATURE_PRESERVED',
  DOCUMENT_STATE_DENIED: 'DOCUMENT_STATE_DENIED',
  IDENTITY_ASSURANCE_INSUFFICIENT: 'IDENTITY_ASSURANCE_INSUFFICIENT',
  MFA_REQUIRED: 'MFA_REQUIRED',
  AUTHORIZATION_EXCEEDS_AUTHORITY: 'AUTHORIZATION_EXCEEDS_AUTHORITY',
} as const;

export const PHASE_8D_MODEL_NAMES = [
  'ElectronicSignatureAuthorization',
  'ElectronicSignatureCredentialReference',
  'ElectronicSignatureRecord',
  'ElectronicSignatureValidationRecord',
  'ElectronicSealDefinition',
  'ElectronicSealCustodyAssignment',
  'ElectronicSealUseAuthorization',
  'ElectronicSealUseRecord',
  'SignableInstrumentBinding',
] as const;

export const FORBIDDEN_PRIVATE_KEY_PATTERNS = [
  /BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY/i,
  /privateKey/i,
  /pkcs8/i,
export const NON_PRODUCTION_DECISIONS_ISSUANCE_FIXTURE_MARKER =
  'NON_PRODUCTION_DECISIONS_ISSUANCE_TEST_ONLY';

export const PHASE_8E_BOUNDARY_DISCLAIMER =
  'Phase 8E establishes the official instrument catalog and controlled issuance engine. A government decision alone does not constitute issuance. A generated document alone is not an official instrument until the issuance event completes successfully.';

export const INSTRUMENT_NUMBER_PREFIX = 'INST';

export const DECISION_NUMBER_PREFIX = 'DEC';

export const FORBIDDEN_CLIENT_ISSUANCE_FIELDS = [
  'instrumentNumber',
  'status',
  'currentVersionId',
  'verificationCode',
  'contentHash',
  'signatureRecord',
  'sealRecord',
  'issuerSource',
] as const;

export const FORBIDDEN_TEMPLATE_INJECTION_PATTERNS = [
  /<script\b/i,
  /<\/script>/i,
  /javascript:/i,
  /on\w+\s*=/i,
  /\{\{.*\}\}/,
  /<%/,
  /%>/,
] as const;

export const ISSUANCE_APPROVING_OUTCOMES = ['APPROVED', 'CONDITIONALLY_APPROVED'] as const;

export const ISSUANCE_READINESS_CHECK_CODES = {
  DECISION_EXISTS: 'DECISION_EXISTS',
  DECISION_BELONGS_TO_CASE: 'DECISION_BELONGS_TO_CASE',
  DECISION_TYPE_ALLOWS_INSTRUMENT: 'DECISION_TYPE_ALLOWS_INSTRUMENT',
  DECISION_FORMALIZED: 'DECISION_FORMALIZED',
  DECISION_HAS_REASONS: 'DECISION_HAS_REASONS',
  NOTICE_STATUS_SATISFIED: 'NOTICE_STATUS_SATISFIED',
  DECISION_NOT_SUPERSEDED: 'DECISION_NOT_SUPERSEDED',
  ISSUE_AUTHORITY_ALLOW: 'ISSUE_AUTHORITY_ALLOW',
  ISSUER_AUTHORIZED: 'ISSUER_AUTHORIZED',
  OUTCOME_PERMITS_ISSUANCE: 'OUTCOME_PERMITS_ISSUANCE',
  PRECEDENT_CONDITIONS_SATISFIED: 'PRECEDENT_CONDITIONS_SATISFIED',
  SIGNATURE_PRESENT: 'SIGNATURE_PRESENT',
  SIGNATURE_VALID: 'SIGNATURE_VALID',
  SEAL_PRESENT: 'SEAL_PRESENT',
  SEAL_VALID: 'SEAL_VALID',
  TEMPLATE_VERSION_ACTIVE: 'TEMPLATE_VERSION_ACTIVE',
  NUMBERING_RULE_ACTIVE: 'NUMBERING_RULE_ACTIVE',
  HOLDER_ESTABLISHED: 'HOLDER_ESTABLISHED',
  SCOPE_ESTABLISHED: 'SCOPE_ESTABLISHED',
  EFFECTIVE_DATE_ESTABLISHED: 'EFFECTIVE_DATE_ESTABLISHED',
  EXPIRY_DATE_ESTABLISHED: 'EXPIRY_DATE_ESTABLISHED',
  VERIFICATION_METHOD_AVAILABLE: 'VERIFICATION_METHOD_AVAILABLE',
  RECORDS_INFRASTRUCTURE_AVAILABLE: 'RECORDS_INFRASTRUCTURE_AVAILABLE',
  NO_SAFE_HALT: 'NO_SAFE_HALT',
  NO_RETAINED_NATIONAL_BLOCK: 'NO_RETAINED_NATIONAL_BLOCK',
} as const;

export const ISSUANCE_READINESS_CHECK_ORDER = [
  ISSUANCE_READINESS_CHECK_CODES.DECISION_EXISTS,
  ISSUANCE_READINESS_CHECK_CODES.DECISION_BELONGS_TO_CASE,
  ISSUANCE_READINESS_CHECK_CODES.DECISION_TYPE_ALLOWS_INSTRUMENT,
  ISSUANCE_READINESS_CHECK_CODES.DECISION_FORMALIZED,
  ISSUANCE_READINESS_CHECK_CODES.DECISION_HAS_REASONS,
  ISSUANCE_READINESS_CHECK_CODES.NOTICE_STATUS_SATISFIED,
  ISSUANCE_READINESS_CHECK_CODES.DECISION_NOT_SUPERSEDED,
  ISSUANCE_READINESS_CHECK_CODES.ISSUE_AUTHORITY_ALLOW,
  ISSUANCE_READINESS_CHECK_CODES.ISSUER_AUTHORIZED,
  ISSUANCE_READINESS_CHECK_CODES.OUTCOME_PERMITS_ISSUANCE,
  ISSUANCE_READINESS_CHECK_CODES.PRECEDENT_CONDITIONS_SATISFIED,
  ISSUANCE_READINESS_CHECK_CODES.SIGNATURE_PRESENT,
  ISSUANCE_READINESS_CHECK_CODES.SIGNATURE_VALID,
  ISSUANCE_READINESS_CHECK_CODES.SEAL_PRESENT,
  ISSUANCE_READINESS_CHECK_CODES.SEAL_VALID,
  ISSUANCE_READINESS_CHECK_CODES.TEMPLATE_VERSION_ACTIVE,
  ISSUANCE_READINESS_CHECK_CODES.NUMBERING_RULE_ACTIVE,
  ISSUANCE_READINESS_CHECK_CODES.HOLDER_ESTABLISHED,
  ISSUANCE_READINESS_CHECK_CODES.SCOPE_ESTABLISHED,
  ISSUANCE_READINESS_CHECK_CODES.EFFECTIVE_DATE_ESTABLISHED,
  ISSUANCE_READINESS_CHECK_CODES.EXPIRY_DATE_ESTABLISHED,
  ISSUANCE_READINESS_CHECK_CODES.VERIFICATION_METHOD_AVAILABLE,
  ISSUANCE_READINESS_CHECK_CODES.RECORDS_INFRASTRUCTURE_AVAILABLE,
  ISSUANCE_READINESS_CHECK_CODES.NO_SAFE_HALT,
  ISSUANCE_READINESS_CHECK_CODES.NO_RETAINED_NATIONAL_BLOCK,
] as const;
