export interface Phase8HInvariant {
  id: number;
  description: string;
  category: string;
}

export const PHASE_8H_INVARIANTS: readonly Phase8HInvariant[] = [
  { id: 1, category: 'boundary', description: 'Recommendation does not equal final government decision' },
  { id: 2, category: 'boundary', description: 'AI assistance does not equal official decision' },
  { id: 3, category: 'boundary', description: 'Technical readiness does not equal institutional acceptance' },
  { id: 4, category: 'boundary', description: 'Institutional acceptance does not equal production-active issuance' },
  { id: 5, category: 'boundary', description: 'Access does not equal authority to decide' },
  { id: 6, category: 'boundary', description: 'Case DECISION_PENDING does not create a government decision' },
  { id: 7, category: 'boundary', description: 'Evidence packet existence does not create a government decision' },
  { id: 8, category: 'boundary', description: 'Decision preparation does not create a government decision' },
  { id: 9, category: 'boundary', description: 'Professional finding does not constitute institutional decision' },
  { id: 10, category: 'boundary', description: 'Readiness assessment alone does not create a government decision' },
  { id: 11, category: 'client', description: 'Client cannot set government decision status' },
  { id: 12, category: 'client', description: 'Client cannot set approved boolean on decision payloads' },
  { id: 13, category: 'client', description: 'Client cannot set refused boolean on decision payloads' },
  { id: 14, category: 'client', description: 'Client cannot set issued boolean on decision payloads' },
  { id: 15, category: 'client', description: 'Client cannot set draft boolean on decision payloads' },
  { id: 16, category: 'client', description: 'Client cannot set isDraft on decision payloads' },
  { id: 17, category: 'client', description: 'Client cannot bypass explicit decision-maker intent confirmation' },
  { id: 18, category: 'client', description: 'Client cannot set instrumentNumber on issuance' },
  { id: 19, category: 'client', description: 'Client cannot set instrument status on issuance' },
  { id: 20, category: 'client', description: 'Client cannot set currentVersionId on issuance' },
  { id: 21, category: 'client', description: 'Client cannot set verificationCode on issuance' },
  { id: 22, category: 'client', description: 'Client cannot set contentHash on issuance' },
  { id: 23, category: 'client', description: 'Client cannot set signatureRecord on issuance' },
  { id: 24, category: 'authority', description: 'Non-human actors cannot execute government decisions' },
  { id: 25, category: 'authority', description: 'AI actors cannot approve, refuse, sign, seal, or issue' },
  { id: 26, category: 'authority', description: 'Case manager role does not confer decision authority' },
  { id: 27, category: 'authority', description: 'Technical admin role does not confer decision authority' },
  { id: 28, category: 'authority', description: 'DECIDE action requires authority evaluation ALLOW' },
  { id: 29, category: 'authority', description: 'SIGN action requires authority evaluation ALLOW' },
  { id: 30, category: 'authority', description: 'ISSUE action requires authority evaluation ALLOW' },
  { id: 31, category: 'authority', description: 'SUSPEND action requires authority evaluation ALLOW' },
  { id: 32, category: 'authority', description: 'REVOKE action requires authority evaluation ALLOW' },
  { id: 33, category: 'authority', description: 'HEAR_REVIEW action requires authority evaluation ALLOW' },
  { id: 34, category: 'authority', description: 'Retained national determination cannot be substituted by ABSEZ' },
  { id: 35, category: 'evidence', description: 'Government decisions require frozen evidence packet version' },
  { id: 36, category: 'evidence', description: 'Unfrozen evidence packet blocks decision readiness READY' },
  { id: 37, category: 'evidence', description: 'Evidence packet must belong to the specified case' },
  { id: 38, category: 'evidence', description: 'Decision readiness assessment must be READY before execution' },
  { id: 39, category: 'decision', description: 'Unconfigured outcome rejected at decision execution' },
  { id: 40, category: 'decision', description: 'Recorded government decisions are immutable' },
  { id: 41, category: 'decision', description: 'Decision execution requires explicit intent confirmation' },
  { id: 42, category: 'decision', description: 'Conflicted decision-maker blocked from execution' },
  { id: 43, category: 'decision', description: 'Recused decision-maker blocked from execution' },
  { id: 44, category: 'decision', description: 'REFUSED outcome does not permit approval instrument issuance' },
  { id: 45, category: 'signature', description: 'Invalid signature document blocks issuance when required' },
  { id: 46, category: 'signature', description: 'Missing signature blocks issuance when required' },
  { id: 47, category: 'signature', description: 'Generated document alone is not a valid signature record' },
  { id: 48, category: 'signature', description: 'Signature status must be evaluated, not assumed from title' },
  { id: 49, category: 'signature', description: 'SIGNATURE_INVALID blocks issuance readiness' },
  { id: 50, category: 'signature', description: 'Unsigned document cannot satisfy signature requirement' },
  { id: 51, category: 'seal', description: 'Invalid seal document blocks issuance when required' },
  { id: 52, category: 'seal', description: 'Missing seal blocks issuance when required' },
  { id: 53, category: 'seal', description: 'Seal dual control requires distinct approver when configured' },
  { id: 54, category: 'seal', description: 'UNSEALED document cannot satisfy seal requirement' },
  { id: 55, category: 'seal', description: 'SEAL_INVALID blocks issuance readiness' },
  { id: 56, category: 'issuance', description: 'Government decision alone does not equal issued instrument' },
  { id: 57, category: 'issuance', description: 'REFUSED outcome does not permit instrument issuance' },
  { id: 58, category: 'issuance', description: 'Unmet PRECEDENT_TO_ISSUANCE conditions block issuance' },
  { id: 59, category: 'issuance', description: 'Issuance readiness must be READY before issue' },
  { id: 60, category: 'issuance', description: 'Inactive instrument type version blocks issuance' },
  { id: 61, category: 'issuance', description: 'Inactive numbering rule blocks issuance' },
  { id: 62, category: 'issuance', description: 'Duplicate instrument numbers are impossible per numbering rule' },
  { id: 63, category: 'issuance', description: 'Retained-national instrument type forbids ABSEZ issuance' },
  { id: 64, category: 'lifecycle', description: 'Suspension notice kind is distinct from license kind' },
  { id: 65, category: 'lifecycle', description: 'Revocation notice kind is distinct from certificate kind' },
  { id: 66, category: 'lifecycle', description: 'Amended instrument preserves prior version history' },
  { id: 67, category: 'lifecycle', description: 'Suspension and revocation remain distinct instrument states' },
  { id: 68, category: 'case', description: 'Case transition to DECIDED requires recorded government decision' },
  { id: 69, category: 'case', description: 'Case transition to ISSUED requires issued official instrument' },
  { id: 70, category: 'workflow', description: 'DECISION_GATE blocked without recorded government decision' },
] as const;
