export const NON_PRODUCTION_DECISIONS_ISSUANCE_FIXTURE_MARKER =
  'NON_PRODUCTION_DECISIONS_ISSUANCE_TEST_ONLY';

export const PHASE_8E_BOUNDARY_DISCLAIMER =
  'Phase 8E establishes the official instrument catalog and controlled issuance engine. A government decision alone does not constitute issuance. A generated document alone is not an official instrument until the issuance event completes successfully.';

export const PHASE_8F_BOUNDARY_DISCLAIMER =
  'Issuance does not imply delivery. Delivery does not imply receipt. Receipt does not imply continuing validity.';

export const INSTRUMENT_NUMBER_PREFIX = 'INST';

export const DECISION_NUMBER_PREFIX = 'DEC';

export const VERIFICATION_CODE_BYTES = 32;
export const VERIFICATION_URI_PATH_PREFIX = '/api/v1/public/instruments/verify';

export const PUBLIC_VERIFICATION_RATE_LIMIT_WINDOW_SECONDS = 60;
export const PUBLIC_VERIFICATION_RATE_LIMIT_MAX_REQUESTS = 30;

export const FORBIDDEN_CLIENT_ISSUANCE_FIELDS = [
  'instrumentNumber',
  'status',
  'currentVersionId',
  'verificationCode',
  'contentHash',
  'signatureRecord',
  'sealRecord',
  'issuerSource',
] as const;

export const FORBIDDEN_CLIENT_INSTRUMENT_FIELDS = [
  'verificationCode',
  'verificationStatus',
  'status',
  'deliveredAt',
  'receivedAt',
  'currentVersionId',
  'issuedAt',
] as const;

export const FORBIDDEN_CLIENT_DELIVERY_FIELDS = [
  'status',
  'sentAt',
  'deliveredAt',
  'failedAt',
  'deliveryEvidenceReference',
] as const;

export const FORBIDDEN_PUBLIC_VERIFICATION_FIELDS = [
  'applicationDetails',
  'evidencePacket',
  'reasons',
  'privateConditions',
  'identityDocuments',
  'internalNotes',
  'professionalRecords',
  'governmentReferrals',
  'restrictedHolderData',
  'caseId',
  'governmentDecisionId',
  'holderIdentityId',
] as const;

export const RESTRICTED_DELIVERY_CLASSIFICATIONS = ['RESTRICTED', 'SECRET'] as const;

export const UNAPPROVED_CHANNELS_FOR_RESTRICTED = ['SECURE_EMAIL', 'PARTNER_INTEGRATION'] as const;

export const FORBIDDEN_TEMPLATE_INJECTION_PATTERNS = [
  /<script\b/i,
  /<\/script>/i,
  /javascript:/i,
  /on\w+\s*=/i,
  /\{\{.*\}\}/,
  /<%/,
  /%>/,
] as const;

export const ISSUANCE_APPROVING_OUTCOMES = ['APPROVED', 'CONDITIONALLY_APPROVED'] as const;

export const ISSUANCE_READINESS_CHECK_CODES = {
  DECISION_EXISTS: 'DECISION_EXISTS',
  DECISION_BELONGS_TO_CASE: 'DECISION_BELONGS_TO_CASE',
  DECISION_TYPE_ALLOWS_INSTRUMENT: 'DECISION_TYPE_ALLOWS_INSTRUMENT',
  DECISION_FORMALIZED: 'DECISION_FORMALIZED',
  DECISION_HAS_REASONS: 'DECISION_HAS_REASONS',
  NOTICE_STATUS_SATISFIED: 'NOTICE_STATUS_SATISFIED',
  DECISION_NOT_SUPERSEDED: 'DECISION_NOT_SUPERSEDED',
  ISSUE_AUTHORITY_ALLOW: 'ISSUE_AUTHORITY_ALLOW',
  ISSUER_AUTHORIZED: 'ISSUER_AUTHORIZED',
  OUTCOME_PERMITS_ISSUANCE: 'OUTCOME_PERMITS_ISSUANCE',
  PRECEDENT_CONDITIONS_SATISFIED: 'PRECEDENT_CONDITIONS_SATISFIED',
  SIGNATURE_PRESENT: 'SIGNATURE_PRESENT',
  SIGNATURE_VALID: 'SIGNATURE_VALID',
  SEAL_PRESENT: 'SEAL_PRESENT',
  SEAL_VALID: 'SEAL_VALID',
  TEMPLATE_VERSION_ACTIVE: 'TEMPLATE_VERSION_ACTIVE',
  NUMBERING_RULE_ACTIVE: 'NUMBERING_RULE_ACTIVE',
  HOLDER_ESTABLISHED: 'HOLDER_ESTABLISHED',
  SCOPE_ESTABLISHED: 'SCOPE_ESTABLISHED',
  EFFECTIVE_DATE_ESTABLISHED: 'EFFECTIVE_DATE_ESTABLISHED',
  EXPIRY_DATE_ESTABLISHED: 'EXPIRY_DATE_ESTABLISHED',
  VERIFICATION_METHOD_AVAILABLE: 'VERIFICATION_METHOD_AVAILABLE',
  RECORDS_INFRASTRUCTURE_AVAILABLE: 'RECORDS_INFRASTRUCTURE_AVAILABLE',
  NO_SAFE_HALT: 'NO_SAFE_HALT',
  NO_RETAINED_NATIONAL_BLOCK: 'NO_RETAINED_NATIONAL_BLOCK',
} as const;

export const ISSUANCE_READINESS_CHECK_ORDER = [
  ISSUANCE_READINESS_CHECK_CODES.DECISION_EXISTS,
  ISSUANCE_READINESS_CHECK_CODES.DECISION_BELONGS_TO_CASE,
  ISSUANCE_READINESS_CHECK_CODES.DECISION_TYPE_ALLOWS_INSTRUMENT,
  ISSUANCE_READINESS_CHECK_CODES.DECISION_FORMALIZED,
  ISSUANCE_READINESS_CHECK_CODES.DECISION_HAS_REASONS,
  ISSUANCE_READINESS_CHECK_CODES.NOTICE_STATUS_SATISFIED,
  ISSUANCE_READINESS_CHECK_CODES.DECISION_NOT_SUPERSEDED,
  ISSUANCE_READINESS_CHECK_CODES.ISSUE_AUTHORITY_ALLOW,
  ISSUANCE_READINESS_CHECK_CODES.ISSUER_AUTHORIZED,
  ISSUANCE_READINESS_CHECK_CODES.OUTCOME_PERMITS_ISSUANCE,
  ISSUANCE_READINESS_CHECK_CODES.PRECEDENT_CONDITIONS_SATISFIED,
  ISSUANCE_READINESS_CHECK_CODES.SIGNATURE_PRESENT,
  ISSUANCE_READINESS_CHECK_CODES.SIGNATURE_VALID,
  ISSUANCE_READINESS_CHECK_CODES.SEAL_PRESENT,
  ISSUANCE_READINESS_CHECK_CODES.SEAL_VALID,
  ISSUANCE_READINESS_CHECK_CODES.TEMPLATE_VERSION_ACTIVE,
  ISSUANCE_READINESS_CHECK_CODES.NUMBERING_RULE_ACTIVE,
  ISSUANCE_READINESS_CHECK_CODES.HOLDER_ESTABLISHED,
  ISSUANCE_READINESS_CHECK_CODES.SCOPE_ESTABLISHED,
  ISSUANCE_READINESS_CHECK_CODES.EFFECTIVE_DATE_ESTABLISHED,
  ISSUANCE_READINESS_CHECK_CODES.EXPIRY_DATE_ESTABLISHED,
  ISSUANCE_READINESS_CHECK_CODES.VERIFICATION_METHOD_AVAILABLE,
  ISSUANCE_READINESS_CHECK_CODES.RECORDS_INFRASTRUCTURE_AVAILABLE,
  ISSUANCE_READINESS_CHECK_CODES.NO_SAFE_HALT,
  ISSUANCE_READINESS_CHECK_CODES.NO_RETAINED_NATIONAL_BLOCK,
] as const;
