export const EXPERIENCE_SEARCH_RESOURCE_TYPES = {
  GOVERNMENT_SERVICE: 'government_service',
  APPLICATION: 'application',
  DOCUMENT: 'document',
  CREDENTIAL: 'credential',
  MESSAGE: 'message',
  BUSINESS: 'business',
  PAYMENT: 'payment',
  CASE: 'case',
  APPLICANT: 'applicant',
  ORGANIZATION: 'organization',
  EVIDENCE_REFERENCE: 'evidence_reference',
  OFFICIAL_INSTRUMENT: 'official_instrument',
} as const;

export type ExperienceSearchResourceType =
  (typeof EXPERIENCE_SEARCH_RESOURCE_TYPES)[keyof typeof EXPERIENCE_SEARCH_RESOURCE_TYPES];

export const CITIZEN_SEARCH_RESOURCE_TYPES: ExperienceSearchResourceType[] = [
  EXPERIENCE_SEARCH_RESOURCE_TYPES.GOVERNMENT_SERVICE,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.APPLICATION,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.DOCUMENT,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.CREDENTIAL,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.MESSAGE,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.BUSINESS,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.PAYMENT,
];

export const OFFICIAL_SEARCH_RESOURCE_TYPES: ExperienceSearchResourceType[] = [
  EXPERIENCE_SEARCH_RESOURCE_TYPES.CASE,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.APPLICATION,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.APPLICANT,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.ORGANIZATION,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.GOVERNMENT_SERVICE,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.EVIDENCE_REFERENCE,
  EXPERIENCE_SEARCH_RESOURCE_TYPES.OFFICIAL_INSTRUMENT,
];

export const RESTRICTED_EVIDENCE_CLASSIFICATIONS = [
  'RESTRICTED',
  'PRIVILEGED',
  'CLASSIFIED',
  'CABINET_CONFIDENTIAL',
] as const;
