export const EXPERIENCE_PERSONAS = {
  CITIZEN: 'CITIZEN',
  RESIDENT: 'RESIDENT',
  BUSINESS: 'BUSINESS',
  INVESTOR: 'INVESTOR',
  AUTHORIZED_REPRESENTATIVE: 'AUTHORIZED_REPRESENTATIVE',
  GOVERNMENT_OFFICIAL: 'GOVERNMENT_OFFICIAL',
  DEPARTMENT_MANAGEMENT: 'DEPARTMENT_MANAGEMENT',
  EXECUTIVE_LEADERSHIP: 'EXECUTIVE_LEADERSHIP',
  PLATFORM_ADMINISTRATION: 'PLATFORM_ADMINISTRATION',
} as const;

export type ExperiencePersona = (typeof EXPERIENCE_PERSONAS)[keyof typeof EXPERIENCE_PERSONAS];

export const CITIZEN_BUSINESS_PERSONAS: ExperiencePersona[] = [
  EXPERIENCE_PERSONAS.CITIZEN,
  EXPERIENCE_PERSONAS.RESIDENT,
  EXPERIENCE_PERSONAS.BUSINESS,
  EXPERIENCE_PERSONAS.INVESTOR,
  EXPERIENCE_PERSONAS.AUTHORIZED_REPRESENTATIVE,
];

export const OFFICIAL_PERSONAS: ExperiencePersona[] = [
  EXPERIENCE_PERSONAS.GOVERNMENT_OFFICIAL,
  EXPERIENCE_PERSONAS.DEPARTMENT_MANAGEMENT,
  EXPERIENCE_PERSONAS.EXECUTIVE_LEADERSHIP,
  EXPERIENCE_PERSONAS.PLATFORM_ADMINISTRATION,
];

export const EXECUTIVE_ROLE_MARKER = 'EXECUTIVE_LEADERSHIP';
export const DEPARTMENT_MANAGEMENT_ROLE_MARKER = 'DEPARTMENT_MANAGEMENT';
