export const PHASE_13D_MODEL_NAMES = [
  'CriticalServiceDefinition',
  'BusinessImpactAssessment',
  'RecoveryObjective',
  'ContinuityDependency',
  'SinglePointOfFailure',
  'ContinuityProcedure',
  'ManualOperationProcedure',
  'ManualOperationAuthorization',
  'ContinuityEvent',
  'ContinuityDecision',
  'BackupDefinition',
  'BackupExecutionRecord',
  'RestoreTest',
  'RecoveryExercise',
  'RecoveryAction',
  'BacklogRecoveryPlan',
  'ManualDigitalReconciliation',
  'ResumptionReadinessAssessment',
  'ResumptionAuthorization',
  'ContinuityCorrectiveAction',
] as const;

export const PHASE_13D_ENUM_NAMES = [
  'ConfigurationConfirmationStatus',
  'CriticalServiceCriticality',
  'CriticalServiceDefinitionStatus',
  'ContinuityScenarioType',
  'ContinuityDependencyType',
  'SinglePointOfFailureStatus',
  'ContinuityProcedureStatus',
  'ManualOperationProcedureStatus',
  'ManualOperationAuthorizationStatus',
  'ContinuityEventStatus',
  'ContinuityOperatingMode',
  'ContinuityDecisionType',
  'BackupTargetType',
  'BackupLocationClass',
  'BackupDefinitionStatus',
  'BackupRecoverabilityStatus',
  'RestoreTestResult',
  'RecoveryExerciseStatus',
  'RecoveryActionStatus',
  'BacklogRecoveryPlanStatus',
  'BacklogPriorityBasis',
  'ManualDigitalReconciliationStatus',
  'ResumptionReadinessStatus',
  'ResumptionAuthorizationStatus',
  'ContinuityCorrectiveActionStatus',
  'ContinuityCorrectiveActionSourceType',
  'BusinessImpactAssessmentStatus',
  'RecoveryObjectiveType',
] as const;
