import { CapabilityMaturityState } from '@prisma/client';

export const PHASE_13A_BOUNDARY_DISCLAIMER =
  'Operational readiness machinery records assessments, conditions, and governance evidence. ' +
  'Authority does not equal activation. Technical completion does not equal production readiness. ' +
  'Production readiness does not equal institutional acceptance. Institutional acceptance does not equal operational activation.';

export const MATURITY_ADVANCEMENT_PATH: CapabilityMaturityState[] = [
  CapabilityMaturityState.CONCEPTUAL,
  CapabilityMaturityState.DESIGNED,
  CapabilityMaturityState.PROTOTYPED,
  CapabilityMaturityState.PILOT_READY,
  CapabilityMaturityState.PILOT_OPERATIONAL,
  CapabilityMaturityState.PRODUCTION_READY,
  CapabilityMaturityState.INSTITUTIONALLY_ACCEPTED,
  CapabilityMaturityState.OPERATIONALLY_ACTIVATED,
];

export const FORBIDDEN_CLIENT_MATURITY_FIELDS = [
  'currentMaturityState',
  'isOperational',
  'isSuspended',
  'isRetired',
  'replacedByCapabilityId',
] as const;

export const FORBIDDEN_CLIENT_READINESS_FIELDS = [
  'overallStatus',
  'assessedAt',
  'assessedByIdentityId',
] as const;

export const FORBIDDEN_CLIENT_DEPENDENCY_FIELDS = ['isReady', 'verificationStatus'] as const;

export const FORBIDDEN_AI_MATURITY_ACTIONS = [
  'ADVANCE_MATURITY',
  'RECORD_INSTITUTIONAL_ACCEPTANCE',
  'RECORD_OPERATIONAL_ACTIVATION',
  'ACCEPT_RESIDUAL_RISK',
] as const;

export const TECHNICAL_COMPLETION_EVIDENCE_TYPES = [
  'CI_PIPELINE_SUCCESS',
  'UNIT_TEST_PASS',
  'INTEGRATION_TEST_PASS',
  'BUILD_SUCCESS',
  'TECHNICAL_COMPLETION',
] as const;

export const VENDOR_CERTIFICATION_EVIDENCE_TYPES = [
  'VENDOR_CERTIFICATION',
  'VENDOR_ATTESTATION',
  'THIRD_PARTY_CERTIFICATION',
] as const;

export const PILOT_SUCCESS_EVIDENCE_TYPES = [
  'PILOT_SUCCESS',
  'PILOT_COMPLETION',
  'PILOT_SIGN_OFF',
] as const;

export const INSTITUTIONAL_ACCEPTANCE_EVIDENCE_TYPES = [
  'INSTITUTIONAL_ACCEPTANCE',
  'INSTITUTIONAL_SIGN_OFF',
  'OFFICEHOLDER_ACCEPTANCE',
] as const;

export const OPERATIONAL_READINESS_REASON_CODES = {
  MATURITY_SKIP_FORBIDDEN: 'MATURITY_SKIP_FORBIDDEN',
  TECHNICAL_COMPLETION_NOT_PRODUCTION_READY: 'TECHNICAL_COMPLETION_NOT_PRODUCTION_READY',
  PRODUCTION_READINESS_NOT_INSTITUTIONAL_ACCEPTANCE: 'PRODUCTION_READINESS_NOT_INSTITUTIONAL_ACCEPTANCE',
  INSTITUTIONAL_ACCEPTANCE_NOT_OPERATIONAL_ACTIVATION:
    'INSTITUTIONAL_ACCEPTANCE_NOT_OPERATIONAL_ACTIVATION',
  PILOT_SUCCESS_NOT_PRODUCTION_AUTHORIZATION: 'PILOT_SUCCESS_NOT_PRODUCTION_AUTHORIZATION',
  CI_SUCCESS_NOT_INSTITUTIONAL_ACCEPTANCE: 'CI_SUCCESS_NOT_INSTITUTIONAL_ACCEPTANCE',
  VENDOR_CERT_NOT_INSTITUTIONAL_ACCEPTANCE: 'VENDOR_CERT_NOT_INSTITUTIONAL_ACCEPTANCE',
  UNRESOLVED_CRITICAL_CONDITION: 'UNRESOLVED_CRITICAL_CONDITION',
  EXTERNAL_DEPENDENCY_FALSELY_CONTROLLED: 'EXTERNAL_DEPENDENCY_FALSELY_CONTROLLED',
  TECH_ADMIN_CANNOT_ACCEPT_INSTITUTIONAL_RISK: 'TECH_ADMIN_CANNOT_ACCEPT_INSTITUTIONAL_RISK',
  AI_CANNOT_ADVANCE_MATURITY: 'AI_CANNOT_ADVANCE_MATURITY',
  CLIENT_CANNOT_SET_MATURITY: 'CLIENT_CANNOT_SET_MATURITY',
  SUSPENDED_CANNOT_APPEAR_OPERATIONAL: 'SUSPENDED_CANNOT_APPEAR_OPERATIONAL',
  RETIRED_CANNOT_REACTIVATE: 'RETIRED_CANNOT_REACTIVATE',
  REVALIDATION_REQUIRED: 'REVALIDATION_REQUIRED',
  EVIDENCE_REQUIRED_FOR_ADVANCEMENT: 'EVIDENCE_REQUIRED_FOR_ADVANCEMENT',
  MANDATORY_ACTIVATION_CONDITIONS_UNSATISFIED: 'MANDATORY_ACTIVATION_CONDITIONS_UNSATISFIED',
  READY_WITH_CONDITIONS_REQUIRES_MEASURABLE: 'READY_WITH_CONDITIONS_REQUIRES_MEASURABLE',
  ACTIVATION_NOT_PRODUCTION: 'ACTIVATION_NOT_PRODUCTION',
} as const;

export const ALL_PRODUCTION_READINESS_DOMAINS = [
  'AUTHORITY',
  'GOVERNANCE',
  'FUNCTIONAL',
  'WORKFLOW',
  'DATA',
  'RECORDS',
  'IDENTITY',
  'SECURITY',
  'PRIVACY',
  'CRYPTOGRAPHY',
  'INTEGRATION',
  'AI_GOVERNANCE',
  'PERFORMANCE',
  'CAPACITY',
  'CONTINUITY',
  'BACKUP_RECOVERY',
  'SUPPORT',
  'WORKFORCE',
  'TRAINING',
  'ACCESSIBILITY',
  'MONITORING',
  'INCIDENT_RESPONSE',
  'CHANGE_MANAGEMENT',
  'VENDOR',
  'EXIT_PORTABILITY',
] as const;

export const AI_ACTOR_ROLE_MARKER = 'AI_ACTOR';
export const AI_ACTOR_IDENTITY_PREFIX = 'ai-actor-';
