export const CASE_MODEL_NAMES = [
  'Case',
  'CaseStatusHistory',
  'CaseRelationship',
] as const;

export const CASE_STATUSES = [
  'RECEIVED',
  'IDENTITY_PENDING',
  'COMPLETENESS_REVIEW',
  'INCOMPLETE',
  'COMPLETE',
  'SUBSTANTIVE_REVIEW',
  'EXTERNAL_REFERRAL',
  'PROFESSIONAL_REVIEW',
  'INSPECTION',
  'DECISION_PENDING',
  'DECIDED',
  'ISSUED',
  'UNDER_CONTINUING_OVERSIGHT',
  'UNDER_COMPLAINT_OR_APPEAL',
  'SUSPENDED',
  'REVOKED',
  'WITHDRAWN',
  'CLOSED',
  'ARCHIVED',
] as const;

export const CASE_LEGAL_STATUSES = [
  'NONE',
  'PENDING',
  'UNRESOLVED',
  'EXTERNAL_STATUS_PENDING',
] as const;

export const CASE_RELATIONSHIP_TYPES = [
  'RELATED_CASE',
  'PARENT_CHILD',
  'RELATED_SERVICE_MATTER',
  'ORGANIZATION_PROJECT_REFERENCE',
] as const;

export const FORBIDDEN_CASE_LEGAL_STATUS_VALUES = ['APPROVED', 'REFUSED'] as const;
