export const CLINICAL_RESEARCH_FOUNDATION_MODEL_NAMES = [
  'ClinicalTrialPhaseReference',
  'ClinicalTrialConditionReference',
  'ClinicalTrialInterventionReference',
  'ClinicalTrialSponsor',
  'ClinicalTrial',
  'ClinicalTrialVersion',
  'ClinicalTrialProtocol',
  'ClinicalTrialProtocolVersion',
  'ClinicalTrialSite',
  'ClinicalTrialInvestigator',
  'ClinicalTrialPrincipalInvestigator',
  'ResearchEthicsApproval',
  'ResearchEthicsApprovalVersion',
  'ClinicalRegulatoryApproval',
  'ClinicalRegulatoryStatus',
  'ClinicalTrialExternalRegistryReference',
  'ClinicalResearchParticipantProfile',
  'ClinicalTrialEligibilityCriterion',
  'ClinicalTrialInterest',
  'ClinicalTrialScreening',
  'ClinicalTrialScreeningReview',
  'ClinicalTrialEligibilityAssessment',
  'ClinicalTrialEligibilityEvidence',
  'ClinicalTrialConsent',
  'ClinicalTrialConsentVersion',
  'ClinicalTrialConsentSignature',
  'ClinicalTrialEnrollment',
  'ClinicalTrialEnrollmentStatusHistory',
  'ClinicalTrialWithdrawal',
] as const;

export const CLINICAL_RESEARCH_FOUNDATION_ENUM_NAMES = [
  'ClinicalResearchDataClassification',
  'ClinicalTrialListingLifecycleStatus',
  'ClinicalTrialRecruitmentStatus',
  'PreliminaryTrialMatchOutcome',
  'ClinicalTrialEligibilityAssessmentOutcome',
  'ClinicalTrialScreeningReviewOutcome',
  'ResearchEthicsApprovalStatus',
  'ClinicalRegulatoryApprovalStatus',
  'ClinicalTrialInterestStatus',
  'ClinicalTrialScreeningStatus',
  'ClinicalTrialConsentSignatureStatus',
  'ClinicalTrialEnrollmentStatus',
  'ClinicalTrialWithdrawalReasonCategory',
  'ClinicalResearchActorPersona',
] as const;

export const FORBIDDEN_SPONSOR_ETHICS_RECORD_FIELDS = [
  'status',
  'recordedByPersona',
  'approvedAt',
] as const;
