export const SOCIAL_PROTECTION_FOUNDATION_MODEL_NAMES = [
  'BenefitCategory',
  'BenefitProgram',
  'BenefitProgramVersion',
  'BenefitApplicantProfile',
  'HouseholdRecord',
  'HouseholdMember',
  'HouseholdRelationship',
  'BenefitApplicationProfile',
  'BenefitEligibilityAssessment',
  'EligibilityFactorReference',
  'EligibilityEvidenceReference',
  'BenefitAward',
  'BenefitAwardVersion',
  'BenefitEntitlementPeriod',
  'BenefitPaymentScheduleReference',
  'BenefitDisbursementReference',
  'BenefitReview',
  'BenefitRenewal',
  'BenefitSuspension',
  'BenefitTermination',
  'BenefitStatusHistory',
  'HouseholdIncomeDeclaration',
  'HouseholdAssetDeclaration',
  'ExternalEligibilityDeterminationReference',
  'SocialSupportCaseReference',
  'SocialProtectionAppealReference',
] as const;

export const SOCIAL_PROTECTION_FOUNDATION_ENUM_NAMES = [
  'SocialProtectionDataClassification',
  'SocialProtectionActorPersona',
  'BenefitCategoryKind',
  'BenefitProgramStatus',
  'BenefitProgramVersionStatus',
  'BenefitApplicantProfileStatus',
  'HouseholdRecordStatus',
  'HouseholdMemberRole',
  'HouseholdRelationshipStatus',
  'BenefitApplicationProfileStatus',
  'BenefitEligibilityAssessmentStatus',
  'BenefitEligibilityOutcome',
  'BenefitAwardLifecycleStatus',
  'BenefitReviewKind',
  'BenefitRenewalStatus',
  'BenefitSuspensionStatus',
  'BenefitTerminationStatus',
  'BenefitStatusHistorySubjectKind',
  'HouseholdDeclarationStatus',
  'ExternalEligibilityDeterminationRecordedBy',
  'SocialProtectionAppealReferenceStatus',
] as const;
