export const SERVICE_PACK_DEPLOYMENT_BOUNDARY_DISCLAIMERS = {
  DEPLOYMENT_NOT_ACTIVATION: 'Deployment != Activation',
  ROLLBACK_NO_ERASE: 'Rollback cannot erase official records or historical decisions',
  ACTIVE_NO_SILENT_OVERWRITE: 'Active service configuration cannot be silently overwritten',
  SUPERSESSION_PRESERVES_HISTORY: 'Supersession leaves historical service versions intact',
} as const;

export const SERVICE_PACK_DEPLOYMENT_REASON_CODES = {
  VERSION_NOT_COMPILED: 'SERVICE_PACK_VERSION_NOT_COMPILED',
  VERSION_NOT_ACCEPTED: 'SERVICE_PACK_VERSION_NOT_ACCEPTED',
  DEPLOYMENT_NOT_READY: 'SERVICE_PACK_DEPLOYMENT_NOT_READY',
  DEPLOYMENT_NOT_DEPLOYED: 'SERVICE_PACK_DEPLOYMENT_NOT_DEPLOYED',
  ALREADY_DEPLOYED: 'SERVICE_PACK_ALREADY_DEPLOYED',
  ALREADY_ACTIVE: 'SERVICE_PACK_ALREADY_ACTIVE',
  ALREADY_ROLLED_BACK: 'SERVICE_PACK_ALREADY_ROLLED_BACK',
  ACTIVE_SERVICE_SILENT_OVERWRITE: 'ACTIVE_SERVICE_CANNOT_BE_SILENTLY_OVERWRITTEN',
  ROLLBACK_ERASES_OFFICIAL_RECORDS: 'ROLLBACK_CANNOT_DELETE_OFFICIAL_RECORDS',
  SUSPENDED_AUTHORITY_BLOCKS: 'SUSPENDED_AUTHORITY_BLOCKS_ACTIVATION',
  UNRESOLVED_DEPENDENCY: 'UNRESOLVED_DEPENDENCY_BLOCKS_ACTIVATION',
  INTEGRATION_ACCEPTANCE_REQUIRED: 'INTEGRATION_ACCEPTANCE_REQUIREMENT_NOT_MET',
  ACTIVATION_DELEGATION_REQUIRED: 'ACTIVATION_MUST_DELEGATE_TO_GOVERNED_DOMAIN_SERVICES',
  SUPERSESSION_REQUIRED: 'ACTIVE_SERVICE_REQUIRES_SUPERSESSION_SEMANTICS',
  MANIFEST_INVALID: 'SERVICE_PACK_MANIFEST_INVALID',
  FINGERPRINT_MISMATCH: 'SERVICE_PACK_CONFIGURATION_FINGERPRINT_MISMATCH',
} as const;

export const SERVICE_PACK_DEPLOYMENT_MODEL_NAMES = [
  'ServicePack',
  'ServicePackVersion',
  'ServicePackDeployment',
  'ServicePackDeploymentBinding',
  'ServicePackDeploymentAuditRecord',
] as const;

export const SERVICE_PACK_VERSION_STATUSES = ['COMPILED', 'ACCEPTED'] as const;

export const SERVICE_PACK_DEPLOYMENT_STATUSES = [
  'DEPLOYMENT_READY',
  'DEPLOYED',
  'OPERATIONALLY_INACTIVE',
  'ACTIVE',
  'SUSPENDED',
  'ROLLED_BACK',
  'SUPERSEDED',
] as const;

export const SERVICE_PACK_BINDING_DOMAINS = [
  'SERVICE_CATALOG',
  'FORMS',
  'WORKFLOWS',
  'SERVICE_AUTHORITY_MAPPINGS',
  'FEE_METADATA',
  'EVIDENCE_REQUIREMENTS',
  'OUTPUT_METADATA',
  'REDRESS_ROUTES',
  'COMMUNICATION_CONFIGURATION',
  'INTEGRATION_REFERENCES',
  'DASHBOARD_CONFIGURATION',
] as const;

export const SERVICE_PACK_AUDIT_EVENT_TYPES = [
  'VERSION_ACCEPTED',
  'DEPLOYMENT_READY',
  'DEPLOYED',
  'ACTIVATION_REQUESTED',
  'ACTIVATION_BLOCKED',
  'ACTIVATED',
  'SUSPENDED',
  'ROLLBACK_INITIATED',
  'ROLLBACK_COMPLETED',
  'SUPERSEDED',
  'FINGERPRINT_RECORDED',
] as const;
