import { APPLICANT_CATEGORIES } from '../service-catalog-schema.constants';

/** Marker required on every service-pack manifest and template. */
export const SERVICE_PACK_NON_PRODUCTION_LABEL = 'NON_PRODUCTION' as const;

/** Secondary marker for canonical templates. */
export const SERVICE_PACK_TEMPLATE_ONLY_LABEL = 'TEMPLATE_ONLY' as const;

export const SERVICE_PACK_SCHEMA_VERSION = '1.0.0';

export const SERVICE_PACK_ALLOWED_LABELS = [
  SERVICE_PACK_NON_PRODUCTION_LABEL,
  SERVICE_PACK_TEMPLATE_ONLY_LABEL,
] as const;

/** Pack manifests may only declare draft / non-operational deployment intent. */
export const SERVICE_PACK_ALLOWED_MATURITY_STATUSES = ['DRAFT'] as const;

export const SERVICE_PACK_ALLOWED_PUBLIC_AVAILABILITY = [
  'HIDDEN',
  'UNDER_DEVELOPMENT',
  'INFORMATION_ONLY',
] as const;

export const SERVICE_PACK_GOVERNANCE_BYPASS_FIELDS = [
  'maturityStatus',
  'publicAvailability',
  'skipInstitutionalAcceptance',
  'skipOperationalActivation',
  'forceActivation',
  'autoActivate',
  'bypassActivationGovernance',
  'directActivation',
  'activationOverride',
] as const;

export const SERVICE_PACK_FORBIDDEN_MATURITY_VALUES = [
  'ACTIVE',
  'ACCEPTED',
  'TESTED',
  'CONFIGURED',
  'APPROVED',
  'RECOGNIZED',
] as const;

export const SERVICE_PACK_FORBIDDEN_AVAILABILITY_VALUES = [
  'ACTIVE',
  'PRE_APPLICATION',
  'PILOT_ONLY',
] as const;

export const SERVICE_PACK_APPLICANT_CATEGORIES = APPLICANT_CATEGORIES;

export const SERVICE_PACK_WORKFLOW_STEP_TYPES = [
  'INTAKE',
  'COMPLETENESS_REVIEW',
  'SUBSTANTIVE_REVIEW',
  'EXTERNAL_REFERRAL',
  'INTERNAL_COORDINATION',
  'PROFESSIONAL_REVIEW',
  'DECISION_GATE',
  'ISSUANCE_GATE',
  'PARALLEL_JOIN',
] as const;

export const SERVICE_PACK_AUTHORITY_ACTION_TYPES = [
  'RETRIEVE',
  'SUMMARIZE',
  'PREPARE',
  'REVIEW',
  'VERIFY',
  'APPROVE',
  'DECIDE',
  'SIGN',
  'ISSUE',
  'INSPECT',
  'ENFORCE',
] as const;

/**
 * Canonical NON_PRODUCTION authority function codes referenced by templates.
 * These are authoring placeholders — not verified legal authority assignments.
 */
export const SERVICE_PACK_AUTHORITY_FUNCTION_REGISTRY = [
  'TEMPLATE-AUTH-REGISTRATION-INTAKE',
  'TEMPLATE-AUTH-REGISTRATION-VERIFY',
  'TEMPLATE-AUTH-LICENSE-REVIEW',
  'TEMPLATE-AUTH-LICENSE-ISSUANCE',
  'TEMPLATE-AUTH-RENEWAL-VERIFY',
  'TEMPLATE-AUTH-RENEWAL-ISSUANCE',
  'TEMPLATE-AUTH-INSPECTION-SCHEDULE',
  'TEMPLATE-AUTH-INSPECTION-VERIFY',
  'TEMPLATE-AUTH-EXTERNAL-REFERRAL',
  'TEMPLATE-AUTH-EXTERNAL-DETERMINATION',
  'TEMPLATE-AUTH-PROFESSIONAL-REVIEW',
  'TEMPLATE-AUTH-MULTI-DEPT-COORD',
  'TEMPLATE-AUTH-MULTI-DEPT-DECIDE',
  'TEMPLATE-AUTH-BENEFIT-INTAKE',
  'TEMPLATE-AUTH-BENEFIT-DETERMINE',
  'TEMPLATE-AUTH-INVESTOR-APPROVAL',
  'TEMPLATE-AUTH-INVESTOR-ISSUANCE',
  'TEMPLATE-AUTH-HIGH-SENSITIVITY-REVIEW',
  'TEMPLATE-AUTH-HIGH-SENSITIVITY-APPROVE',
  'TEMPLATE-AUTH-HIGH-SENSITIVITY-ISSUE',
  'TEMPLATE-AUTH-CIVIL-EVENT-INTAKE',
  'TEMPLATE-AUTH-CIVIL-EVENT-REGISTER',
  'TEMPLATE-AUTH-CIVIL-CERTIFICATE-ISSUE',
  'TEMPLATE-AUTH-CIVIL-RECORD-AMEND',
  'TEMPLATE-AUTH-CIVIL-CORRECTION-APPROVE',
  'TEMPLATE-AUTH-CIVIL-VERIFICATION-ATTEST',
  'TEMPLATE-AUTH-CORPORATE-REGISTRY-INTAKE',
  'TEMPLATE-AUTH-CORPORATE-REGISTRY-REVIEW',
  'TEMPLATE-AUTH-CORPORATE-REGISTRY-DECIDE',
  'TEMPLATE-AUTH-CORPORATE-REGISTRY-ISSUE',
  'TEMPLATE-AUTH-CORPORATE-REGISTRY-VERIFY',
  'TEMPLATE-AUTH-IMMIGRATION-INTAKE',
  'TEMPLATE-AUTH-IMMIGRATION-REVIEW',
  'TEMPLATE-AUTH-IMMIGRATION-DECIDE',
  'TEMPLATE-AUTH-IMMIGRATION-ISSUE',
  'TEMPLATE-AUTH-IMMIGRATION-BIOMETRIC',
  'TEMPLATE-AUTH-IMMIGRATION-INTERVIEW',
  'TEMPLATE-AUTH-REVENUE-INTAKE',
  'TEMPLATE-AUTH-REVENUE-VERIFY',
  'TEMPLATE-AUTH-REVENUE-RETURN-REVIEW',
  'TEMPLATE-AUTH-REVENUE-ASSESSMENT-ISSUE',
  'TEMPLATE-AUTH-REVENUE-REFUND-AUTHORIZE',
  'TEMPLATE-AUTH-REVENUE-OBJECTION-DECIDE',
  'TEMPLATE-AUTH-REVENUE-CLEARANCE-ISSUE',
  'TEMPLATE-AUTH-REVENUE-PAYMENT-PLAN-APPROVE',
  'TEMPLATE-AUTH-CUSTOMS-INTAKE',
  'TEMPLATE-AUTH-CUSTOMS-VERIFY',
  'TEMPLATE-AUTH-CUSTOMS-DECLARATION-REVIEW',
  'TEMPLATE-AUTH-CUSTOMS-RELEASE-AUTHORIZE',
  'TEMPLATE-AUTH-CUSTOMS-PERMIT-DECIDE',
  'TEMPLATE-AUTH-CUSTOMS-ASSESSMENT-ISSUE',
  'TEMPLATE-AUTH-CUSTOMS-REFUND-ADJUST',
  'TEMPLATE-AUTH-CUSTOMS-APPEAL-DECIDE',
  'TEMPLATE-AUTH-PROPERTY-INTAKE',
  'TEMPLATE-AUTH-PROPERTY-VERIFY',
  'TEMPLATE-AUTH-PROPERTY-TITLE-REVIEW',
  'TEMPLATE-AUTH-PROPERTY-TRANSFER-DECIDE',
  'TEMPLATE-AUTH-PROPERTY-REGISTER-TRANSFER',
  'TEMPLATE-AUTH-PROPERTY-SURVEY-VERIFY',
  'TEMPLATE-AUTH-PROPERTY-ENCUMBRANCE-DECIDE',
  'TEMPLATE-AUTH-PROPERTY-CERTIFICATE-ISSUE',
  'TEMPLATE-AUTH-PROPERTY-EXTERNAL-REGISTRY-CHECK',
  'TEMPLATE-AUTH-PROPERTY-VALUATION-DECIDE',
  'TEMPLATE-AUTH-PROPERTY-APPEAL-DECIDE',
  'TEMPLATE-AUTH-PLANNING-INTAKE',
  'TEMPLATE-AUTH-PLANNING-REVIEW',
  'TEMPLATE-AUTH-ZONING-DETERMINE',
  'TEMPLATE-AUTH-PLANNING-PERMIT-ISSUE',
  'TEMPLATE-AUTH-PLANNING-OCCUPANCY-ISSUE',
  'TEMPLATE-AUTH-PLANNING-APPEAL-DECIDE',
  'TEMPLATE-AUTH-LABOUR-INTAKE',
  'TEMPLATE-AUTH-LABOUR-REVIEW',
  'TEMPLATE-AUTH-LABOUR-DECIDE',
  'TEMPLATE-AUTH-LABOUR-ISSUE',
  'TEMPLATE-AUTH-LABOUR-INSPECT',
  'TEMPLATE-AUTH-LABOUR-ENFORCE',
  'TEMPLATE-AUTH-LABOUR-COMPLAINT-DECIDE',
  'TEMPLATE-AUTH-LABOUR-QUALIFICATION-VERIFY',
  'TEMPLATE-AUTH-LABOUR-IMMIGRATION-COORD',
  'TEMPLATE-AUTH-TRANSPORT-INTAKE',
  'TEMPLATE-AUTH-TRANSPORT-REVIEW',
  'TEMPLATE-AUTH-TRANSPORT-LICENSE-DECIDE',
  'TEMPLATE-AUTH-TRANSPORT-LICENSE-ISSUE',
  'TEMPLATE-AUTH-TRANSPORT-REGISTRATION-DECIDE',
  'TEMPLATE-AUTH-TRANSPORT-INSPECTION-VERIFY',
  'TEMPLATE-AUTH-TRANSPORT-OPERATOR-LICENSE',
  'TEMPLATE-AUTH-TRANSPORT-TRANSFER-DECIDE',
  'TEMPLATE-AUTH-TRANSPORT-APPEAL-DECIDE',
  'TEMPLATE-AUTH-PUBLIC-SAFETY-INTAKE',
  'TEMPLATE-AUTH-PUBLIC-SAFETY-VERIFY',
  'TEMPLATE-AUTH-PUBLIC-SAFETY-ASSISTANCE-REVIEW',
  'TEMPLATE-AUTH-PUBLIC-SAFETY-INSPECTION-SCHEDULE',
  'TEMPLATE-AUTH-PUBLIC-SAFETY-INSPECTION-VERIFY',
  'TEMPLATE-AUTH-PUBLIC-SAFETY-NOTICE-APPROVE',
  'TEMPLATE-AUTH-PUBLIC-SAFETY-NOTICE-PUBLISH',
  'TEMPLATE-AUTH-PUBLIC-SAFETY-RECOVERY-DETERMINE',
  'TEMPLATE-AUTH-PUBLIC-SAFETY-APPEAL-DECIDE',
  'TEMPLATE-AUTH-PUBLIC-SAFETY-EXTERNAL-COORD',
  'TEMPLATE-AUTH-PUBLIC-SAFETY-REFERRAL',
] as const;

export const SERVICE_PACK_HIGH_RISK_CHANGE_TYPES = [
  'SERVICE_REMOVED',
  'NEW_AUTHORITY_FUNCTION',
  'DECISION_ACTOR_CHANGE',
  'EVIDENCE_REQUIREMENT_REMOVED',
  'REVIEW_GATE_REDUCED',
  'NEW_EXTERNAL_INTEGRATION',
  'NEW_SENSITIVE_DATA_FIELD',
  'RETENTION_BEHAVIOR_CHANGED',
  'FEE_CHANGED',
  'ELIGIBILITY_RULE_CHANGED',
  'WORKFLOW_STAGE_REMOVED',
  'SLA_RELAXED',
  'OUTPUT_DEFINITION_CHANGED',
] as const;

export type ServicePackHighRiskChangeType = (typeof SERVICE_PACK_HIGH_RISK_CHANGE_TYPES)[number];
