export const SERVICE_PACK_RUNTIME_COMPILER_REASON_CODES = {
  VERSION_NOT_FOUND: 'SERVICE_PACK_COMPILE_VERSION_NOT_FOUND',
  AUTHORING_MANIFEST_MISSING: 'SERVICE_PACK_COMPILE_AUTHORING_MANIFEST_MISSING',
  AUTHORING_MANIFEST_INVALID: 'SERVICE_PACK_COMPILE_AUTHORING_MANIFEST_INVALID',
  VALIDATION_FAILED: 'SERVICE_PACK_COMPILE_VALIDATION_FAILED',
  INSTITUTION_NOT_FOUND: 'SERVICE_PACK_COMPILE_INSTITUTION_NOT_FOUND',
  DEPARTMENT_NOT_FOUND: 'SERVICE_PACK_COMPILE_DEPARTMENT_NOT_FOUND',
  SERVICE_FAMILY_NOT_FOUND: 'SERVICE_PACK_COMPILE_SERVICE_FAMILY_NOT_FOUND',
  AUTHORITY_NOT_RESOLVABLE: 'SERVICE_PACK_COMPILE_AUTHORITY_NOT_RESOLVABLE',
  GOVERNING_SOURCE_NOT_EFFECTIVE: 'SERVICE_PACK_COMPILE_GOVERNING_SOURCE_NOT_EFFECTIVE',
  VERSION_IMMUTABLE: 'SERVICE_PACK_COMPILE_VERSION_IMMUTABLE',
  ALREADY_COMPILED: 'SERVICE_PACK_COMPILE_ALREADY_MATERIALIZED',
} as const;

export const SERVICE_PACK_RUNTIME_COMPILER_MARKER = 'NON_PRODUCTION-S15-COMPILE';
