export const ABSEZ_S18F_SCHEMA_MODELS = [
  'BondedWarehouseReference',
  'FreeZoneCustomsCase',
  'FreeZoneBondedWarehouseLink',
  'FreeZoneDutyReliefRequest',
  'FreeZonePortCustomsCoordination',
  'FreeZoneCustomsExternalDetermination',
  'ImmigrationProgramConfiguration',
  'InvestorResidencyProgramApplication',
  'InvestorResidencyDueDiligenceReference',
  'ZoneLandLeaseRecord',
  'ZoneLandConcessionRecord',
  'ZoneLandOccupancyUseRelationship',
  'InvestorRelationsProfile',
  'InvestorInquiryRecord',
  'InvestorInquiryCaseLink',
  'InvestorCaseManagerAssignment',
  'InvestorInquiryStatusHistory',
  'AbsezArticle9ServicePathState',
] as const;
