export const TRANSPORTATION_FOUNDATION_MODEL_NAMES = [
  'TransportationRegistryEntry',
  'DriverProfile',
  'DriverLicenseApplicationProfile',
  'DriverLicenseRecord',
  'DriverLicenseClass',
  'DriverLicenseEndorsement',
  'DriverQualification',
  'DriverTestRecord',
  'DriverMedicalRequirementReference',
  'VehicleRecord',
  'VehicleIdentifier',
  'VehicleRegistration',
  'VehicleOwnershipRecord',
  'VehicleOwnershipHistory',
  'VehicleInspection',
  'VehicleRoadworthinessRecord',
  'VehicleTransfer',
  'VehicleRestriction',
  'VehicleComplianceRecord',
  'CommercialVehiclePermit',
  'TransportOperatorRecord',
  'TransportOperatorLicense',
  'FleetRecord',
  'FleetVehicle',
  'TransportPermit',
  'TransportationStatusHistory',
] as const;

export const TRANSPORTATION_FOUNDATION_ENUM_NAMES = [
  'TransportationDataClassification',
  'TransportationRegistryLifecycleStatus',
  'TransportationApplicationProfileStatus',
  'DriverLicenseLifecycleStatus',
  'VehicleIdentifierType',
  'VehicleIdentifierStatus',
  'VehicleOwnershipPartyType',
  'VehicleOwnershipRecordStatus',
  'TransportationActorPersona',
  'DriverTestRecordOutcome',
  'TransportationProfessionalDeterminationStatus',
  'FleetVehicleLinkStatus',
  'TransportPermitLifecycleStatus',
  'TransportationRegistryEntryKind',
  'TransportationRegistrySubjectStatus',
] as const;
