export const EDUCATION_FOUNDATION_MODEL_NAMES = [
  'EducationConfiguration',
  'EducationInstitution',
  'EducationInstitutionRegistration',
  'EducationInstitutionLicense',
  'EducationInstitutionAccreditation',
  'EducationInstitutionStatusHistory',
  'StudentEducationProfile',
  'GuardianEducationRelationship',
  'StudentInstitutionRelationship',
  'EducationAdmissionApplicationProfile',
  'EnrollmentRecord',
  'EnrollmentHistory',
  'EducationProgram',
  'EducationProgramVersion',
  'CourseReference',
  'QualificationReference',
  'AcademicRecord',
  'TranscriptRecord',
  'TranscriptRecordCorrectionHistory',
  'CertificateRecord',
  'AcademicCredential',
  'ScholarshipProgramReference',
  'ScholarshipApplicationProfile',
  'EducationGrantReference',
  'StudentSupportProgramReference',
  'EducatorProfileReference',
  'EducatorLicenseRecord',
  'ProfessionalEducationQualificationReference',
  'EducationInspectionReference',
  'EducationComplianceReference',
  'EducationExternalDependency',
] as const;

export const EDUCATION_FOUNDATION_ENUM_NAMES = [
  'EducationDataClassification',
  'EducationActorPersona',
  'EducationInstitutionKind',
  'EducationInstitutionOperationalStatus',
  'EducationInstitutionRegistrationStatus',
  'EducationInstitutionLicenseStatus',
  'EducationInstitutionAccreditationStatus',
  'GuardianEducationRelationshipKind',
  'GuardianEducationRelationshipStatus',
  'StudentInstitutionRelationshipStatus',
  'EducationAdmissionApplicationProfileStatus',
  'EnrollmentRecordStatus',
  'EducationProgramStatus',
  'AcademicRecordVerificationStatus',
  'AcademicCredentialLifecycleStatus',
  'ScholarshipApplicationProfileStatus',
  'EducatorLicenseRecordStatus',
  'EducationExternalDependencyType',
  'EducationExternalDependencyRecordedBy',
] as const;

export const PUBLIC_EDUCATION_VERIFICATION_FORBIDDEN_RESPONSE_KEYS = [
  'grades',
  'transcript',
  'transcriptContent',
  'gpa',
  'assessmentResults',
  'disciplinaryRecords',
  'guardianIdentityId',
  'studentIdentityId',
  'fullAcademicRecord',
] as const;

export const FORBIDDEN_CLIENT_ACADEMIC_CREDENTIAL_FIELDS = [
  'lifecycleStatus',
  'governmentDecisionId',
  'officialInstrumentId',
  'issuedAt',
] as const;
