export const PHASE_13F_MODEL_NAMES = [
  'OperationalRoleRequirement',
  'TrainingRequirement',
  'OperatorReadinessProfile',
  'OperatorQualification',
  'OperatorCompetencyAssessment',
  'TrainingCompletion',
  'PracticalAssessment',
  'AuthorityBoundaryAssessment',
  'SecurityPrivacyAssessment',
  'ContinuityCompetencyAssessment',
  'SupportCoveragePlan',
  'SupportAssignment',
  'OnCallAssignment',
  'SuccessionAssignment',
  'DepartmentReadinessAssessment',
  'StaffingReadinessAssessment',
  'QualificationExpiryEvent',
  'OperatorAccessReview',
] as const;

export const PHASE_13F_ENUM_NAMES = [
  'OperatorQualificationStatus',
  'DepartmentReadinessStatus',
  'StaffingReadinessStatus',
  'OperationalRoleRequirementStatus',
  'CompetencyAssessmentOutcome',
  'TrainingCompletionStatus',
  'OperatorAccessReviewTrigger',
  'OperatorAccessReviewStatus',
  'QualificationExpiryEventType',
  'SupportCoveragePlanStatus',
  'SupportTier',
  'OnCallAssignmentStatus',
  'SuccessionAssignmentStatus',
] as const;
