export const NON_PRODUCTION_PHASE_13G_FIXTURE_MARKER = 'NON_PRODUCTION_PHASE_13G_TEST_ONLY';

export const PRODUCTION_READINESS_BOUNDARY_DISCLAIMER =
  'Institutional acceptance, residual-risk acceptance, and production activation are distinct institutional controls. Technical readiness, passed tests, vendor delivery, payment milestones, and training completion do not constitute institutional acceptance or production activation.';

export const FORBIDDEN_CLIENT_ACCEPTANCE_FIELDS = [
  'institutionallyAccepted',
  'frozenAt',
  'submittedForFinalAcceptanceAt',
  'acceptanceDecision',
  'residualRiskAccepted',
  'productionActivated',
  'operationallyAvailable',
] as const;

export const FORBIDDEN_ACCEPTANCE_BASIS_TYPES = [
  'VENDOR_DELIVERY',
  'PAYMENT_MILESTONE',
  'TRAINING_COMPLETION',
  'PASSED_TESTS',
  'TECHNICAL_PRODUCTION_ACCEPTANCE',
  'DEVELOPER_SELF_ACCEPTANCE',
] as const;

export const INSTITUTIONAL_ACCEPTANCE_LEVELS = ['INSTITUTIONAL', 'OPERATIONAL_ACTIVATION'] as const;

export const TECHNICAL_ACCEPTANCE_LEVELS = [
  'RECEIPT',
  'ADMINISTRATIVE_COMPLETENESS',
  'DISCOVERY',
  'DESIGN',
  'PROTOTYPE',
  'TEST',
  'PILOT',
  'TECHNICAL_PRODUCTION',
] as const;

export const ACCEPTANCE_LEVEL_ORDER: Record<string, number> = {
  RECEIPT: 1,
  ADMINISTRATIVE_COMPLETENESS: 2,
  DISCOVERY: 3,
  DESIGN: 4,
  PROTOTYPE: 5,
  TEST: 6,
  PILOT: 7,
  TECHNICAL_PRODUCTION: 8,
  OPERATIONAL: 9,
  DEPARTMENTAL: 10,
  WORKFLOW: 11,
  INTEGRATION: 12,
  AI_AGENT: 13,
  ISSUANCE: 14,
  INSTITUTIONAL: 15,
  OPERATIONAL_ACTIVATION: 16,
  REVALIDATION: 17,
};

export const ACCEPTANCE_REVIEW_CLASSES = [
  'INSTITUTIONAL',
  'OPERATIONAL',
  'TECHNICAL',
  'SECURITY',
  'PRIVACY',
  'RECORDS',
  'CONTINUITY',
  'LEGAL',
  'PROFESSIONAL',
  'INTEGRATION',
  'AI_GOVERNANCE',
  'ACCESSIBILITY',
  'FINANCIAL',
  'OTHER_CONFIGURED',
] as const;

export const PRODUCTION_ACTIVATION_APPROVED_OUTCOMES = [
  'APPROVED',
  'APPROVED_WITH_RESTRICTIONS',
] as const;
export const PHASE_13F_BOUNDARY_DISCLAIMER =
  'Attendance != Competence. Course Completion != Qualification. System Role != Appointment. Technical Permission != Authority. Staff Assigned != Staff Available. Named Owner != Operational Coverage.';

export const OPERATOR_QUALIFICATION_STATUSES = [
  'QUALIFIED',
  'QUALIFIED_WITH_CONDITIONS',
  'NOT_QUALIFIED',
  'SUSPENDED',
  'EXPIRED',
  'WITHDRAWN',
] as const;

export const DEPARTMENT_READINESS_STATUSES = [
  'NOT_READY',
  'PARTIALLY_READY',
  'READY_WITH_CONDITIONS',
  'READY',
  'SUSPENDED',
] as const;

export const QUALIFIED_STATUSES = ['QUALIFIED', 'QUALIFIED_WITH_CONDITIONS'] as const;

export const FORBIDDEN_CLIENT_QUALIFICATION_FIELDS = [
  'status',
  'isAiAssessed',
  'effectiveFrom',
  'effectiveUntil',
  'accessRetained',
] as const;

export const FORBIDDEN_CLIENT_READINESS_FIELDS = [
  'status',
  'isInstitutionalAcceptance',
  'selfActivated',
  'supportCoverageGapDetected',
  'staffingShortageDetected',
] as const;

export const FORBIDDEN_CLIENT_SUPPORT_FIELDS = [
  'isTwentyFourSeven',
  'contactsRestricted',
] as const;

export const AI_ACTOR_ROLE_MARKER = 'AI_ASSISTANCE';
export const AI_ACTOR_IDENTITY_PREFIX = 'ai-assistant:';

export const PRODUCTION_READINESS_REASON_CODES = {
  ATTENDANCE_NOT_COMPETENCE: 'ATTENDANCE_NOT_COMPETENCE',
  COURSE_COMPLETION_NOT_QUALIFICATION: 'COURSE_COMPLETION_NOT_QUALIFICATION',
  SYSTEM_ROLE_NOT_APPOINTMENT: 'SYSTEM_ROLE_NOT_APPOINTMENT',
  TECHNICAL_PERMISSION_NOT_AUTHORITY: 'TECHNICAL_PERMISSION_NOT_AUTHORITY',
  STAFF_ASSIGNED_NOT_AVAILABLE: 'STAFF_ASSIGNED_NOT_AVAILABLE',
  NAMED_OWNER_NOT_COVERAGE: 'NAMED_OWNER_NOT_COVERAGE',
  AI_CANNOT_QUALIFY_OPERATOR: 'AI_CANNOT_QUALIFY_OPERATOR',
  TRAINING_PROVIDER_CANNOT_SELF_ASSIGN_AUTHORITY: 'TRAINING_PROVIDER_CANNOT_SELF_ASSIGN_AUTHORITY',
  QUALIFICATION_EXPIRED: 'QUALIFICATION_EXPIRED',
  QUALIFICATION_SUSPENDED: 'QUALIFICATION_SUSPENDED',
  QUALIFICATION_NOT_QUALIFIED: 'QUALIFICATION_NOT_QUALIFIED',
  QUALIFICATION_SCOPE_MISMATCH: 'QUALIFICATION_SCOPE_MISMATCH',
  APPOINTMENT_REQUIRED: 'APPOINTMENT_REQUIRED',
  DELEGATION_REQUIRED: 'DELEGATION_REQUIRED',
  ALTERNATE_CANNOT_ASSUME_OFFICE: 'ALTERNATE_CANNOT_ASSUME_OFFICE',
  DEPARTMENT_READINESS_NOT_INSTITUTIONAL_ACCEPTANCE: 'DEPARTMENT_READINESS_NOT_INSTITUTIONAL_ACCEPTANCE',
  DEPARTMENT_CANNOT_SELF_ACTIVATE: 'DEPARTMENT_CANNOT_SELF_ACTIVATE',
  SUPPORT_COVERAGE_GAP: 'SUPPORT_COVERAGE_GAP',
  STAFFING_SHORTAGE_BLOCKS_READINESS: 'STAFFING_SHORTAGE_BLOCKS_READINESS',
  HIGH_CONSEQUENCE_ACCESS_DENIED: 'HIGH_CONSEQUENCE_ACCESS_DENIED',
  PROFESSIONAL_QUALIFICATION_EXPIRED: 'PROFESSIONAL_QUALIFICATION_EXPIRED',
  ACCESS_REVIEW_REQUIRED: 'ACCESS_REVIEW_REQUIRED',
} as const;

export const ATTENDANCE_NOT_COMPETENCE_MESSAGE =
  'Attendance at training does not establish operator competence or qualification';

export const COURSE_COMPLETION_NOT_QUALIFICATION_MESSAGE =
  'Course completion alone does not establish governmental qualification';

export const AI_CANNOT_QUALIFY_OPERATOR_MESSAGE =
  'AI assistance cannot qualify an operator for production roles';

export const TRAINING_PROVIDER_SELF_AUTHORITY_MESSAGE =
  'Training providers cannot self-assign governmental assessment authority';

export const ALTERNATE_CANNOT_ASSUME_OFFICE_MESSAGE =
  'An alternate does not gain authority until applicable appointment and delegation conditions are met';

export const DEPARTMENT_READINESS_NOT_ACCEPTANCE_MESSAGE =
  'Department readiness assessment does not equal institutional acceptance';

export const DEPARTMENT_CANNOT_SELF_ACTIVATE_MESSAGE =
  'A ready department cannot activate itself without separate activation authority';

export const PHASE_13F_INVARIANTS = {
  attendanceNotCompetence: true,
  courseCompletionNotQualification: true,
  systemRoleNotAppointment: true,
  technicalPermissionNotAuthority: true,
  staffAssignedNotAvailable: true,
  namedOwnerNotCoverage: true,
  aiCannotQualifyOperator: true,
  trainingProviderCannotSelfAssignAuthority: true,
  alternateCannotAssumeOffice: true,
  departmentReadinessNotInstitutionalAcceptance: true,
  departmentCannotSelfActivate: true,
  qualificationScopeEnforced: true,
  expiredTrainingBlocksHighConsequence: true,
  expiredProfessionalQualificationBlocks: true,
  revokedDelegationTriggersAccessReview: true,
  supportCoverageGapVisible: true,
  staffingShortageBlocksReadiness: true,
} as const;
import { PlatformEnvironmentClassification } from '@prisma/client';

export const PRODUCTION_READINESS_BOUNDARY_DISCLAIMER =
  'Deployment, release acceptance, and change approval are operational governance acts. They do not create, alter, or delegate institutional authority. CI success does not authorize production deployment. Software deployment does not equal feature activation.';

export const PRODUCTION_READINESS_REASON_CODES = {
  PRODUCTION_SEMANTICS_SPOOFING_FORBIDDEN: 'PRODUCTION_SEMANTICS_SPOOFING_FORBIDDEN',
  CI_GREEN_NOT_PRODUCTION_AUTHORIZATION: 'CI_GREEN_NOT_PRODUCTION_AUTHORIZATION',
  UNSIGNED_ARTIFACT_BLOCKED: 'UNSIGNED_ARTIFACT_BLOCKED',
  ARTIFACT_DIGEST_MISMATCH: 'ARTIFACT_DIGEST_MISMATCH',
  UNACCEPTED_ARTIFACT_BLOCKED: 'UNACCEPTED_ARTIFACT_BLOCKED',
  PRODUCTION_DEPLOY_REQUIRES_APPROVAL: 'PRODUCTION_DEPLOY_REQUIRES_APPROVAL',
  PRODUCTION_CREDENTIAL_IN_NON_PRODUCTION: 'PRODUCTION_CREDENTIAL_IN_NON_PRODUCTION',
  LIVE_GOVERNMENT_ENDPOINT_IN_TEST: 'LIVE_GOVERNMENT_ENDPOINT_IN_TEST',
  PRODUCTION_DATA_TRANSFER_UNAPPROVED: 'PRODUCTION_DATA_TRANSFER_UNAPPROVED',
  DEPLOYMENT_NOT_FEATURE_ACTIVATION: 'DEPLOYMENT_NOT_FEATURE_ACTIVATION',
  EMERGENCY_CHANGE_AUTHORITY_FORBIDDEN: 'EMERGENCY_CHANGE_AUTHORITY_FORBIDDEN',
  ROLLBACK_MUST_PRESERVE_RECORDS: 'ROLLBACK_MUST_PRESERVE_RECORDS',
  IMMUTABLE_ARTIFACT_MODIFICATION: 'IMMUTABLE_ARTIFACT_MODIFICATION',
  CHANGE_BYPASS_AUTHORITY_FORBIDDEN: 'CHANGE_BYPASS_AUTHORITY_FORBIDDEN',
  MATERIAL_CHANGE_REVALIDATION_REQUIRED: 'MATERIAL_CHANGE_REVALIDATION_REQUIRED',
  EMERGENCY_CHANGE_EXPIRED: 'EMERGENCY_CHANGE_EXPIRED',
} as const;

export const PLATFORM_ENVIRONMENT_CLASSIFICATIONS: readonly PlatformEnvironmentClassification[] = [
  PlatformEnvironmentClassification.LOCAL,
  PlatformEnvironmentClassification.DEVELOPMENT,
  PlatformEnvironmentClassification.TEST,
  PlatformEnvironmentClassification.INTEGRATION,
  PlatformEnvironmentClassification.SANDBOX,
  PlatformEnvironmentClassification.STAGING,
  PlatformEnvironmentClassification.PILOT,
  PlatformEnvironmentClassification.PRODUCTION,
  PlatformEnvironmentClassification.DISASTER_RECOVERY,
];

export const PRODUCTION_CAPABLE_CLASSIFICATIONS: readonly PlatformEnvironmentClassification[] = [
  PlatformEnvironmentClassification.PRODUCTION,
  PlatformEnvironmentClassification.PILOT,
  PlatformEnvironmentClassification.DISASTER_RECOVERY,
];

export const NON_PRODUCTION_CLASSIFICATIONS: readonly PlatformEnvironmentClassification[] =
  PLATFORM_ENVIRONMENT_CLASSIFICATIONS.filter(
    (classification) => !PRODUCTION_CAPABLE_CLASSIFICATIONS.includes(classification),
  );

export const REQUIRED_CI_CHECKS = [
  'clean_checkout',
  'locked_dependencies',
  'build',
  'prisma_validation',
  'migration_testing',
  'typecheck',
  'format',
  'lint',
  'unit',
  'integration',
  'e2e',
  'security_tests',
  'artifact_digest',
  'provenance',
] as const;

export const MATERIAL_REVALIDATION_TRIGGER_TYPES = [
  'MATERIAL_CONFIGURATION_CHANGE',
  'INTEGRATION_ENDPOINT_CHANGE',
  'AI_MODEL_UPDATE',
  'AUTHORITY_POLICY_CHANGE',
  'MATERIAL_FEATURE_CHANGE',
] as const;
export const PRODUCTION_READINESS_BOUNDARY_DISCLAIMER =
  'National launch activates only accepted capabilities and scope. Launch != universal authority != activation of every service != permanent acceptance.';

export const PHASE_13_BOUNDARY_DISCLAIMERS = {
  AUTHORITY_NOT_ACTIVATION: 'Authority != Activation',
  DEPLOYMENT_NOT_ACTIVATION: 'Deployment != Activation',
  TECHNICAL_COMPLETION_NOT_PRODUCTION_READINESS: 'Technical Completion != Production Readiness',
  PRODUCTION_READINESS_NOT_INSTITUTIONAL_ACCEPTANCE:
    'Production Readiness != Institutional Acceptance',
  INSTITUTIONAL_ACCEPTANCE_NOT_OPERATIONAL_ACTIVATION:
    'Institutional Acceptance != Operational Activation',
  OPERATIONAL_ACTIVATION_NOT_PERMANENT_AUTHORIZATION:
    'Operational Activation != Permanent Authorization',
  BACKUP_NOT_RECOVERY: 'Backup != Recovery',
  TECHNICAL_RESTORATION_NOT_INSTITUTIONAL_RESUMPTION:
    'Technical Restoration != Institutional Resumption',
  TRAINING_ATTENDANCE_NOT_COMPETENCE: 'Training Attendance != Competence',
  SECURITY_TEST_NOT_SECURITY_ACCREDITATION: 'Security Test != Security Accreditation',
  CI_GREEN_NOT_INSTITUTIONAL_ACCEPTANCE: 'CI Green != Institutional Acceptance',
  VENDOR_ACCEPTANCE_NOT_INSTITUTIONAL_ACCEPTANCE: 'Vendor Acceptance != Institutional Acceptance',
  EMERGENCY_AUTHORITY_NOT_PERMANENT_AUTHORITY: 'Emergency Authority != Permanent Authority',
  FEATURE_DEPLOYED_NOT_FEATURE_ACTIVATED: 'Feature Deployed != Feature Activated',
  PILOT_SUCCESS_NOT_PRODUCTION_AUTHORIZATION: 'Pilot Success != Production Authorization',
  SUSPENSION_NOT_RECORD_DELETION: 'Suspension != Record Deletion',
  RETIREMENT_NOT_RECORD_DESTRUCTION: 'Retirement != Record Destruction',
} as const;

export const PRODUCTION_READINESS_REASON_CODES = {
  CI_NOT_INSTITUTIONAL_ACCEPTANCE: 'CI_SUCCESS_NOT_INSTITUTIONAL_ACCEPTANCE',
  DEPLOYMENT_NOT_ACTIVATION: 'DEPLOYMENT_NOT_ACTIVATION',
  PRODUCTION_READY_NOT_AUTHORIZED: 'PRODUCTION_READY_NOT_PRODUCTION_AUTHORIZED',
  PILOT_NOT_AUTHORIZATION: 'PILOT_SUCCESS_NOT_PRODUCTION_AUTHORIZATION',
  TECHNICAL_NOT_INSTITUTIONAL: 'TECHNICAL_ACCEPTANCE_NOT_INSTITUTIONAL',
  ACCEPTANCE_NOT_ACTIVATION: 'INSTITUTIONAL_ACCEPTANCE_NOT_ACTIVATION',
  ACTIVATION_EXCEEDS_SCOPE: 'ACTIVATION_EXCEEDS_ACCEPTED_SCOPE',
  SYSADMIN_CANNOT_ACTIVATE: 'SYSTEM_ADMIN_CANNOT_ACTIVATE_INSTITUTIONAL_FUNCTION',
  VENDOR_CANNOT_ACCEPT_RISK: 'VENDOR_CANNOT_ACCEPT_INSTITUTIONAL_RISK',
  AI_CANNOT_ACCEPT_RISK: 'AI_CANNOT_ACCEPT_INSTITUTIONAL_RISK',
  AI_CANNOT_ACTIVATE: 'AI_CANNOT_ACTIVATE_PRODUCTION',
  AI_CANNOT_OVERRIDE_SAFE_HALT: 'AI_CANNOT_OVERRIDE_SAFE_HALT',
  DEVELOPER_CANNOT_SELF_ACCEPT: 'DEVELOPER_CANNOT_ASSIGN_ACCEPTANCE_AUTHORITY',
  EXPIRED_ACCEPTANCE: 'EXPIRED_ACCEPTANCE_CANNOT_REMAIN_VALID',
  EXPIRED_OFFICEHOLDER_BLOCKS: 'EXPIRED_OFFICEHOLDER_AUTHORITY_BLOCKS_ACTION',
  REVOKED_DELEGATION_BLOCKS: 'REVOKED_DELEGATION_BLOCKS_CONSEQUENTIAL_ACTION',
  EXPIRED_QUALIFICATION_BLOCKS: 'EXPIRED_QUALIFICATION_BLOCKS_FUNCTION',
  TRAINING_NOT_COMPETENCE: 'TRAINING_ATTENDANCE_NOT_COMPETENCE',
  SHARED_PROD_ADMIN_REJECTED: 'SHARED_PRODUCTION_ADMINISTRATOR_REJECTED',
  SHARED_EMERGENCY_CREDS_REJECTED: 'SHARED_EMERGENCY_CREDENTIALS_REJECTED',
  BREAK_GLASS_NOT_PERMANENT: 'BREAK_GLASS_ACCESS_CANNOT_REMAIN_PERMANENT',
  BREAK_GLASS_NO_SUBSTANTIVE_AUTHORITY: 'BREAK_GLASS_CANNOT_CREATE_SUBSTANTIVE_AUTHORITY',
  SECRET_IN_SOURCE: 'PRODUCTION_SECRET_CANNOT_BE_COMMITTED',
  SECRET_IN_LOG: 'SECRET_CANNOT_APPEAR_IN_LOG',
  PAN_IN_LOG: 'FULL_PAYMENT_CARD_SECRET_CANNOT_BE_LOGGED',
  UNSIGNED_ARTIFACT: 'UNSIGNED_RELEASE_ARTIFACT_BLOCKED',
  WRONG_DIGEST: 'WRONG_ARTIFACT_DIGEST_BLOCKED',
  UNVERIFIED_PROVENANCE: 'UNVERIFIED_BUILD_PROVENANCE_BLOCKED',
  DEV_CRED_IN_PROD: 'PRODUCTION_CANNOT_USE_DEV_CREDENTIAL',
  TEST_CALLS_PROD: 'TEST_SYSTEM_CANNOT_CALL_PRODUCTION_INTEGRATION',
  PROD_DATA_IN_DEV: 'PRODUCTION_DATA_CANNOT_ENTER_DEV_WITHOUT_PROTECTION',
  HEALTH_NOT_VALIDITY: 'GREEN_HEALTH_CHECK_NOT_INSTITUTIONAL_VALIDITY',
  HTTP200_NOT_DETERMINATION: 'HTTP_200_NOT_GOVERNMENT_DETERMINATION',
  LOAD_DEGRADATION_NO_BYPASS: 'LOAD_DEGRADATION_CANNOT_BYPASS_AUTHORITY',
  EXHAUSTION_NO_AUTO_APPROVE: 'RESOURCE_EXHAUSTION_CANNOT_AUTO_APPROVE',
  QUEUE_REPLAY_NO_DUPLICATE: 'QUEUE_REPLAY_CANNOT_DUPLICATE_ACTION',
  BACKUP_NOT_RECOVERY: 'BACKUP_SUCCESS_NOT_RECOVERABILITY',
  UNTESTED_RESTORE: 'UNTESTED_RESTORE_CANNOT_SUPPORT_READINESS',
  CORRUPT_RESTORE: 'CORRUPT_RESTORE_CANNOT_RESUME',
  RESTORATION_NOT_RESUMPTION: 'TECHNICAL_RESTORATION_NOT_INSTITUTIONAL_RESUMPTION',
  EMERGENCY_NO_WAIVE: 'EMERGENCY_CANNOT_WAIVE_MANDATORY_VERIFICATION',
  MANUAL_NO_SOD_BYPASS: 'MANUAL_OPERATION_CANNOT_BYPASS_SOD',
  MANUAL_NO_ERASE_PROVENANCE: 'MANUAL_OPERATION_CANNOT_ERASE_PROVENANCE',
  MANUAL_NO_OVERWRITE: 'MANUAL_RECORD_CANNOT_BE_OVERWRITTEN',
  BACKLOG_NO_PRIVILEGE: 'BACKLOG_CANNOT_PRIVILEGE_WITHOUT_LAWFUL_CRITERIA',
  CONTINUITY_NO_GUARANTEE: 'CONTINUITY_EXERCISE_NOT_FUTURE_GUARANTEE',
  SCAN_NOT_ACCREDITATION: 'SECURITY_SCAN_NOT_SECURITY_ACCREDITATION',
  VULNERABILITY_HIDDEN: 'VULNERABILITY_CANNOT_BE_HIDDEN',
  CRITICAL_DEFECT_OMITTED: 'CRITICAL_DEFECT_CANNOT_BE_OMITTED',
  FAILED_MUST_FAIL_OMITTED: 'FAILED_MUST_FAIL_CANNOT_BE_OMITTED',
  LIMITATION_REMOVED: 'KNOWN_LIMITATION_CANNOT_BE_REMOVED',
  RISK_SILENTLY_ACCEPTED: 'RESIDUAL_RISK_CANNOT_BE_SILENTLY_ACCEPTED',
  RISK_EXCEEDS_AUTHORITY: 'RISK_ACCEPTANCE_EXCEEDS_ACCEPTOR_AUTHORITY',
  EXPIRED_EXCEPTION: 'EXPIRED_SECURITY_EXCEPTION_CANNOT_CONTINUE',
  INTEGRATION_NO_ACCEPTANCE: 'CRITICAL_INTEGRATION_REQUIRES_ACCEPTANCE',
  AI_MODEL_SILENT_CHANGE: 'AI_MODEL_CANNOT_CHANGE_SILENTLY',
  AI_SUSPENDED_CONTINUES: 'AI_USE_CASE_CANNOT_CONTINUE_AFTER_SUSPENSION',
  AGENT_CRED_NOT_REVOKED: 'AGENT_CREDENTIAL_MUST_REVOKE_ON_SUSPENSION',
  PQC_FALSELY_COMPLETE: 'PQC_READINESS_CANNOT_BE_FALSELY_LABELED',
  CRYPTO_ROTATION_DESTROYS_HISTORY: 'CRYPTOGRAPHIC_ROTATION_CANNOT_DESTROY_HISTORICAL_VERIFICATION',
  CERT_EXPIRY_HIDDEN: 'CERTIFICATE_EXPIRY_CANNOT_BE_HIDDEN',
  CHANGE_CONTROL_EXPANDS_AUTHORITY: 'CHANGE_CONTROL_CANNOT_EXPAND_INSTITUTIONAL_AUTHORITY',
  EMERGENCY_NO_REVIEW_BYPASS: 'EMERGENCY_CHANGE_CANNOT_BYPASS_LATER_REVIEW',
  DEPLOYED_NOT_ACTIVATED: 'FEATURE_DEPLOYED_NOT_OPERATIONALLY_ACTIVATED',
  ROLLBACK_NO_ERASE: 'ROLLBACK_CANNOT_ERASE_OFFICIAL_HISTORY',
  DB_ROLLBACK_NO_DESTROY: 'DATABASE_ROLLBACK_CANNOT_DESTROY_EVIDENCE',
  NOTIFICATION_NOT_LEGAL_NOTICE: 'FAILED_NOTIFICATION_NOT_LEGALLY_COMPLETED_NOTICE',
  PAYMENT_OUTAGE_NO_WAIVE: 'PAYMENT_PROVIDER_OUTAGE_CANNOT_WAIVE_FEE',
  INTEGRATION_OUTAGE_NO_FABRICATE: 'INTEGRATION_OUTAGE_CANNOT_FABRICATE_RESPONSE',
  TECH_ADMIN_NO_OVERWRITE: 'TECHNICAL_ADMIN_CANNOT_OVERWRITE_EXTERNAL_RECORD',
  STALE_SOURCE_CURRENT: 'STALE_SOURCE_CANNOT_SILENTLY_APPEAR_CURRENT',
  AI_OUTPUT_FINAL_DEGRADED: 'AI_OUTPUT_CANNOT_BECOME_FINAL_DECISION_DEGRADED',
  TWIN_NOT_AVAILABILITY: 'DIGITAL_TWIN_NOT_INFRASTRUCTURE_AVAILABILITY',
  ALERT_NOT_CONCLUSION: 'ALERT_NOT_INCIDENT_CONCLUSION',
  RISK_SCORE_NO_OVERRIDE: 'RISK_SCORE_CANNOT_OVERRIDE_LAUNCH_GATE',
  KPI_CONCEALS_CONTROL: 'PERFORMANCE_KPI_CANNOT_CONCEAL_FAILED_CONTROL',
  SECURITY_SUPPRESSED: 'CRITICAL_SECURITY_FINDING_CANNOT_BE_SUPPRESSED',
  COMMERCIAL_NO_FORCE: 'COMMERCIAL_COMMITMENT_CANNOT_FORCE_ACTIVATION',
  EXECUTIVE_NO_OVERRIDE: 'EXECUTIVE_PREFERENCE_CANNOT_OVERRIDE_SECURITY',
  ACTIVATION_NO_ACCEPTANCE: 'ACTIVATION_REQUIRES_CURRENT_ACCEPTANCE',
  ACTIVATION_NO_OWNER: 'ACTIVATION_REQUIRES_ACCOUNTABLE_OWNER',
  ACTIVATION_NO_MONITORING: 'ACTIVATION_REQUIRES_MONITORING',
  ACTIVATION_NO_SUSPENSION_PATH: 'ACTIVATION_REQUIRES_SUSPENSION_PATH',
  ACTIVATION_NO_ROLLBACK: 'ACTIVATION_REQUIRES_TESTED_ROLLBACK',
  ACTIVATION_NO_CONTINUITY: 'ACTIVATION_REQUIRES_TESTED_CONTINUITY',
  ACTIVATION_NO_QUALIFIED_STAFF: 'ACTIVATION_REQUIRES_QUALIFIED_STAFF',
  ACTIVATION_RECORD_INTEGRITY: 'ACTIVATION_REQUIRES_RECORD_INTEGRITY',
  ACTIVATION_ISSUANCE_AUTH: 'ACTIVATION_REQUIRES_AUTHENTICATED_ISSUANCE',
  SUSPENSION_BLOCKS_ACCESS: 'SUSPENSION_MUST_BLOCK_AFFECTED_ACCESS',
  SUSPENSION_PRESERVES_RECORDS: 'SUSPENSION_MUST_PRESERVE_RECORDS',
  SUSPENSION_PRESERVES_APPEALS: 'SUSPENSION_MUST_NOT_ERASE_APPEALS',
  SUSPENSION_NOT_UNNECESSARY: 'SUSPENSION_SHOULD_NOT_STOP_UNRELATED_SERVICES',
  RETIRED_NOT_REACHABLE: 'RETIRED_CAPABILITY_CANNOT_REMAIN_REACHABLE',
  RETIRED_CREDS_REVOKED: 'RETIRED_CREDENTIALS_MUST_REVOKE',
  RETIRED_INTEGRATION_STOP: 'RETIRED_INTEGRATION_MUST_STOP',
  DECOMMISSION_NO_DESTROY: 'DECOMMISSION_CANNOT_DESTROY_LEGAL_HELD_RECORDS',
  VENDOR_NO_BLOCK_EXPORT: 'VENDOR_TERMINATION_CANNOT_PREVENT_EXPORT',
  REPLACEMENT_NO_PRE_ACCEPTANCE: 'REPLACEMENT_CANNOT_OPERATE_BEFORE_ACCEPTANCE',
  REVALIDATION_NOT_HIDDEN: 'REVALIDATION_FAILURE_CANNOT_REMAIN_HIDDEN',
  CLIENT_ACTIVATION_FIELDS: 'CLIENT_CANNOT_SET_ACTIVATION_FIELDS',
  CLIENT_GATE_FIELDS: 'CLIENT_CANNOT_SET_GATE_FIELDS',
  CLIENT_SUSPENSION_FIELDS: 'CLIENT_CANNOT_SET_SUSPENSION_FIELDS',
  CORRECTIVE_ACTION_NO_SKIP_VERIFY: 'CORRECTIVE_ACTION_REQUIRES_VERIFICATION_BEFORE_CLOSURE',
} as const;

export const FORBIDDEN_CLIENT_ACTIVATION_FIELDS = [
  'outcome',
  'newStatus',
  'gateOutcome',
  'effectiveAt',
  'authorityEvaluationRecordId',
] as const;

export const FORBIDDEN_CLIENT_GATE_FIELDS = [
  'gateOutcome',
  'passed',
  'blockingDefectsOverridden',
] as const;

export const FORBIDDEN_CLIENT_SUSPENSION_FIELDS = [
  'status',
  'liftedAt',
  'liftedByIdentityId',
] as const;

export const LAUNCH_GATE_REQUIREMENTS = [
  'all_applicable_acceptance_decisions_valid',
  'production_activation_decision_valid',
  'exact_release_accepted',
  'migration_validated',
  'no_unresolved_blocking_defect',
  'security_readiness_accepted',
  'privacy_controls_accepted',
  'backup_restore_tested',
  'continuity_exercise_passed',
  'resumption_process_tested',
  'monitoring_active',
  'incident_process_active',
  'qualified_workforce_available',
  'support_ready',
  'critical_integrations_accepted',
  'ai_use_cases_accepted_or_suspendable',
  'records_audit_functioning',
  'rollback_available',
  'residual_risks_accepted_by_proper_owners',
] as const;

export const STABILIZATION_MONITORING_CATEGORIES = [
  'ERRORS',
  'PERFORMANCE',
  'WORKFLOW_INTEGRITY',
  'AUTHORITY_FAILURES',
  'RECORDS_INTEGRITY',
  'SECURITY_EVENTS',
  'USER_ISSUES',
  'INTEGRATION_FAILURES',
  'PAYMENT_FAILURES',
  'NOTIFICATION_FAILURES',
  'AI_ANOMALIES',
  'ACCESS_ANOMALIES',
  'SUPPORT_VOLUME',
] as const;

export const OPERATIONAL_ACTIVATION_BASIS = {
  INSTITUTIONAL_ACTIVATION_DECISION: 'INSTITUTIONAL_ACTIVATION_DECISION',
  SCOPED_CAPABILITY_ACTIVATION: 'SCOPED_CAPABILITY_ACTIVATION',
  NATIONAL_LAUNCH: 'NATIONAL_LAUNCH',
} as const;

export const MUST_FAIL_INVARIANT_COUNT = 100;
