export const PHASE_13_MODEL_NAMES = [
  'LaunchReadinessSnapshot',
  'LaunchEvent',
  'OperationalActivationRecord',
  'ProductionMonitoringPlan',
  'StabilizationPeriod',
  'StabilizationObservation',
  'ProductionDefect',
  'ProductionCorrectiveAction',
  'OperationalRevalidation',
  'OperationalSuspension',
  'CapabilityRetirement',
  'CapabilityReplacement',
  'DecommissioningPlan',
  'DecommissioningExecution',
  'DataExportManifest',
  'RecordsPreservationManifest',
  'CredentialShutdownRecord',
  'IntegrationShutdownRecord',
  'ExitAcceptanceRecord',
] as const;

export const PHASE_13_ENUM_NAMES = [
  'ProductionDefectSeverity',
  'ProductionDefectStatus',
  'ProductionCorrectiveActionStatus',
  'OperationalRevalidationOutcome',
  'OperationalRevalidationTrigger',
  'OperationalSuspensionScope',
  'OperationalSuspensionStatus',
  'LaunchEventType',
  'LaunchGateOutcome',
  'OperationalActivationStatus',
  'OperationalActivationOutcome',
  'StabilizationPeriodStatus',
  'StabilizationObservationCategory',
  'ProductionMonitoringPlanStatus',
  'CapabilityReplacementStatus',
  'DecommissioningPlanStatus',
  'ExitAcceptanceOutcome',
] as const;
