export const PHASE_13F_MODEL_NAMES = [
  'OperationalRoleRequirement',
  'TrainingRequirement',
  'OperatorReadinessProfile',
  'OperatorQualification',
  'OperatorCompetencyAssessment',
  'TrainingCompletion',
  'PracticalAssessment',
  'AuthorityBoundaryAssessment',
  'SecurityPrivacyAssessment',
  'ContinuityCompetencyAssessment',
  'SupportCoveragePlan',
  'SupportAssignment',
  'OnCallAssignment',
  'SuccessionAssignment',
  'DepartmentReadinessAssessment',
  'StaffingReadinessAssessment',
  'QualificationExpiryEvent',
  'OperatorAccessReview',
] as const;

export const PHASE_13F_ENUM_NAMES = [
  'OperatorQualificationStatus',
  'DepartmentReadinessStatus',
  'StaffingReadinessStatus',
  'OperationalRoleRequirementStatus',
  'CompetencyAssessmentOutcome',
  'TrainingCompletionStatus',
  'OperatorAccessReviewTrigger',
  'OperatorAccessReviewStatus',
  'QualificationExpiryEventType',
  'SupportCoveragePlanStatus',
  'SupportTier',
  'OnCallAssignmentStatus',
  'SuccessionAssignmentStatus',
export const PHASE_13E_MODEL_NAMES = [
  'EnvironmentDefinition',
  'EnvironmentConfigurationBaseline',
  'EnvironmentCredentialBinding',
  'EnvironmentIntegrationEndpoint',
  'ReleaseDefinition',
  'ReleaseArtifact',
  'ReleaseApproval',
  'DeploymentRecord',
  'DeploymentVerification',
  'RollbackPlan',
  'RollbackExecution',
  'ChangeRequest',
  'ChangeAssessment',
  'EmergencyChange',
  'ConfigurationItem',
  'ConfigurationChange',
  'FeatureActivation',
  'ReleaseRevalidationTrigger',
  'CiPipelineRun',
  'DataTransferApproval',
] as const;

export const PHASE_13E_ENUM_NAMES = [
  'PlatformEnvironmentClassification',
  'EnvironmentDefinitionStatus',
  'ReleaseDefinitionStatus',
  'ReleaseArtifactStatus',
  'ReleaseApprovalStatus',
  'DeploymentRecordStatus',
  'DeploymentVerificationStatus',
  'RollbackPlanStatus',
  'RollbackExecutionStatus',
  'ChangeRequestStatus',
  'ChangeAssessmentOutcome',
  'EmergencyChangeStatus',
  'ConfigurationItemStatus',
  'ConfigurationChangeStatus',
  'FeatureActivationStatus',
  'ReleaseRevalidationTriggerType',
  'CiPipelineRunStatus',
  'DataTransferApprovalStatus',
  'EnvironmentIntegrationMode',
export const PHASE_13_MODEL_NAMES = [
  'LaunchReadinessSnapshot',
  'LaunchEvent',
  'OperationalActivationRecord',
  'ProductionMonitoringPlan',
  'StabilizationPeriod',
  'StabilizationObservation',
  'ProductionDefect',
  'ProductionCorrectiveAction',
  'OperationalRevalidation',
  'OperationalSuspension',
  'CapabilityRetirement',
  'CapabilityReplacement',
  'DecommissioningPlan',
  'DecommissioningExecution',
  'DataExportManifest',
  'RecordsPreservationManifest',
  'CredentialShutdownRecord',
  'IntegrationShutdownRecord',
  'ExitAcceptanceRecord',
] as const;

export const PHASE_13_ENUM_NAMES = [
  'ProductionDefectSeverity',
  'ProductionDefectStatus',
  'ProductionCorrectiveActionStatus',
  'OperationalRevalidationOutcome',
  'OperationalRevalidationTrigger',
  'OperationalSuspensionScope',
  'OperationalSuspensionStatus',
  'LaunchEventType',
  'LaunchGateOutcome',
  'OperationalActivationStatus',
  'OperationalActivationOutcome',
  'StabilizationPeriodStatus',
  'StabilizationObservationCategory',
  'ProductionMonitoringPlanStatus',
  'CapabilityReplacementStatus',
  'DecommissioningPlanStatus',
  'ExitAcceptanceOutcome',
] as const;
