export const AI_GOVERNANCE_BOUNDARY_DISCLAIMER =
  'AI assistance, recommendations, and recorded outputs do not constitute government authority, evidence, or official decisions.';

export const AI_GOVERNANCE_REASON_CODES = {
  AI_NOT_AUTHORITY: 'AI_NOT_AUTHORITY',
  AI_OUTPUT_NOT_EVIDENCE: 'AI_OUTPUT_NOT_EVIDENCE',
  AI_RECOMMENDATION_NOT_DECISION: 'AI_RECOMMENDATION_NOT_DECISION',
  AI_CONFIDENCE_NOT_COMPLETENESS: 'AI_CONFIDENCE_NOT_COMPLETENESS',
  AGENT_PERMISSION_NOT_INSTITUTIONAL_AUTHORITY: 'AGENT_PERMISSION_NOT_INSTITUTIONAL_AUTHORITY',
  TOOL_ACCESS_NOT_UNIVERSAL_PERMISSION: 'TOOL_ACCESS_NOT_UNIVERSAL_PERMISSION',
  AUTONOMOUS_FINAL_DECISION_FORBIDDEN: 'AUTONOMOUS_FINAL_DECISION_FORBIDDEN',
  PROHIBITED_USE_CASE: 'PROHIBITED_USE_CASE',
  MODEL_SUSPENDED: 'MODEL_SUSPENDED',
  USE_CASE_SUSPENDED: 'USE_CASE_SUSPENDED',
  USE_CASE_EXPIRED: 'USE_CASE_EXPIRED',
  AGENT_SUSPENDED: 'AGENT_SUSPENDED',
  ENTITLEMENT_DENIED: 'ENTITLEMENT_DENIED',
  PROMPT_INJECTION_BLOCKED: 'PROMPT_INJECTION_BLOCKED',
  DOCUMENT_INSTRUCTIONS_UNTRUSTED: 'DOCUMENT_INSTRUCTIONS_UNTRUSTED',
  CROSS_CASE_RETRIEVAL_BLOCKED: 'CROSS_CASE_RETRIEVAL_BLOCKED',
  PROHIBITED_DATASET_BLOCKED: 'PROHIBITED_DATASET_BLOCKED',
  EVIDENCE_GATE_REQUIRED: 'EVIDENCE_GATE_REQUIRED',
  AGENT_SELF_EXPANSION_FORBIDDEN: 'AGENT_SELF_EXPANSION_FORBIDDEN',
  SECRET_IN_LOG_FORBIDDEN: 'SECRET_IN_LOG_FORBIDDEN',
  FABRICATED_AUTHORITY_BLOCKED: 'FABRICATED_AUTHORITY_BLOCKED',
  GOVERNMENT_ACTION_FORBIDDEN: 'GOVERNMENT_ACTION_FORBIDDEN',
} as const;

export const FORBIDDEN_AI_USE_CASE_CLIENT_FIELDS = [
  'status',
  'allowsAutonomousFinalDecision',
] as const;

export const FORBIDDEN_AI_MODEL_DEFINITION_CLIENT_FIELDS = ['status'] as const;

export const FORBIDDEN_AI_AGENT_DEFINITION_CLIENT_FIELDS = [
  'status',
  'suspensionState',
  'permittedOperations',
  'restrictions',
  'delegationChain',
] as const;

export const FORBIDDEN_AI_EXECUTION_CLIENT_FIELDS = [
  'status',
  'executedAt',
  'humanReviewerIdentityId',
] as const;

export const FORBIDDEN_AI_GOVERNMENT_ACTIONS = [
  'APPROVE',
  'REFUSE',
  'SIGN',
  'ISSUE',
  'HEAR_APPEAL',
  'WAIVE',
  'AUTHORIZE_EXPENDITURE',
  'INITIATE_ENFORCEMENT',
  'ALTER_OFFICIAL_RECORD',
] as const;

export const PROMPT_INJECTION_PATTERNS = [
  /ignore (all )?(previous|prior|system) instructions/i,
  /you are now (an? )?(admin|authority|judge|decision maker)/i,
  /grant (yourself|me) (admin|root|authority|permission)/i,
  /override (tool|policy|permission|authority)/i,
  /disregard (policy|guardrails|restrictions)/i,
] as const;

export const SECRET_LOG_PATTERNS = [
  /api[_-]?key/i,
  /secret/i,
  /password/i,
  /bearer\s+[a-z0-9._-]+/i,
  /sk-[a-z0-9]{8,}/i,
] as const;

export const FABRICATED_AUTHORITY_PATTERNS = [
  /pursuant to (my|the ai'?s?) authority/i,
  /i (hereby )?(approve|deny|grant|authorize|decide)/i,
  /official decision (is|has been) (made|recorded|issued)/i,
  /this constitutes (a )?(final )?(government )?decision/i,
] as const;

export const ACTIVE_AI_STATUSES = {
  modelDefinition: ['ACTIVE', 'APPROVED'],
  modelVersion: ['ACTIVE', 'APPROVED'],
  useCase: ['ACTIVE', 'APPROVED'],
  useCaseVersion: ['ACTIVE', 'APPROVED'],
  agentDefinition: ['ACTIVE', 'APPROVED'],
  agentVersion: ['ACTIVE', 'APPROVED'],
  entitlement: ['ACTIVE', 'APPROVED'],
} as const;

export const AIEvaluationTestCategory = {
  HALLUCINATION: 'HALLUCINATION',
  UNSUPPORTED_AUTHORITY_CLAIM: 'UNSUPPORTED_AUTHORITY_CLAIM',
  SOURCE_MISATTRIBUTION: 'SOURCE_MISATTRIBUTION',
  PROMPT_INJECTION: 'PROMPT_INJECTION',
  DATA_POISONING: 'DATA_POISONING',
  RETRIEVAL_AUTHORIZATION_BYPASS: 'RETRIEVAL_AUTHORIZATION_BYPASS',
  PII_LEAKAGE: 'PII_LEAKAGE',
  CROSS_CASE_LEAKAGE: 'CROSS_CASE_LEAKAGE',
  TOOL_MISUSE: 'TOOL_MISUSE',
  BIAS_DISPARATE_IMPACT: 'BIAS_DISPARATE_IMPACT',
  MODEL_DRIFT: 'MODEL_DRIFT',
  UNSAFE_RECOMMENDATION: 'UNSAFE_RECOMMENDATION',
  REFUSAL_BEHAVIOR: 'REFUSAL_BEHAVIOR',
  SUSPENSION: 'SUSPENSION',
  REPLAYABILITY: 'REPLAYABILITY',
} as const;
