export const PHASE_12D_MODEL_NAMES = [
  'AIModelDefinition',
  'AIModelVersion',
  'AICapabilityDefinition',
  'AIUseCase',
  'AIUseCaseVersion',
  'AIAgentDefinition',
  'AIAgentVersion',
  'AIDataEntitlement',
  'AIToolEntitlement',
  'AIOutputContract',
  'AIEvaluation',
  'AIEvaluationTest',
  'AIIncident',
  'AISuspensionRecord',
  'AIRevalidationRecord',
  'AIPromptPolicy',
  'AIExecutionRecord',
  'AIHumanDisposition',
] as const;

export const PHASE_12D_ENUM_NAMES = [
  'AIRiskClass',
  'AIModelDefinitionStatus',
  'AIModelVersionStatus',
  'AIDeploymentType',
  'AICapabilityDefinitionStatus',
  'AIUseCaseStatus',
  'AIAgentDefinitionStatus',
  'AIAgentVersionStatus',
  'AIEntitlementStatus',
  'AIOutputContractStatus',
  'AIPromptPolicyType',
  'AIPromptPolicyStatus',
  'AIExecutionStatus',
  'AIHumanDispositionType',
  'AISuspensionScope',
  'AISuspensionStatus',
  'AIEvaluationStatus',
  'AIEvaluationTestCategory',
  'AIEvaluationTestOutcome',
  'AIIncidentSeverity',
  'AIIncidentStatus',
  'AIRevalidationStatus',
] as const;

export const AI_RISK_CLASSES = [
  'LOW',
  'MODERATE',
  'HIGH',
  'CONSEQUENTIAL_ASSISTANCE',
  'PROHIBITED',
] as const;

export const AI_HUMAN_DISPOSITION_TYPES = [
  'ACCEPTED_FOR_ASSISTIVE_USE',
  'REVISED',
  'REJECTED',
  'ESCALATED',
  'UNSAFE',
  'OUTSIDE_SCOPE',
] as const;

export const AI_EVALUATION_TEST_CATEGORIES = [
  'HALLUCINATION',
  'UNSUPPORTED_AUTHORITY_CLAIM',
  'SOURCE_MISATTRIBUTION',
  'PROMPT_INJECTION',
  'DATA_POISONING',
  'RETRIEVAL_AUTHORIZATION_BYPASS',
  'PII_LEAKAGE',
  'CROSS_CASE_LEAKAGE',
  'TOOL_MISUSE',
  'BIAS_DISPARATE_IMPACT',
  'MODEL_DRIFT',
  'UNSAFE_RECOMMENDATION',
  'REFUSAL_BEHAVIOR',
  'SUSPENSION',
  'REPLAYABILITY',
] as const;
