export const WORKFLOW_SAFE_HALT_REASONS = {
  WORKFLOW_VERSION_SUSPENDED: 'WORKFLOW_VERSION_SUSPENDED',
  WORKFLOW_VERSION_SUPERSEDED: 'WORKFLOW_VERSION_SUPERSEDED',
  AUTHORITY_CANNOT_BE_ESTABLISHED: 'AUTHORITY_CANNOT_BE_ESTABLISHED',
  APPOINTMENT_INVALID: 'APPOINTMENT_INVALID',
  DELEGATION_SCOPE_MISMATCH: 'DELEGATION_SCOPE_MISMATCH',
  AUTHORITY_BOUNDARY_CROSSED: 'AUTHORITY_BOUNDARY_CROSSED',
  MANDATORY_DEPENDENCY_UNRESOLVED: 'MANDATORY_DEPENDENCY_UNRESOLVED',
  RUNTIME_GRAPH_INCONSISTENT: 'RUNTIME_GRAPH_INCONSISTENT',
  RECORDS_CANNOT_BE_PRESERVED: 'RECORDS_CANNOT_BE_PRESERVED',
  PROHIBITED_DECISION_AUTOMATION: 'PROHIBITED_DECISION_AUTOMATION',
  CRITICAL_CONFIGURATION_UNAVAILABLE: 'CRITICAL_CONFIGURATION_UNAVAILABLE',
} as const;

export const WORKFLOW_ORCHESTRATION_ERRORS = {
  INACTIVE_WORKFLOW: 'Inactive workflow version cannot be started',
  SERVICE_MISMATCH: 'Workflow version does not belong to the case service version',
  ALREADY_STARTED: 'Workflow instance already started for this case',
  STEP_NOT_READY: 'Step is not ready to start',
  STEP_NOT_IN_PROGRESS: 'Step is not in progress',
  STEP_ALREADY_COMPLETED: 'Step has already been completed',
  AUTHORITY_DENIED: 'Authority evaluation denied the requested action',
  SERVICE_IDENTITY_HUMAN_STEP: 'Service identity cannot complete human-required steps',
  ARBITRARY_TRANSITION: 'Client cannot choose arbitrary transition destination',
  SAFE_HALTED: 'Workflow is safe-halted and cannot continue normally',
  DECISION_GATE_NO_CREATE: 'Decision gate cannot create a government decision',
  ISSUANCE_GATE_NO_ISSUE: 'Issuance gate cannot issue an instrument',
  DECISION_RESULT_REQUIRED: 'Issuance gate requires an external decision result',
  CONCURRENCY_CONFLICT: 'Concurrent modification detected',
  PARALLEL_RACE: 'Parallel transition race detected',
} as const;
