import { type PrismaService } from '../../src/database/prisma.service';

export async function resetProductionReadinessData(prisma: PrismaService): Promise<void> {
  await prisma.continuityCorrectiveAction.deleteMany();
  await prisma.resumptionAuthorization.deleteMany();
  await prisma.resumptionReadinessAssessment.deleteMany();
  await prisma.manualDigitalReconciliation.deleteMany();
  await prisma.backlogRecoveryPlan.deleteMany();
  await prisma.recoveryAction.deleteMany();
  await prisma.recoveryExercise.deleteMany();
  await prisma.restoreTest.deleteMany();
  await prisma.backupExecutionRecord.deleteMany();
  await prisma.backupDefinition.deleteMany();
  await prisma.continuityDecision.deleteMany();
  await prisma.manualOperationAuthorization.deleteMany();
  await prisma.continuityEvent.deleteMany();
  await prisma.manualOperationProcedure.deleteMany();
  await prisma.continuityProcedure.deleteMany();
  await prisma.singlePointOfFailure.deleteMany();
  await prisma.continuityDependency.deleteMany();
  await prisma.recoveryObjective.deleteMany();
  await prisma.businessImpactAssessment.deleteMany();
  await prisma.criticalServiceDefinition.deleteMany();
  await prisma.exitAcceptanceRecord.deleteMany();
  await prisma.integrationShutdownRecord.deleteMany();
  await prisma.credentialShutdownRecord.deleteMany();
  await prisma.recordsPreservationManifest.deleteMany();
  await prisma.dataExportManifest.deleteMany();
  await prisma.decommissioningExecution.deleteMany();
  await prisma.decommissioningPlan.deleteMany();
  await prisma.capabilityReplacement.deleteMany();
  await prisma.capabilityRetirement.deleteMany();
  await prisma.operationalRevalidation.deleteMany();
  await prisma.operationalSuspension.deleteMany();
  await prisma.productionCorrectiveAction.deleteMany();
  await prisma.productionDefect.deleteMany();
  await prisma.stabilizationObservation.deleteMany();
  await prisma.stabilizationPeriod.deleteMany();
  await prisma.productionMonitoringPlan.deleteMany();
  await prisma.launchEvent.deleteMany();
  await prisma.operationalActivationRecord.deleteMany();
  await prisma.launchReadinessSnapshot.deleteMany();
}
