export const LABOUR_FOUNDATION_MODEL_NAMES = [
  'EmployerRegistryRecord',
  'WorkerProfileReference',
  'EmploymentRelationship',
  'EmploymentRelationshipHistory',
  'EmploymentDeclaration',
  'EmploymentContractReference',
  'OccupationClassificationReference',
  'WorkPermitRecord',
  'WorkPermitApplicationProfile',
  'WorkPermitCondition',
  'WorkPermitStatusHistory',
  'EmploymentSponsorship',
  'LabourMarketDeterminationReference',
  'ProfessionalQualificationReference',
  'EmployerWorkforceProfile',
  'EmployerWorkforceDeclaration',
  'LabourInspectionReference',
  'LabourComplianceMatterReference',
  'EmploymentComplaint',
  'EmploymentDispute',
  'EmploymentTerminationNotification',
  'WorkplaceRequirementReference',
  'LabourExternalDependency',
] as const;

export const LABOUR_FOUNDATION_ENUM_NAMES = [
  'LabourDataClassification',
  'LabourActorPersona',
  'EmployerRegistryStatus',
  'EmploymentRelationshipStatus',
  'WorkPermitApplicationProfileStatus',
  'WorkPermitLifecycleStatus',
  'EmploymentDeclarationStatus',
  'EmploymentSponsorshipStatus',
  'EmploymentComplaintStatus',
  'EmploymentDisputeStatus',
  'LabourExternalDependencyType',
  'LabourExternalDependencyRecordedBy',
] as const;
