export const TREATMENT_FOUNDATION_MODEL_NAMES = [
  'PatientHealthcareProfile',
  'TreatmentProgram',
  'TreatmentProgramVersion',
  'TreatmentProgramProvider',
  'TreatmentProgramSite',
  'TreatmentProgramConditionReference',
  'TreatmentProgramEligibilityCriterion',
  'TreatmentApplication',
  'TreatmentReferral',
  'TreatmentReferralSource',
  'TreatmentScreening',
  'TreatmentEligibilityReview',
  'TreatmentEnrollment',
  'TreatmentEnrollmentStatusHistory',
  'TreatmentAppointmentReference',
  'TreatmentCareTeamReference',
  'TreatmentProgramAuthorization',
  'TreatmentProgramExternalDependency',
  'PatientTreatmentStatusProjection',
  'TreatmentPatientDataAccessGrant',
] as const;

export const TREATMENT_FOUNDATION_ENUM_NAMES = [
  'HealthcareDataClassification',
  'TreatmentProgramKind',
  'TreatmentProgramLifecycleStatus',
  'TreatmentApplicationStatus',
  'TreatmentReferralStatus',
  'TreatmentScreeningStatus',
  'TreatmentEligibilityReviewStatus',
  'ClinicalSuitabilityOutcome',
  'TreatmentAdministrativeEligibilityOutcome',
  'TreatmentEnrollmentStatus',
  'HealthcareActorPersona',
  'HealthcareAppointmentPrivacyClassification',
  'TreatmentProgramAuthorizationKind',
  'TreatmentExternalDependencyRecordedBy',
  'TreatmentProgramProviderRole',
] as const;
