export const SERVICE_PACK_MANIFEST_VERSION = '1.0' as const;

export const SERVICE_PACK_COMPILATION_CHECK_CODES = {
  REFERENTIAL_INTEGRITY: 'REFERENTIAL_INTEGRITY',
  CODE_UNIQUENESS: 'CODE_UNIQUENESS',
  SERVICE_SLUG_COLLISION: 'SERVICE_SLUG_COLLISION',
  DEPARTMENT_OWNERSHIP: 'DEPARTMENT_OWNERSHIP',
  AUTHORITY_MAPPING_EXISTENCE: 'AUTHORITY_MAPPING_EXISTENCE',
  GOVERNING_SOURCE_AUTHENTICATION: 'GOVERNING_SOURCE_AUTHENTICATION',
  FORM_FIELD_VALIDITY: 'FORM_FIELD_VALIDITY',
  WORKFLOW_GRAPH_VALIDITY: 'WORKFLOW_GRAPH_VALIDITY',
  DEAD_WORKFLOW_STAGES: 'DEAD_WORKFLOW_STAGES',
  MISSING_TRANSITIONS: 'MISSING_TRANSITIONS',
  INVALID_CONSEQUENTIAL_ACTION_MAPPING: 'INVALID_CONSEQUENTIAL_ACTION_MAPPING',
  MISSING_EVIDENCE_REQUIREMENT_REFERENCES: 'MISSING_EVIDENCE_REQUIREMENT_REFERENCES',
  FEE_DEFINITION_CONFLICTS: 'FEE_DEFINITION_CONFLICTS',
  OUTPUT_TYPE_CONFLICTS: 'OUTPUT_TYPE_CONFLICTS',
  INTEGRATION_DEPENDENCY_AVAILABILITY: 'INTEGRATION_DEPENDENCY_AVAILABILITY',
  EXTERNAL_AUTHORITY_DEPENDENCIES: 'EXTERNAL_AUTHORITY_DEPENDENCIES',
  REDRESS_ROUTE_COMPLETENESS: 'REDRESS_ROUTE_COMPLETENESS',
  SLA_CONFIGURATION_VALIDITY: 'SLA_CONFIGURATION_VALIDITY',
  UNSUPPORTED_DATA_CLASSIFICATIONS: 'UNSUPPORTED_DATA_CLASSIFICATIONS',
  CROSS_INSTITUTION_REFERENCE: 'CROSS_INSTITUTION_REFERENCE',
  ACTIVATION_BYPASS_FORBIDDEN: 'ACTIVATION_BYPASS_FORBIDDEN',
  AUTHORITY_CREATION_FORBIDDEN: 'AUTHORITY_CREATION_FORBIDDEN',
} as const;

export type ServicePackCompilationCheckCode =
  (typeof SERVICE_PACK_COMPILATION_CHECK_CODES)[keyof typeof SERVICE_PACK_COMPILATION_CHECK_CODES];

export const SERVICE_PACK_ISSUE_SEVERITY = {
  ERROR: 'ERROR',
  WARNING: 'WARNING',
} as const;

export type ServicePackIssueSeverity =
  (typeof SERVICE_PACK_ISSUE_SEVERITY)[keyof typeof SERVICE_PACK_ISSUE_SEVERITY];

export const SERVICE_PACK_CRITICAL_CHECK_CODES: readonly ServicePackCompilationCheckCode[] = [
  SERVICE_PACK_COMPILATION_CHECK_CODES.REFERENTIAL_INTEGRITY,
  SERVICE_PACK_COMPILATION_CHECK_CODES.DEPARTMENT_OWNERSHIP,
  SERVICE_PACK_COMPILATION_CHECK_CODES.AUTHORITY_MAPPING_EXISTENCE,
  SERVICE_PACK_COMPILATION_CHECK_CODES.GOVERNING_SOURCE_AUTHENTICATION,
  SERVICE_PACK_COMPILATION_CHECK_CODES.WORKFLOW_GRAPH_VALIDITY,
  SERVICE_PACK_COMPILATION_CHECK_CODES.INVALID_CONSEQUENTIAL_ACTION_MAPPING,
  SERVICE_PACK_COMPILATION_CHECK_CODES.INTEGRATION_DEPENDENCY_AVAILABILITY,
  SERVICE_PACK_COMPILATION_CHECK_CODES.EXTERNAL_AUTHORITY_DEPENDENCIES,
  SERVICE_PACK_COMPILATION_CHECK_CODES.CROSS_INSTITUTION_REFERENCE,
  SERVICE_PACK_COMPILATION_CHECK_CODES.ACTIVATION_BYPASS_FORBIDDEN,
  SERVICE_PACK_COMPILATION_CHECK_CODES.AUTHORITY_CREATION_FORBIDDEN,
];

export const SERVICE_PACK_FORBIDDEN_MANIFEST_FIELDS = [
  'bypassActivation',
  'forceActivation',
  'maturityStatus',
  'publicAvailability',
  'createAuthority',
  'createFunctionAuthority',
  'activationOverride',
] as const;

export const SERVICE_PACK_SUPPORTED_DATA_CLASSIFICATIONS = [
  'PUBLIC',
  'INTERNAL',
  'RESTRICTED',
] as const;

export const SERVICE_PACK_COMPILATION_DISCLAIMER =
  'Service pack compilation is a dry-run validation only. Compilation does not mutate production configuration, create authority, or activate services.';
