export const NON_PRODUCTION_PHASE_6F_FIXTURE_MARKER = 'NON_PRODUCTION_PHASE_6F_TEST_ONLY';

export const FORBIDDEN_CASE_COORDINATION_AUTHORITY_FIELDS = [
  'canApprove',
  'grantsAuthority',
  'isDecisionMaker',
  'waivesRequirement',
  'createsCompensation',
] as const;

export const CASE_COORDINATION_EXPLANATION_CODES = {
  ASSIGNMENT_NOT_AUTHORITY: 'ASSIGNMENT_NOT_AUTHORITY',
  CASE_MANAGER_NOT_DECISION_MAKER: 'CASE_MANAGER_NOT_DECISION_MAKER',
  REFERRAL_PRESERVES_INSTITUTION: 'REFERRAL_PRESERVES_INSTITUTION',
  EXTERNAL_RESPONSE_NOT_ABSEZ_DECISION: 'EXTERNAL_RESPONSE_NOT_ABSEZ_DECISION',
  CONSULTATION_NOT_CONCURRENCE: 'CONSULTATION_NOT_CONCURRENCE',
  SLA_BREACH_NOT_APPROVAL: 'SLA_BREACH_NOT_APPROVAL',
  ESCALATION_PRESERVES_AUTHORITY: 'ESCALATION_PRESERVES_AUTHORITY',
  EXPIRED_DETERMINATION_UNSATISFIED: 'EXPIRED_DETERMINATION_UNSATISFIED',
  WRONG_EXTERNAL_AUTHORITY_UNSATISFIED: 'WRONG_EXTERNAL_AUTHORITY_UNSATISFIED',
  BLOCKING_ISSUE_PREVENTS_ADVANCE: 'BLOCKING_ISSUE_PREVENTS_ADVANCE',
} as const;
