export enum RouteClass {
  PUBLIC = 'PUBLIC',
  AUTHENTICATED_SELF_SERVICE = 'AUTHENTICATED_SELF_SERVICE',
  AUTHENTICATED_INSTITUTIONAL = 'AUTHENTICATED_INSTITUTIONAL',
  RESTRICTED_ADMINISTRATIVE = 'RESTRICTED_ADMINISTRATIVE',
  CONSEQUENTIAL_AUTHORITY_CONTROLLED = 'CONSEQUENTIAL_AUTHORITY_CONTROLLED',
  SYSTEM_HEALTH = 'SYSTEM/HEALTH',
}
