export const S19_BOUNDARY_DISCLAIMER =
  'Payment, messaging, and integration success satisfy operational obligations only. They do not approve applications, issue licences, record decisions, or grant authority.';

export const OPERATIONAL_PROVIDER_READINESS_CODES = {
  PROHIBITED_PAYMENT_ADAPTER: 'PROHIBITED_PAYMENT_ADAPTER',
  PROHIBITED_EMAIL_ADAPTER: 'PROHIBITED_EMAIL_ADAPTER',
  PROHIBITED_SMS_ADAPTER: 'PROHIBITED_SMS_ADAPTER',
  PAYMENT_PROVIDER_NOT_CONFIGURED: 'PAYMENT_PROVIDER_NOT_CONFIGURED',
  EMAIL_PROVIDER_NOT_CONFIGURED: 'EMAIL_PROVIDER_NOT_CONFIGURED',
  SMS_PROVIDER_NOT_CONFIGURED: 'SMS_PROVIDER_NOT_CONFIGURED',
  OPERATIONAL_READINESS_BLOCKED: 'OPERATIONAL_READINESS_BLOCKED',
} as const;

export const S19_REASON_CODES = {
  AUTHORITATIVE_KPI_SUBMISSION_FORBIDDEN: 'AUTHORITATIVE_KPI_SUBMISSION_FORBIDDEN',
  COMPUTED_METRIC_VALUE_REQUIRED: 'COMPUTED_METRIC_VALUE_REQUIRED',
  EXECUTIVE_REPORT_INSTITUTION_SCOPE_REQUIRED: 'EXECUTIVE_REPORT_INSTITUTION_SCOPE_REQUIRED',
  EXECUTIVE_REPORT_CROSS_INSTITUTION_DENIED: 'EXECUTIVE_REPORT_CROSS_INSTITUTION_DENIED',
  SERVICE_INTAKE_BLOCKED: 'SERVICE_INTAKE_BLOCKED',
  SERVICE_ISSUANCE_BLOCKED: 'SERVICE_ISSUANCE_BLOCKED',
  ACTIVATION_EVIDENCE_REQUIRED: 'ACTIVATION_EVIDENCE_REQUIRED',
  INTEGRATION_EXCHANGE_IDEMPOTENT_REPLAY: 'INTEGRATION_EXCHANGE_IDEMPOTENT_REPLAY',
} as const;

export const APPENDIX_G_REPORT_VERSION = '2026-09-28';

export const OPERATIONAL_COMMUNICATION_MAX_DELIVERY_ATTEMPTS = 5;
export const OPERATIONAL_INTEGRATION_MAX_EXCHANGE_ATTEMPTS = 5;
