export const PHASE_PROPERTY_REGISTRY_MODEL_NAMES = [
  'PropertyRegistryConfiguration',
  'PropertyParcel',
  'PropertyInterest',
  'PropertyOwnershipHistory',
  'PropertyRegistryApplication',
  'PropertyTransferDecision',
  'PropertyEncumbrance',
  'PropertyEncumbranceHistory',
  'PropertySurveySubmission',
  'PropertyRegistryCertificate',
  'PropertyInterestEntitlement',
  'PropertyAccessAudit',
] as const;

export const PHASE_PROPERTY_REGISTRY_ENUM_NAMES = [
  'PropertyPublicVerificationMode',
  'PropertyParcelStatus',
  'PropertyInterestKind',
  'PropertyInterestStatus',
  'PropertyRegistryApplicationType',
  'PropertyRegistryApplicationStatus',
  'PropertyTransferDecisionOutcome',
  'PropertyEncumbranceKind',
  'PropertyEncumbranceStatus',
  'PropertySurveySubmissionStatus',
  'PropertyCertificateStatus',
  'PropertyAccessActorKind',
] as const;

export const FORBIDDEN_PROPERTY_CLIENT_FIELDS = [
  'registryVersion',
  'internalParcelIdentifier',
  'titleHolderIdentityId',
  'encumbranceReleaseDecisionId',
] as const;

export const CADASTRE_PROPERTY_REGISTRY_MODEL_NAMES = [
  'LandParcel',
  'ParcelIdentifier',
  'ParcelGeometryReference',
  'ParcelAddress',
  'PropertyRecord',
  'CadastrePropertyInterest',
  'CadastrePropertyInterestHolder',
  'CadastrePropertyInterestHistory',
  'TitleRecord',
  'TitleVersion',
  'TitleInstrumentReference',
  'PropertyTransfer',
  'TransferParty',
  'CadastrePropertyEncumbrance',
  'MortgageReference',
  'LienReference',
  'EasementReference',
  'RestrictionReference',
  'SurveyRecord',
  'SurveyPlanReference',
  'SurveyorCertificationReference',
  'PropertyValuationRecord',
  'PropertyTaxReference',
  'PropertyRegistryEntry',
  'PropertyRegistryCorrection',
  'PropertyRegistryVerification',
  'PropertyRegistryRestriction',
  'PropertyTransactionHistory',
  'PropertyTransferEvidenceLink',
  'PropertyRegistryAuditEvent',
] as const;

export const CADASTRE_PROPERTY_REGISTRY_ENUM_NAMES = [
  'PropertyRegistryAccessClassification',
  'PropertyTransferApplicationStatus',
  'TitleRecordStatus',
  'PropertyInterestType',
  'PropertyInterestHolderRole',
  'PropertyEncumbranceType',
  'PropertyValuationPurpose',
  'PropertyRegistryVerificationState',
  'PropertyRegistryCorrectionStatus',
  'PropertyRegistryAuditEventType',
  'TransferPartyRole',
  'PropertyTransactionHistoryEventType',
] as const;
