export const PROPERTY_REGISTRY_MODEL_NAMES = [
  'LandParcel',
  'ParcelIdentifier',
  'ParcelGeometryReference',
  'ParcelAddress',
  'PropertyRecord',
  'PropertyInterest',
  'PropertyInterestHolder',
  'PropertyInterestHistory',
  'TitleRecord',
  'TitleVersion',
  'TitleInstrumentReference',
  'PropertyTransfer',
  'TransferParty',
  'PropertyEncumbrance',
  'MortgageReference',
  'LienReference',
  'EasementReference',
  'RestrictionReference',
  'SurveyRecord',
  'SurveyPlanReference',
  'SurveyorCertificationReference',
  'PropertyValuationRecord',
  'PropertyTaxReference',
  'PropertyRegistryEntry',
  'PropertyRegistryCorrection',
  'PropertyRegistryVerification',
  'PropertyRegistryRestriction',
  'PropertyTransactionHistory',
  'PropertyTransferEvidenceLink',
  'PropertyRegistryAuditEvent',
] as const;

export const PROPERTY_REGISTRY_ENUM_NAMES = [
  'PropertyRegistryAccessClassification',
  'PropertyTransferApplicationStatus',
  'TitleRecordStatus',
  'PropertyInterestType',
  'PropertyInterestHolderRole',
  'PropertyEncumbranceType',
  'PropertyEncumbranceStatus',
  'PropertyValuationPurpose',
  'PropertyRegistryVerificationState',
  'PropertyRegistryCorrectionStatus',
  'PropertyRegistryAuditEventType',
  'TransferPartyRole',
  'PropertyTransactionHistoryEventType',
] as const;
