export const PHASE_11B_INVARIANTS = [
  { id: 1, description: 'Client redirect cannot mark payment SETTLED' },
  { id: 2, description: 'Duplicate webhook does not duplicate payment' },
  { id: 3, description: 'Invalid webhook signature rejected' },
  { id: 4, description: 'Replayed webhook rejected' },
  { id: 5, description: 'Amount mismatch safe-halts reconciliation' },
  { id: 6, description: 'Currency mismatch rejected' },
  { id: 7, description: 'Payment cannot exceed invoice incorrectly' },
  { id: 8, description: 'Settled payment updates financial balance only' },
  { id: 9, description: 'Payment does not approve application' },
  { id: 10, description: 'Payment does not issue instrument' },
  { id: 11, description: 'Payment does not renew instrument' },
  { id: 12, description: 'Payment does not satisfy compliance automatically' },
  { id: 13, description: 'Receipt generated only after permitted payment confirmation' },
  { id: 14, description: 'Receipt immutable' },
  { id: 15, description: 'PAN/CVV never persisted' },
  { id: 16, description: 'Provider credentials never returned in API' },
  { id: 17, description: 'Manual payment requires controlled actor' },
  { id: 18, description: 'AI cannot execute payment' },
  { id: 19, description: 'AI cannot mark transaction settled' },
] as const;
