export const GOVERNED_AI_CONFIG_KEY = 'governedAi';

export const FORBIDDEN_AI_GOVERNMENT_ACTIONS = [
  'APPROVE',
  'DECIDE',
  'SIGN',
  'ISSUE',
  'ENFORCE',
  'SUSPEND',
  'REVOKE',
  'HEAR_REVIEW',
] as const;

export const AI_POLICY_REASON_CODES = {
  AGENT_NOT_REGISTERED: 'AGENT_NOT_REGISTERED',
  AGENT_INACTIVE: 'AGENT_INACTIVE',
  AGENT_IDENTITY_INACTIVE: 'AGENT_IDENTITY_INACTIVE',
  MODEL_NOT_APPROVED: 'MODEL_NOT_APPROVED',
  MODEL_SUSPENDED: 'MODEL_SUSPENDED',
  PROVIDER_NOT_APPROVED: 'PROVIDER_NOT_APPROVED',
  PROVIDER_SUSPENDED: 'PROVIDER_SUSPENDED',
  DATA_CLASS_FORBIDDEN: 'DATA_CLASS_FORBIDDEN',
  POLICY_INDETERMINATE: 'POLICY_INDETERMINATE',
  POLICY_SERVICE_UNAVAILABLE: 'POLICY_SERVICE_UNAVAILABLE',
  TOOL_NOT_ALLOWLISTED: 'TOOL_NOT_ALLOWLISTED',
  EXTERNAL_PROVIDER_DISABLED: 'EXTERNAL_PROVIDER_DISABLED',
  AUDIT_RECORD_REQUIRED: 'AUDIT_RECORD_REQUIRED',
  HUMAN_REVIEW_REQUIRED: 'HUMAN_REVIEW_REQUIRED',
  GOVERNANCE_CHAIN_INCOMPLETE: 'GOVERNANCE_CHAIN_INCOMPLETE',
} as const;

export const AI_GOVERNANCE_AUDIT_ACTIONS = {
  AI_CALL_REQUESTED: 'AI_CALL_REQUESTED',
  AI_CALL_COMPLETED: 'AI_CALL_COMPLETED',
  AI_CALL_DENIED: 'AI_CALL_DENIED',
  AI_OUTPUT_DELIVERED: 'AI_OUTPUT_DELIVERED',
} as const;

export const GOVERNED_AI_READINESS_CODES = {
  EXTERNAL_PROVIDER_NOT_APPROVED: 'EXTERNAL_AI_PROVIDER_NOT_APPROVED',
  EXTERNAL_PROVIDER_NOT_CONFIGURED: 'EXTERNAL_AI_PROVIDER_NOT_CONFIGURED',
} as const;

export const S20_GOVERNED_AI_MODEL_NAMES = [
  'AiAgentIdentity',
  'AiModelProviderRegistry',
  'AiModelDefinition',
  'AiModelVersion',
  'AiAgentDefinition',
  'AiAgentToolAllowlist',
  'AiAgentDataClassAllowlist',
  'AiGovernanceSuspension',
  'AiPolicyDecisionRecord',
  'AiCallRecord',
  'AiCallInputRecord',
  'AiCallSourceReference',
  'AiCallOutputRecord',
  'AiCallOutputEdit',
  'AiCallReviewRecord',
] as const;
