export enum ExternalAuthorityType {
  GOVERNMENT_AUTHORITY = 'GOVERNMENT_AUTHORITY',
  REGULATOR = 'REGULATOR',
  JUDICIAL_BODY = 'JUDICIAL_BODY',
  PROFESSIONAL_BODY = 'PROFESSIONAL_BODY',
  PUBLIC_REGISTRY = 'PUBLIC_REGISTRY',
  INTERNATIONAL_BODY = 'INTERNATIONAL_BODY',
  OTHER = 'OTHER',
}
