export enum InstitutionExternalAuthorityRelationshipType {
  COORDINATION = 'COORDINATION',
  REFERRAL = 'REFERRAL',
  CONSULTATION = 'CONSULTATION',
  VERIFICATION = 'VERIFICATION',
  SUPERVISION = 'SUPERVISION',
  REGULATORY = 'REGULATORY',
  DEPENDENCY = 'DEPENDENCY',
  OTHER = 'OTHER',
}
